// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BMS_ROLE int32

const (
	BMS_ROLE_BR_UNKNOWN      BMS_ROLE = 0
	BMS_ROLE_BR_SYSTEM_ADMIN BMS_ROLE = 1
	BMS_ROLE_BR_BMS_ADMIN    BMS_ROLE = 2
	BMS_ROLE_BR_BMS_LEADER   BMS_ROLE = 3
	BMS_ROLE_BR_BMS_EXECUTOR BMS_ROLE = 4
	BMS_ROLE_BR_BMS_VIEWER   BMS_ROLE = 5
)

// Enum value maps for BMS_ROLE.
var (
	BMS_ROLE_name = map[int32]string{
		0: "BR_UNKNOWN",
		1: "BR_SYSTEM_ADMIN",
		2: "BR_BMS_ADMIN",
		3: "BR_BMS_LEADER",
		4: "BR_BMS_EXECUTOR",
		5: "BR_BMS_VIEWER",
	}
	BMS_ROLE_value = map[string]int32{
		"BR_UNKNOWN":      0,
		"BR_SYSTEM_ADMIN": 1,
		"BR_BMS_ADMIN":    2,
		"BR_BMS_LEADER":   3,
		"BR_BMS_EXECUTOR": 4,
		"BR_BMS_VIEWER":   5,
	}
)

func (x BMS_ROLE) Enum() *BMS_ROLE {
	p := new(BMS_ROLE)
	*p = x
	return p
}

func (x BMS_ROLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BMS_ROLE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Auth_proto_enumTypes[0].Descriptor()
}

func (BMS_ROLE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Auth_proto_enumTypes[0]
}

func (x BMS_ROLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BMS_ROLE.Descriptor instead.
func (BMS_ROLE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Auth_proto_rawDescGZIP(), []int{0}
}

type LoginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"` //`json:"user_name"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"` //`json:"password"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInfo) Reset() {
	*x = LoginInfo{}
	mi := &file_pkg_proto_Auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfo) ProtoMessage() {}

func (x *LoginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfo.ProtoReflect.Descriptor instead.
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthUser struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ID               string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                               //`json:"id" bson:"_id"`
	Email            string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`                         //`json:"email" bson:"email"`
	FirstName        string                 `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`                 //`json:"first_name" bson:"first_name"`
	LastName         string                 `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`                   //`json:"last_name" bson:"last_name"`
	Bio              string                 `protobuf:"bytes,5,opt,name=Bio,proto3" json:"Bio,omitempty"`                             //`json:"bio" bson:"bio"`
	UserName         string                 `protobuf:"bytes,6,opt,name=UserName,proto3" json:"UserName,omitempty"`                   //`json:"user_name" bson:"user_name" index:"unique"`
	UnitCode         string                 `protobuf:"bytes,7,opt,name=UnitCode,proto3" json:"UnitCode,omitempty"`                   //`json:"unit_code" bson:"unit_code"`
	Password         string                 `protobuf:"bytes,8,opt,name=Password,proto3" json:"Password,omitempty"`                   //`json:"password" bson:"password"`
	Role             BMS_ROLE               `protobuf:"varint,9,opt,name=Role,proto3,enum=auth.BMS_ROLE" json:"Role,omitempty"`       //`json:"role" bson:"role"`
	LoginFailedCount uint32                 `protobuf:"varint,10,opt,name=LoginFailedCount,proto3" json:"LoginFailedCount,omitempty"` //`json:"login_failed_count" bson:"login_failed_count"`
	IsLoggedIn       bool                   `protobuf:"varint,11,opt,name=IsLoggedIn,proto3" json:"IsLoggedIn,omitempty"`             //`json:"is_logged_in" bson:"is_logged_in"`
	Token            string                 `protobuf:"bytes,12,opt,name=Token,proto3" json:"Token,omitempty"`                        //`json:"token" bson:"token"`
	// Thong tin Audit
	CreatedAt     uint64 `protobuf:"varint,13,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` //`json:"created_at" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64 `protobuf:"varint,14,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"` //`json:"updated_at" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string `protobuf:"bytes,15,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`  //`json:"created_by" bson:"created_by"`
	UpdatedBy     string `protobuf:"bytes,16,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`  //`json:"updated_by" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUser) Reset() {
	*x = AuthUser{}
	mi := &file_pkg_proto_Auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUser) ProtoMessage() {}

func (x *AuthUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUser.ProtoReflect.Descriptor instead.
func (*AuthUser) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthUser) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AuthUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AuthUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AuthUser) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AuthUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuthUser) GetUnitCode() string {
	if x != nil {
		return x.UnitCode
	}
	return ""
}

func (x *AuthUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthUser) GetRole() BMS_ROLE {
	if x != nil {
		return x.Role
	}
	return BMS_ROLE_BR_UNKNOWN
}

func (x *AuthUser) GetLoginFailedCount() uint32 {
	if x != nil {
		return x.LoginFailedCount
	}
	return 0
}

func (x *AuthUser) GetIsLoggedIn() bool {
	if x != nil {
		return x.IsLoggedIn
	}
	return false
}

func (x *AuthUser) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthUser) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AuthUser) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AuthUser) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AuthUser) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUser      []*AuthUser            `protobuf:"bytes,1,rep,name=AuthUser,proto3" json:"AuthUser,omitempty"`      //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAuthUserResponse) Reset() {
	*x = SearchAuthUserResponse{}
	mi := &file_pkg_proto_Auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAuthUserResponse) ProtoMessage() {}

func (x *SearchAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAuthUserResponse.ProtoReflect.Descriptor instead.
func (*SearchAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Auth_proto_rawDescGZIP(), []int{2}
}

func (x *SearchAuthUserResponse) GetAuthUser() []*AuthUser {
	if x != nil {
		return x.AuthUser
	}
	return nil
}

func (x *SearchAuthUserResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_Auth_proto protoreflect.FileDescriptor

const file_pkg_proto_Auth_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/Auth.proto\x12\x04auth\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\"C\n" +
	"\tLoginInfo\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\xce\x03\n" +
	"\bAuthUser\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x1c\n" +
	"\tFirstName\x18\x03 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x04 \x01(\tR\bLastName\x12\x10\n" +
	"\x03Bio\x18\x05 \x01(\tR\x03Bio\x12\x1a\n" +
	"\bUserName\x18\x06 \x01(\tR\bUserName\x12\x1a\n" +
	"\bUnitCode\x18\a \x01(\tR\bUnitCode\x12\x1a\n" +
	"\bPassword\x18\b \x01(\tR\bPassword\x12\"\n" +
	"\x04Role\x18\t \x01(\x0e2\x0e.auth.BMS_ROLER\x04Role\x12*\n" +
	"\x10LoginFailedCount\x18\n" +
	" \x01(\rR\x10LoginFailedCount\x12\x1e\n" +
	"\n" +
	"IsLoggedIn\x18\v \x01(\bR\n" +
	"IsLoggedIn\x12\x14\n" +
	"\x05Token\x18\f \x01(\tR\x05Token\x12\x1c\n" +
	"\tCreatedAt\x18\r \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x0e \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x0f \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18\x10 \x01(\tR\tUpdatedBy\"d\n" +
	"\x16SearchAuthUserResponse\x12*\n" +
	"\bAuthUser\x18\x01 \x03(\v2\x0e.auth.AuthUserR\bAuthUser\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount*|\n" +
	"\bBMS_ROLE\x12\x0e\n" +
	"\n" +
	"BR_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fBR_SYSTEM_ADMIN\x10\x01\x12\x10\n" +
	"\fBR_BMS_ADMIN\x10\x02\x12\x11\n" +
	"\rBR_BMS_LEADER\x10\x03\x12\x13\n" +
	"\x0fBR_BMS_EXECUTOR\x10\x04\x12\x11\n" +
	"\rBR_BMS_VIEWER\x10\x052\xc6\x01\n" +
	"\x0fAuthUserService\x12(\n" +
	"\x06create\x12\x0e.auth.AuthUser\x1a\x0e.auth.AuthUser\x12E\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x1c.auth.SearchAuthUserResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Auth_proto_rawDescOnce sync.Once
	file_pkg_proto_Auth_proto_rawDescData []byte
)

func file_pkg_proto_Auth_proto_rawDescGZIP() []byte {
	file_pkg_proto_Auth_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Auth_proto_rawDesc), len(file_pkg_proto_Auth_proto_rawDesc)))
	})
	return file_pkg_proto_Auth_proto_rawDescData
}

var file_pkg_proto_Auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_Auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_Auth_proto_goTypes = []any{
	(BMS_ROLE)(0),                  // 0: auth.BMS_ROLE
	(*LoginInfo)(nil),              // 1: auth.LoginInfo
	(*AuthUser)(nil),               // 2: auth.AuthUser
	(*SearchAuthUserResponse)(nil), // 3: auth.SearchAuthUserResponse
	(*SearchOptions)(nil),          // 4: search_options.SearchOptions
	(*PatchOptions)(nil),           // 5: patch_options.PatchOptions
	(*PatchResponse)(nil),          // 6: patch_options.PatchResponse
}
var file_pkg_proto_Auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthUser.Role:type_name -> auth.BMS_ROLE
	2, // 1: auth.SearchAuthUserResponse.AuthUser:type_name -> auth.AuthUser
	2, // 2: auth.AuthUserService.create:input_type -> auth.AuthUser
	4, // 3: auth.AuthUserService.search:input_type -> search_options.SearchOptions
	5, // 4: auth.AuthUserService.patch:input_type -> patch_options.PatchOptions
	2, // 5: auth.AuthUserService.create:output_type -> auth.AuthUser
	3, // 6: auth.AuthUserService.search:output_type -> auth.SearchAuthUserResponse
	6, // 7: auth.AuthUserService.patch:output_type -> patch_options.PatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_Auth_proto_init() }
func file_pkg_proto_Auth_proto_init() {
	if File_pkg_proto_Auth_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Auth_proto_rawDesc), len(file_pkg_proto_Auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_Auth_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Auth_proto_depIdxs,
		EnumInfos:         file_pkg_proto_Auth_proto_enumTypes,
		MessageInfos:      file_pkg_proto_Auth_proto_msgTypes,
	}.Build()
	File_pkg_proto_Auth_proto = out.File
	file_pkg_proto_Auth_proto_goTypes = nil
	file_pkg_proto_Auth_proto_depIdxs = nil
}
