// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Datasource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AT_DATASOURCE_CONNECTION_TYPE int32

const (
	AT_DATASOURCE_CONNECTION_TYPE_ADTC_UNKNOWN AT_DATASOURCE_CONNECTION_TYPE = 0
	AT_DATASOURCE_CONNECTION_TYPE_ADTC_GCS     AT_DATASOURCE_CONNECTION_TYPE = 1
	AT_DATASOURCE_CONNECTION_TYPE_ADTC_BV5     AT_DATASOURCE_CONNECTION_TYPE = 2
	AT_DATASOURCE_CONNECTION_TYPE_ADTC_RMID    AT_DATASOURCE_CONNECTION_TYPE = 3
)

// Enum value maps for AT_DATASOURCE_CONNECTION_TYPE.
var (
	AT_DATASOURCE_CONNECTION_TYPE_name = map[int32]string{
		0: "ADTC_UNKNOWN",
		1: "ADTC_GCS",
		2: "ADTC_BV5",
		3: "ADTC_RMID",
	}
	AT_DATASOURCE_CONNECTION_TYPE_value = map[string]int32{
		"ADTC_UNKNOWN": 0,
		"ADTC_GCS":     1,
		"ADTC_BV5":     2,
		"ADTC_RMID":    3,
	}
)

func (x AT_DATASOURCE_CONNECTION_TYPE) Enum() *AT_DATASOURCE_CONNECTION_TYPE {
	p := new(AT_DATASOURCE_CONNECTION_TYPE)
	*p = x
	return p
}

func (x AT_DATASOURCE_CONNECTION_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_DATASOURCE_CONNECTION_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Datasource_proto_enumTypes[0].Descriptor()
}

func (AT_DATASOURCE_CONNECTION_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Datasource_proto_enumTypes[0]
}

func (x AT_DATASOURCE_CONNECTION_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_DATASOURCE_CONNECTION_TYPE.Descriptor instead.
func (AT_DATASOURCE_CONNECTION_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Datasource_proto_rawDescGZIP(), []int{0}
}

type Datasource struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	ID             string                        `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	DataSourceAdd  string                        `protobuf:"bytes,2,opt,name=DataSourceAdd,proto3" json:"datasource_add,omitempty" bson:"datasource_add"`
	DatasourcePort string                        `protobuf:"bytes,3,opt,name=DatasourcePort,proto3" json:"datasource_port,omitempty" bson:"datasource_port"`
	ConnectionType AT_DATASOURCE_CONNECTION_TYPE `protobuf:"varint,4,opt,name=ConnectionType,proto3,enum=datasouce.AT_DATASOURCE_CONNECTION_TYPE" json:"connection_type,omitempty" bson:"connection_type"`
	Position       []float64                     `protobuf:"fixed64,5,rep,packed,name=Position,proto3" json:"position,omitempty" bson:"position"`
	Coverage       float64                       `protobuf:"fixed64,6,opt,name=Coverage,proto3" json:"coverage,omitempty" bson:"coverage"`
	CreatedAt      uint64                        `protobuf:"varint,50,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt      uint64                        `protobuf:"varint,51,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy      string                        `protobuf:"bytes,52,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy      string                        `protobuf:"bytes,53,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Datasource) Reset() {
	*x = Datasource{}
	mi := &file_pkg_proto_Datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datasource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datasource) ProtoMessage() {}

func (x *Datasource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datasource.ProtoReflect.Descriptor instead.
func (*Datasource) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Datasource_proto_rawDescGZIP(), []int{0}
}

func (x *Datasource) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Datasource) GetDataSourceAdd() string {
	if x != nil {
		return x.DataSourceAdd
	}
	return ""
}

func (x *Datasource) GetDatasourcePort() string {
	if x != nil {
		return x.DatasourcePort
	}
	return ""
}

func (x *Datasource) GetConnectionType() AT_DATASOURCE_CONNECTION_TYPE {
	if x != nil {
		return x.ConnectionType
	}
	return AT_DATASOURCE_CONNECTION_TYPE_ADTC_UNKNOWN
}

func (x *Datasource) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Datasource) GetCoverage() float64 {
	if x != nil {
		return x.Coverage
	}
	return 0
}

func (x *Datasource) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Datasource) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Datasource) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Datasource) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasources   []*Datasource          `protobuf:"bytes,1,rep,name=Datasources,proto3" json:"Datasources,omitempty"` //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`  //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDatasourceResponse) Reset() {
	*x = SearchDatasourceResponse{}
	mi := &file_pkg_proto_Datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDatasourceResponse) ProtoMessage() {}

func (x *SearchDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDatasourceResponse.ProtoReflect.Descriptor instead.
func (*SearchDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Datasource_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDatasourceResponse) GetDatasources() []*Datasource {
	if x != nil {
		return x.Datasources
	}
	return nil
}

func (x *SearchDatasourceResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_Datasource_proto protoreflect.FileDescriptor

const file_pkg_proto_Datasource_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/Datasource.proto\x12\tdatasouce\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\"\xec\x02\n" +
	"\n" +
	"Datasource\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12$\n" +
	"\rDataSourceAdd\x18\x02 \x01(\tR\rDataSourceAdd\x12&\n" +
	"\x0eDatasourcePort\x18\x03 \x01(\tR\x0eDatasourcePort\x12P\n" +
	"\x0eConnectionType\x18\x04 \x01(\x0e2(.datasouce.AT_DATASOURCE_CONNECTION_TYPER\x0eConnectionType\x12\x1a\n" +
	"\bPosition\x18\x05 \x03(\x01R\bPosition\x12\x1a\n" +
	"\bCoverage\x18\x06 \x01(\x01R\bCoverage\x12\x1c\n" +
	"\tCreatedAt\x182 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x183 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x184 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x185 \x01(\tR\tUpdatedBy\"s\n" +
	"\x18SearchDatasourceResponse\x127\n" +
	"\vDatasources\x18\x01 \x03(\v2\x15.datasouce.DatasourceR\vDatasources\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount*\\\n" +
	"\x1dAT_DATASOURCE_CONNECTION_TYPE\x12\x10\n" +
	"\fADTC_UNKNOWN\x10\x00\x12\f\n" +
	"\bADTC_GCS\x10\x01\x12\f\n" +
	"\bADTC_BV5\x10\x02\x12\r\n" +
	"\tADTC_RMID\x10\x032\xdd\x01\n" +
	"\x11DatasourceService\x126\n" +
	"\x06create\x12\x15.datasouce.Datasource\x1a\x15.datasouce.Datasource\x12L\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a#.datasouce.SearchDatasourceResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Datasource_proto_rawDescOnce sync.Once
	file_pkg_proto_Datasource_proto_rawDescData []byte
)

func file_pkg_proto_Datasource_proto_rawDescGZIP() []byte {
	file_pkg_proto_Datasource_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Datasource_proto_rawDesc), len(file_pkg_proto_Datasource_proto_rawDesc)))
	})
	return file_pkg_proto_Datasource_proto_rawDescData
}

var file_pkg_proto_Datasource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_Datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_Datasource_proto_goTypes = []any{
	(AT_DATASOURCE_CONNECTION_TYPE)(0), // 0: datasouce.AT_DATASOURCE_CONNECTION_TYPE
	(*Datasource)(nil),                 // 1: datasouce.Datasource
	(*SearchDatasourceResponse)(nil),   // 2: datasouce.SearchDatasourceResponse
	(*SearchOptions)(nil),              // 3: search_options.SearchOptions
	(*PatchOptions)(nil),               // 4: patch_options.PatchOptions
	(*PatchResponse)(nil),              // 5: patch_options.PatchResponse
}
var file_pkg_proto_Datasource_proto_depIdxs = []int32{
	0, // 0: datasouce.Datasource.ConnectionType:type_name -> datasouce.AT_DATASOURCE_CONNECTION_TYPE
	1, // 1: datasouce.SearchDatasourceResponse.Datasources:type_name -> datasouce.Datasource
	1, // 2: datasouce.DatasourceService.create:input_type -> datasouce.Datasource
	3, // 3: datasouce.DatasourceService.search:input_type -> search_options.SearchOptions
	4, // 4: datasouce.DatasourceService.patch:input_type -> patch_options.PatchOptions
	1, // 5: datasouce.DatasourceService.create:output_type -> datasouce.Datasource
	2, // 6: datasouce.DatasourceService.search:output_type -> datasouce.SearchDatasourceResponse
	5, // 7: datasouce.DatasourceService.patch:output_type -> patch_options.PatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_Datasource_proto_init() }
func file_pkg_proto_Datasource_proto_init() {
	if File_pkg_proto_Datasource_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Datasource_proto_rawDesc), len(file_pkg_proto_Datasource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_Datasource_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Datasource_proto_depIdxs,
		EnumInfos:         file_pkg_proto_Datasource_proto_enumTypes,
		MessageInfos:      file_pkg_proto_Datasource_proto_msgTypes,
	}.Build()
	File_pkg_proto_Datasource_proto = out.File
	file_pkg_proto_Datasource_proto_goTypes = nil
	file_pkg_proto_Datasource_proto_depIdxs = nil
}
