// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/DirectCommand.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirectCommandService_Create_FullMethodName = "/drone.DirectCommandService/create"
	DirectCommandService_Search_FullMethodName = "/drone.DirectCommandService/search"
	DirectCommandService_Patch_FullMethodName  = "/drone.DirectCommandService/patch"
	DirectCommandService_Update_FullMethodName = "/drone.DirectCommandService/update"
)

// DirectCommandServiceClient is the client API for DirectCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirectCommandServiceClient interface {
	Create(ctx context.Context, in *DirectCommand, opts ...grpc.CallOption) (*DirectCommand, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchDirectCommandResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
	Update(ctx context.Context, in *DirectCommand, opts ...grpc.CallOption) (*DirectCommand, error)
}

type directCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectCommandServiceClient(cc grpc.ClientConnInterface) DirectCommandServiceClient {
	return &directCommandServiceClient{cc}
}

func (c *directCommandServiceClient) Create(ctx context.Context, in *DirectCommand, opts ...grpc.CallOption) (*DirectCommand, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectCommand)
	err := c.cc.Invoke(ctx, DirectCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directCommandServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchDirectCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDirectCommandResponse)
	err := c.cc.Invoke(ctx, DirectCommandService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directCommandServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, DirectCommandService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directCommandServiceClient) Update(ctx context.Context, in *DirectCommand, opts ...grpc.CallOption) (*DirectCommand, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectCommand)
	err := c.cc.Invoke(ctx, DirectCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectCommandServiceServer is the server API for DirectCommandService service.
// All implementations must embed UnimplementedDirectCommandServiceServer
// for forward compatibility.
type DirectCommandServiceServer interface {
	Create(context.Context, *DirectCommand) (*DirectCommand, error)
	Search(context.Context, *SearchOptions) (*SearchDirectCommandResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	Update(context.Context, *DirectCommand) (*DirectCommand, error)
	mustEmbedUnimplementedDirectCommandServiceServer()
}

// UnimplementedDirectCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectCommandServiceServer struct{}

func (UnimplementedDirectCommandServiceServer) Create(context.Context, *DirectCommand) (*DirectCommand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDirectCommandServiceServer) Search(context.Context, *SearchOptions) (*SearchDirectCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDirectCommandServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedDirectCommandServiceServer) Update(context.Context, *DirectCommand) (*DirectCommand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDirectCommandServiceServer) mustEmbedUnimplementedDirectCommandServiceServer() {}
func (UnimplementedDirectCommandServiceServer) testEmbeddedByValue()                              {}

// UnsafeDirectCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectCommandServiceServer will
// result in compilation errors.
type UnsafeDirectCommandServiceServer interface {
	mustEmbedUnimplementedDirectCommandServiceServer()
}

func RegisterDirectCommandServiceServer(s grpc.ServiceRegistrar, srv DirectCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedDirectCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectCommandService_ServiceDesc, srv)
}

func _DirectCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectCommandServiceServer).Create(ctx, req.(*DirectCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectCommandService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectCommandServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectCommandService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectCommandServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectCommandService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectCommandServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectCommandService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectCommandServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectCommandServiceServer).Update(ctx, req.(*DirectCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectCommandService_ServiceDesc is the grpc.ServiceDesc for DirectCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DirectCommandService",
	HandlerType: (*DirectCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _DirectCommandService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _DirectCommandService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _DirectCommandService_Patch_Handler,
		},
		{
			MethodName: "update",
			Handler:    _DirectCommandService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/DirectCommand.proto",
}
