// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/DirectCommand.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AT_DIRECT_COMMAND_STATUS int32

const (
	AT_DIRECT_COMMAND_STATUS_ADCS_UNKNOWN AT_DIRECT_COMMAND_STATUS = 0
	AT_DIRECT_COMMAND_STATUS_ADCS_SENT    AT_DIRECT_COMMAND_STATUS = 1
	AT_DIRECT_COMMAND_STATUS_ADCS_ACK     AT_DIRECT_COMMAND_STATUS = 2
)

// Enum value maps for AT_DIRECT_COMMAND_STATUS.
var (
	AT_DIRECT_COMMAND_STATUS_name = map[int32]string{
		0: "ADCS_UNKNOWN",
		1: "ADCS_SENT",
		2: "ADCS_ACK",
	}
	AT_DIRECT_COMMAND_STATUS_value = map[string]int32{
		"ADCS_UNKNOWN": 0,
		"ADCS_SENT":    1,
		"ADCS_ACK":     2,
	}
)

func (x AT_DIRECT_COMMAND_STATUS) Enum() *AT_DIRECT_COMMAND_STATUS {
	p := new(AT_DIRECT_COMMAND_STATUS)
	*p = x
	return p
}

func (x AT_DIRECT_COMMAND_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_DIRECT_COMMAND_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_DirectCommand_proto_enumTypes[0].Descriptor()
}

func (AT_DIRECT_COMMAND_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_DirectCommand_proto_enumTypes[0]
}

func (x AT_DIRECT_COMMAND_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_DIRECT_COMMAND_STATUS.Descriptor instead.
func (AT_DIRECT_COMMAND_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_DirectCommand_proto_rawDescGZIP(), []int{0}
}

type DirectCommand struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	ID                  string                   `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	Content             string                   `protobuf:"bytes,2,opt,name=Content,proto3" json:"content,omitempty" bson:"content"`
	Src                 string                   `protobuf:"bytes,3,opt,name=Src,proto3" json:"src,omitempty" bson:"src"`
	Dest                string                   `protobuf:"bytes,4,opt,name=Dest,proto3" json:"dest,omitempty" bson:"dest"`
	DirectCommandStatus AT_DIRECT_COMMAND_STATUS `protobuf:"varint,5,opt,name=DirectCommandStatus,proto3,enum=drone.AT_DIRECT_COMMAND_STATUS" json:"command_status,omitempty" bson:"command_status"`
	CreatedAt           uint64                   `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt           uint64                   `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy           string                   `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy           string                   `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DirectCommand) Reset() {
	*x = DirectCommand{}
	mi := &file_pkg_proto_DirectCommand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCommand) ProtoMessage() {}

func (x *DirectCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_DirectCommand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCommand.ProtoReflect.Descriptor instead.
func (*DirectCommand) Descriptor() ([]byte, []int) {
	return file_pkg_proto_DirectCommand_proto_rawDescGZIP(), []int{0}
}

func (x *DirectCommand) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DirectCommand) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DirectCommand) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *DirectCommand) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *DirectCommand) GetDirectCommandStatus() AT_DIRECT_COMMAND_STATUS {
	if x != nil {
		return x.DirectCommandStatus
	}
	return AT_DIRECT_COMMAND_STATUS_ADCS_UNKNOWN
}

func (x *DirectCommand) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DirectCommand) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *DirectCommand) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DirectCommand) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchDirectCommandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DirectCommands []*DirectCommand       `protobuf:"bytes,1,rep,name=DirectCommands,proto3" json:"DirectCommands,omitempty"` //
	TotalCount     int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`        //
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchDirectCommandResponse) Reset() {
	*x = SearchDirectCommandResponse{}
	mi := &file_pkg_proto_DirectCommand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDirectCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDirectCommandResponse) ProtoMessage() {}

func (x *SearchDirectCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_DirectCommand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDirectCommandResponse.ProtoReflect.Descriptor instead.
func (*SearchDirectCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_DirectCommand_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDirectCommandResponse) GetDirectCommands() []*DirectCommand {
	if x != nil {
		return x.DirectCommands
	}
	return nil
}

func (x *SearchDirectCommandResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_DirectCommand_proto protoreflect.FileDescriptor

const file_pkg_proto_DirectCommand_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/DirectCommand.proto\x12\x05drone\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\x1a pkg/proto/SpatialAttribute.proto\"\xaa\x02\n" +
	"\rDirectCommand\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12\x10\n" +
	"\x03Src\x18\x03 \x01(\tR\x03Src\x12\x12\n" +
	"\x04Dest\x18\x04 \x01(\tR\x04Dest\x12Q\n" +
	"\x13DirectCommandStatus\x18\x05 \x01(\x0e2\x1f.drone.AT_DIRECT_COMMAND_STATUSR\x13DirectCommandStatus\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"{\n" +
	"\x1bSearchDirectCommandResponse\x12<\n" +
	"\x0eDirectCommands\x18\x01 \x03(\v2\x14.drone.DirectCommandR\x0eDirectCommands\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount*I\n" +
	"\x18AT_DIRECT_COMMAND_STATUS\x12\x10\n" +
	"\fADCS_UNKNOWN\x10\x00\x12\r\n" +
	"\tADCS_SENT\x10\x01\x12\f\n" +
	"\bADCS_ACK\x10\x022\x93\x02\n" +
	"\x14DirectCommandService\x124\n" +
	"\x06create\x12\x14.drone.DirectCommand\x1a\x14.drone.DirectCommand\x12K\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\".drone.SearchDirectCommandResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x124\n" +
	"\x06update\x12\x14.drone.DirectCommand\x1a\x14.drone.DirectCommandB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_DirectCommand_proto_rawDescOnce sync.Once
	file_pkg_proto_DirectCommand_proto_rawDescData []byte
)

func file_pkg_proto_DirectCommand_proto_rawDescGZIP() []byte {
	file_pkg_proto_DirectCommand_proto_rawDescOnce.Do(func() {
		file_pkg_proto_DirectCommand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_DirectCommand_proto_rawDesc), len(file_pkg_proto_DirectCommand_proto_rawDesc)))
	})
	return file_pkg_proto_DirectCommand_proto_rawDescData
}

var file_pkg_proto_DirectCommand_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_DirectCommand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_DirectCommand_proto_goTypes = []any{
	(AT_DIRECT_COMMAND_STATUS)(0),       // 0: drone.AT_DIRECT_COMMAND_STATUS
	(*DirectCommand)(nil),               // 1: drone.DirectCommand
	(*SearchDirectCommandResponse)(nil), // 2: drone.SearchDirectCommandResponse
	(*SearchOptions)(nil),               // 3: search_options.SearchOptions
	(*PatchOptions)(nil),                // 4: patch_options.PatchOptions
	(*PatchResponse)(nil),               // 5: patch_options.PatchResponse
}
var file_pkg_proto_DirectCommand_proto_depIdxs = []int32{
	0, // 0: drone.DirectCommand.DirectCommandStatus:type_name -> drone.AT_DIRECT_COMMAND_STATUS
	1, // 1: drone.SearchDirectCommandResponse.DirectCommands:type_name -> drone.DirectCommand
	1, // 2: drone.DirectCommandService.create:input_type -> drone.DirectCommand
	3, // 3: drone.DirectCommandService.search:input_type -> search_options.SearchOptions
	4, // 4: drone.DirectCommandService.patch:input_type -> patch_options.PatchOptions
	1, // 5: drone.DirectCommandService.update:input_type -> drone.DirectCommand
	1, // 6: drone.DirectCommandService.create:output_type -> drone.DirectCommand
	2, // 7: drone.DirectCommandService.search:output_type -> drone.SearchDirectCommandResponse
	5, // 8: drone.DirectCommandService.patch:output_type -> patch_options.PatchResponse
	1, // 9: drone.DirectCommandService.update:output_type -> drone.DirectCommand
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_DirectCommand_proto_init() }
func file_pkg_proto_DirectCommand_proto_init() {
	if File_pkg_proto_DirectCommand_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	file_pkg_proto_SpatialAttribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_DirectCommand_proto_rawDesc), len(file_pkg_proto_DirectCommand_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_DirectCommand_proto_goTypes,
		DependencyIndexes: file_pkg_proto_DirectCommand_proto_depIdxs,
		EnumInfos:         file_pkg_proto_DirectCommand_proto_enumTypes,
		MessageInfos:      file_pkg_proto_DirectCommand_proto_msgTypes,
	}.Build()
	File_pkg_proto_DirectCommand_proto = out.File
	file_pkg_proto_DirectCommand_proto_goTypes = nil
	file_pkg_proto_DirectCommand_proto_depIdxs = nil
}
