// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/Drone.proto

package pb

import (
	context "context"
	empty "google.golang.org/protobuf/types/known/emptypb"
	wrappers "google.golang.org/protobuf/types/known/wrapperspb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DroneService_Create_FullMethodName = "/drone.DroneService/create"
	DroneService_Search_FullMethodName = "/drone.DroneService/search"
	DroneService_Patch_FullMethodName  = "/drone.DroneService/patch"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	Create(ctx context.Context, in *Drone, opts ...grpc.CallOption) (*Drone, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchDroneResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) Create(ctx context.Context, in *Drone, opts ...grpc.CallOption) (*Drone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drone)
	err := c.cc.Invoke(ctx, DroneService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDroneResponse)
	err := c.cc.Invoke(ctx, DroneService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, DroneService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility.
type DroneServiceServer interface {
	Create(context.Context, *Drone) (*Drone, error)
	Search(context.Context, *SearchOptions) (*SearchDroneResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneServiceServer struct{}

func (UnimplementedDroneServiceServer) Create(context.Context, *Drone) (*Drone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDroneServiceServer) Search(context.Context, *SearchOptions) (*SearchDroneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDroneServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}
func (UnimplementedDroneServiceServer) testEmbeddedByValue()                      {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	// If the following call pancis, it indicates UnimplementedDroneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Drone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).Create(ctx, req.(*Drone))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _DroneService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _DroneService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _DroneService_Patch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/Drone.proto",
}

const (
	TrackHistoryService_Create_FullMethodName = "/drone.TrackHistoryService/create"
	TrackHistoryService_Search_FullMethodName = "/drone.TrackHistoryService/search"
	TrackHistoryService_Patch_FullMethodName  = "/drone.TrackHistoryService/patch"
)

// TrackHistoryServiceClient is the client API for TrackHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackHistoryServiceClient interface {
	Create(ctx context.Context, in *TrackHistory, opts ...grpc.CallOption) (*TrackHistory, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchTrackHistoryResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
}

type trackHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackHistoryServiceClient(cc grpc.ClientConnInterface) TrackHistoryServiceClient {
	return &trackHistoryServiceClient{cc}
}

func (c *trackHistoryServiceClient) Create(ctx context.Context, in *TrackHistory, opts ...grpc.CallOption) (*TrackHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackHistory)
	err := c.cc.Invoke(ctx, TrackHistoryService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHistoryServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchTrackHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTrackHistoryResponse)
	err := c.cc.Invoke(ctx, TrackHistoryService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackHistoryServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, TrackHistoryService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackHistoryServiceServer is the server API for TrackHistoryService service.
// All implementations must embed UnimplementedTrackHistoryServiceServer
// for forward compatibility.
type TrackHistoryServiceServer interface {
	Create(context.Context, *TrackHistory) (*TrackHistory, error)
	Search(context.Context, *SearchOptions) (*SearchTrackHistoryResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	mustEmbedUnimplementedTrackHistoryServiceServer()
}

// UnimplementedTrackHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackHistoryServiceServer struct{}

func (UnimplementedTrackHistoryServiceServer) Create(context.Context, *TrackHistory) (*TrackHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTrackHistoryServiceServer) Search(context.Context, *SearchOptions) (*SearchTrackHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedTrackHistoryServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedTrackHistoryServiceServer) mustEmbedUnimplementedTrackHistoryServiceServer() {}
func (UnimplementedTrackHistoryServiceServer) testEmbeddedByValue()                             {}

// UnsafeTrackHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackHistoryServiceServer will
// result in compilation errors.
type UnsafeTrackHistoryServiceServer interface {
	mustEmbedUnimplementedTrackHistoryServiceServer()
}

func RegisterTrackHistoryServiceServer(s grpc.ServiceRegistrar, srv TrackHistoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrackHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackHistoryService_ServiceDesc, srv)
}

func _TrackHistoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackHistory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHistoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHistoryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHistoryServiceServer).Create(ctx, req.(*TrackHistory))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHistoryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHistoryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHistoryService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHistoryServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackHistoryService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackHistoryServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackHistoryService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackHistoryServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackHistoryService_ServiceDesc is the grpc.ServiceDesc for TrackHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.TrackHistoryService",
	HandlerType: (*TrackHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _TrackHistoryService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _TrackHistoryService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _TrackHistoryService_Patch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/Drone.proto",
}

const (
	ObjectTrackService_Create_FullMethodName   = "/drone.ObjectTrackService/create"
	ObjectTrackService_Search_FullMethodName   = "/drone.ObjectTrackService/search"
	ObjectTrackService_Patch_FullMethodName    = "/drone.ObjectTrackService/patch"
	ObjectTrackService_FindByID_FullMethodName = "/drone.ObjectTrackService/findByID"
	ObjectTrackService_FindAll_FullMethodName  = "/drone.ObjectTrackService/findAll"
)

// ObjectTrackServiceClient is the client API for ObjectTrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectTrackServiceClient interface {
	Create(ctx context.Context, in *ObjectTrack, opts ...grpc.CallOption) (*ObjectTrack, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchObjectTrackResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
	FindByID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*ObjectTrack, error)
	FindAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SearchObjectTrackResponse, error)
}

type objectTrackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectTrackServiceClient(cc grpc.ClientConnInterface) ObjectTrackServiceClient {
	return &objectTrackServiceClient{cc}
}

func (c *objectTrackServiceClient) Create(ctx context.Context, in *ObjectTrack, opts ...grpc.CallOption) (*ObjectTrack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectTrack)
	err := c.cc.Invoke(ctx, ObjectTrackService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTrackServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchObjectTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchObjectTrackResponse)
	err := c.cc.Invoke(ctx, ObjectTrackService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTrackServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, ObjectTrackService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTrackServiceClient) FindByID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*ObjectTrack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectTrack)
	err := c.cc.Invoke(ctx, ObjectTrackService_FindByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectTrackServiceClient) FindAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SearchObjectTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchObjectTrackResponse)
	err := c.cc.Invoke(ctx, ObjectTrackService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectTrackServiceServer is the server API for ObjectTrackService service.
// All implementations must embed UnimplementedObjectTrackServiceServer
// for forward compatibility.
type ObjectTrackServiceServer interface {
	Create(context.Context, *ObjectTrack) (*ObjectTrack, error)
	Search(context.Context, *SearchOptions) (*SearchObjectTrackResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	FindByID(context.Context, *wrappers.Int32Value) (*ObjectTrack, error)
	FindAll(context.Context, *empty.Empty) (*SearchObjectTrackResponse, error)
	mustEmbedUnimplementedObjectTrackServiceServer()
}

// UnimplementedObjectTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectTrackServiceServer struct{}

func (UnimplementedObjectTrackServiceServer) Create(context.Context, *ObjectTrack) (*ObjectTrack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedObjectTrackServiceServer) Search(context.Context, *SearchOptions) (*SearchObjectTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedObjectTrackServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedObjectTrackServiceServer) FindByID(context.Context, *wrappers.Int32Value) (*ObjectTrack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}
func (UnimplementedObjectTrackServiceServer) FindAll(context.Context, *empty.Empty) (*SearchObjectTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedObjectTrackServiceServer) mustEmbedUnimplementedObjectTrackServiceServer() {}
func (UnimplementedObjectTrackServiceServer) testEmbeddedByValue()                            {}

// UnsafeObjectTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectTrackServiceServer will
// result in compilation errors.
type UnsafeObjectTrackServiceServer interface {
	mustEmbedUnimplementedObjectTrackServiceServer()
}

func RegisterObjectTrackServiceServer(s grpc.ServiceRegistrar, srv ObjectTrackServiceServer) {
	// If the following call pancis, it indicates UnimplementedObjectTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectTrackService_ServiceDesc, srv)
}

func _ObjectTrackService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectTrack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTrackServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectTrackService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTrackServiceServer).Create(ctx, req.(*ObjectTrack))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTrackService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTrackServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectTrackService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTrackServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTrackService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTrackServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectTrackService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTrackServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTrackService_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTrackServiceServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectTrackService_FindByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTrackServiceServer).FindByID(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectTrackService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectTrackServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectTrackService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectTrackServiceServer).FindAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectTrackService_ServiceDesc is the grpc.ServiceDesc for ObjectTrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectTrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.ObjectTrackService",
	HandlerType: (*ObjectTrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _ObjectTrackService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _ObjectTrackService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _ObjectTrackService_Patch_Handler,
		},
		{
			MethodName: "findByID",
			Handler:    _ObjectTrackService_FindByID_Handler,
		},
		{
			MethodName: "findAll",
			Handler:    _ObjectTrackService_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/Drone.proto",
}
