// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Drone.proto

package pb

import (
	empty "google.golang.org/protobuf/types/known/emptypb"
	wrappers "google.golang.org/protobuf/types/known/wrapperspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AT_UAV_OP_MODE int32

const (
	AT_UAV_OP_MODE_AUOM_MODE_UNKNOWN AT_UAV_OP_MODE = 0
	AT_UAV_OP_MODE_AUOM_MODE_ONE     AT_UAV_OP_MODE = 1
)

// Enum value maps for AT_UAV_OP_MODE.
var (
	AT_UAV_OP_MODE_name = map[int32]string{
		0: "AUOM_MODE_UNKNOWN",
		1: "AUOM_MODE_ONE",
	}
	AT_UAV_OP_MODE_value = map[string]int32{
		"AUOM_MODE_UNKNOWN": 0,
		"AUOM_MODE_ONE":     1,
	}
)

func (x AT_UAV_OP_MODE) Enum() *AT_UAV_OP_MODE {
	p := new(AT_UAV_OP_MODE)
	*p = x
	return p
}

func (x AT_UAV_OP_MODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_UAV_OP_MODE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Drone_proto_enumTypes[0].Descriptor()
}

func (AT_UAV_OP_MODE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Drone_proto_enumTypes[0]
}

func (x AT_UAV_OP_MODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_UAV_OP_MODE.Descriptor instead.
func (AT_UAV_OP_MODE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{0}
}

type AT_DRONE_STATUS int32

const (
	AT_DRONE_STATUS_ADS_UNKNOWN AT_DRONE_STATUS = 0
	AT_DRONE_STATUS_ADS_FLYING  AT_DRONE_STATUS = 1
	AT_DRONE_STATUS_ADS_LANDED  AT_DRONE_STATUS = 2
)

// Enum value maps for AT_DRONE_STATUS.
var (
	AT_DRONE_STATUS_name = map[int32]string{
		0: "ADS_UNKNOWN",
		1: "ADS_FLYING",
		2: "ADS_LANDED",
	}
	AT_DRONE_STATUS_value = map[string]int32{
		"ADS_UNKNOWN": 0,
		"ADS_FLYING":  1,
		"ADS_LANDED":  2,
	}
)

func (x AT_DRONE_STATUS) Enum() *AT_DRONE_STATUS {
	p := new(AT_DRONE_STATUS)
	*p = x
	return p
}

func (x AT_DRONE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_DRONE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Drone_proto_enumTypes[1].Descriptor()
}

func (AT_DRONE_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_Drone_proto_enumTypes[1]
}

func (x AT_DRONE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_DRONE_STATUS.Descriptor instead.
func (AT_DRONE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{1}
}

type AT_VALIDATE_STATUS int32

const (
	AT_VALIDATE_STATUS_ADS_CREATED  AT_VALIDATE_STATUS = 0
	AT_VALIDATE_STATUS_ADS_SENT     AT_VALIDATE_STATUS = 1
	AT_VALIDATE_STATUS_ADS_APPROVED AT_VALIDATE_STATUS = 2
)

// Enum value maps for AT_VALIDATE_STATUS.
var (
	AT_VALIDATE_STATUS_name = map[int32]string{
		0: "ADS_CREATED",
		1: "ADS_SENT",
		2: "ADS_APPROVED",
	}
	AT_VALIDATE_STATUS_value = map[string]int32{
		"ADS_CREATED":  0,
		"ADS_SENT":     1,
		"ADS_APPROVED": 2,
	}
)

func (x AT_VALIDATE_STATUS) Enum() *AT_VALIDATE_STATUS {
	p := new(AT_VALIDATE_STATUS)
	*p = x
	return p
}

func (x AT_VALIDATE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_VALIDATE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Drone_proto_enumTypes[2].Descriptor()
}

func (AT_VALIDATE_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_Drone_proto_enumTypes[2]
}

func (x AT_VALIDATE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_VALIDATE_STATUS.Descriptor instead.
func (AT_VALIDATE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{2}
}

type Drone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	RTSPLink      string                 `protobuf:"bytes,2,opt,name=RTSPLink,proto3" json:"rtsp_link,omitempty" bson:"rtsp_link"`
	GcsID         string                 `protobuf:"bytes,3,opt,name=GcsID,proto3" json:"gcs_id,omitempty" bson:"gcs_id"`
	DroneStatus   AT_DRONE_STATUS        `protobuf:"varint,4,opt,name=DroneStatus,proto3,enum=drone.AT_DRONE_STATUS" json:"drone_status,omitempty" bson:"drone_status"`
	DeportID      string                 `protobuf:"bytes,5,opt,name=DeportID,proto3" json:"deport_id,omitempty" bson:"deport_id"`
	Mass          float64                `protobuf:"fixed64,6,opt,name=Mass,proto3" json:"mass,omitempty" bson:"mass"`
	MaxPayload    float64                `protobuf:"fixed64,7,opt,name=MaxPayload,proto3" json:"max_payload,omitempty" bson:"max_payload"`
	MaxBattery    float64                `protobuf:"fixed64,8,opt,name=MaxBattery,proto3" json:"max_battery,omitempty" bson:"max_battery"`
	MaxPower      float64                `protobuf:"fixed64,9,opt,name=MaxPower,proto3" json:"max_power,omitempty" bson:"max_power"`
	MaxSpeed      float64                `protobuf:"fixed64,10,opt,name=MaxSpeed,proto3" json:"max_speed,omitempty" bson:"max_speed"`
	Size          []float64              `protobuf:"fixed64,11,rep,packed,name=Size,proto3" json:"size,omitempty" bson:"size"`
	FixedLockerIDs []string               `protobuf:"bytes,12,rep,name=FixedLockerIDs,proto3" json:"fixed_locker_ids,omitempty" bson:"fixed_locker_ids"`
	ValidateStatus AT_VALIDATE_STATUS     `protobuf:"varint,13,opt,name=ValidateStatus,proto3,enum=drone.AT_VALIDATE_STATUS" json:"validate_status,omitempty" bson:"validate_status"`
	Image          string                 `protobuf:"bytes,14,opt,name=Image,proto3" json:"image,omitempty" bson:"image"`
	CreatedAt     uint64                 `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64                 `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string                 `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string                 `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drone) Reset() {
	*x = Drone{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{0}
}

func (x *Drone) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Drone) GetRTSPLink() string {
	if x != nil {
		return x.RTSPLink
	}
	return ""
}

func (x *Drone) GetGcsID() string {
	if x != nil {
		return x.GcsID
	}
	return ""
}

func (x *Drone) GetDroneStatus() AT_DRONE_STATUS {
	if x != nil {
		return x.DroneStatus
	}
	return AT_DRONE_STATUS_ADS_UNKNOWN
}

func (x *Drone) GetDeportID() string {
	if x != nil {
		return x.DeportID
	}
	return ""
}

func (x *Drone) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *Drone) GetMaxPayload() float64 {
	if x != nil {
		return x.MaxPayload
	}
	return 0
}

func (x *Drone) GetMaxBattery() float64 {
	if x != nil {
		return x.MaxBattery
	}
	return 0
}

func (x *Drone) GetMaxPower() float64 {
	if x != nil {
		return x.MaxPower
	}
	return 0
}

func (x *Drone) GetMaxSpeed() float64 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *Drone) GetSize() []float64 {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Drone) GetFixedLockerIDs() []string {
	if x != nil {
		return x.FixedLockerIDs
	}
	return nil
}

func (x *Drone) GetValidateStatus() AT_VALIDATE_STATUS {
	if x != nil {
		return x.ValidateStatus
	}
	return AT_VALIDATE_STATUS_ADS_CREATED
}

func (x *Drone) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Drone) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Drone) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Drone) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Drone) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchDroneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drones        []*Drone               `protobuf:"bytes,1,rep,name=Drones,proto3" json:"Drones,omitempty"`          //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDroneResponse) Reset() {
	*x = SearchDroneResponse{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDroneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDroneResponse) ProtoMessage() {}

func (x *SearchDroneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDroneResponse.ProtoReflect.Descriptor instead.
func (*SearchDroneResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDroneResponse) GetDrones() []*Drone {
	if x != nil {
		return x.Drones
	}
	return nil
}

func (x *SearchDroneResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TrackHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	DroneID       string                 `protobuf:"bytes,2,opt,name=DroneID,proto3" json:"drone_id,omitempty" bson:"drone_id"`
	OrderID       string                 `protobuf:"bytes,3,opt,name=OrderID,proto3" json:"order_id,omitempty" bson:"order_id"`
	DatasourceID  string                 `protobuf:"bytes,4,opt,name=DatasourceID,proto3" json:"datasource,omitempty" bson:"datasource"`
	TrackID       int32                  `protobuf:"varint,5,opt,name=TrackID,proto3" json:"track_id,omitempty" bson:"track_id"`
	LocationByte  []byte                 `protobuf:"bytes,6,opt,name=LocationByte,proto3" json:"location_byte,omitempty" bson:"location_byte"`
	CreatedAt     uint64                 `protobuf:"varint,7,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackHistory) Reset() {
	*x = TrackHistory{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackHistory) ProtoMessage() {}

func (x *TrackHistory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackHistory.ProtoReflect.Descriptor instead.
func (*TrackHistory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{2}
}

func (x *TrackHistory) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TrackHistory) GetDroneID() string {
	if x != nil {
		return x.DroneID
	}
	return ""
}

func (x *TrackHistory) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *TrackHistory) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

func (x *TrackHistory) GetTrackID() int32 {
	if x != nil {
		return x.TrackID
	}
	return 0
}

func (x *TrackHistory) GetLocationByte() []byte {
	if x != nil {
		return x.LocationByte
	}
	return nil
}

func (x *TrackHistory) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string  ID          = 1;//`json:"id,omitempty" bson:"_id"`
	GeodeticPosition *GeodeticPosition `protobuf:"bytes,1,opt,name=GeodeticPosition,proto3" json:"geodetic_position,omitempty" bson:"geodetic_position"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetGeodeticPosition() *GeodeticPosition {
	if x != nil {
		return x.GeodeticPosition
	}
	return nil
}

type SearchTrackHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHistorys []*TrackHistory        `protobuf:"bytes,1,rep,name=TrackHistorys,proto3" json:"TrackHistorys,omitempty"` //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`      //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTrackHistoryResponse) Reset() {
	*x = SearchTrackHistoryResponse{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTrackHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrackHistoryResponse) ProtoMessage() {}

func (x *SearchTrackHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrackHistoryResponse.ProtoReflect.Descriptor instead.
func (*SearchTrackHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTrackHistoryResponse) GetTrackHistorys() []*TrackHistory {
	if x != nil {
		return x.TrackHistorys
	}
	return nil
}

func (x *SearchTrackHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ObjectTrack struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ID                      string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	ObjectTrackID           int32                  `protobuf:"varint,2,opt,name=ObjectTrackID,proto3" json:"object_track_id,omitempty" bson:"object_track_id"`
	ObjectID                string                 `protobuf:"bytes,3,opt,name=ObjectID,proto3" json:"object_id,omitempty" bson:"object_id"`
	PolarVelocity           *PolarVelocity         `protobuf:"bytes,4,opt,name=PolarVelocity,proto3" json:"polar_velocity,omitempty" bson:"polar_velocity"`
	Heading                 float64                `protobuf:"fixed64,5,opt,name=Heading,proto3" json:"heading,omitempty" bson:"heading"`
	Battery                 float64                `protobuf:"fixed64,6,opt,name=Battery,proto3" json:"battery,omitempty" bson:"battery"`
	DatasourcesLatestUpdate map[string]uint64      `protobuf:"bytes,7,rep,name=DatasourcesLatestUpdate,proto3" json:"datasource_latest_update,omitempty" bson:"datasource_latest_update" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` 
	Position                *GeodeticPosition      `protobuf:"bytes,8,opt,name=Position,proto3" json:"position,omitempty" bson:"position"`
	DroneStatus             AT_DRONE_STATUS        `protobuf:"varint,9,opt,name=DroneStatus,proto3,enum=drone.AT_DRONE_STATUS" json:"drone_status,omitempty" bson:"drone_status"`
	SourceTracks            []*TrackMessage        `protobuf:"bytes,10,rep,name=SourceTracks,proto3" json:"source_tracks,omitempty" bson:"source_tracks"`
	AircraftType            AircraftType           `protobuf:"varint,11,opt,name=AircraftType,proto3,enum=com.vht.bms.messages.AircraftType" json:"aircraft_type,omitempty" bson:"aircraft_type"`
	RemainTime              uint64                 `protobuf:"varint,51,opt,name=RemainTime,proto3" json:"remain_time,omitempty" bson:"remain_time"  audit:"updatedAt"`
	CreatedAt               uint64                 `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt               uint64                 `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy               string                 `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy               string                 `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ObjectTrack) Reset() {
	*x = ObjectTrack{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTrack) ProtoMessage() {}

func (x *ObjectTrack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTrack.ProtoReflect.Descriptor instead.
func (*ObjectTrack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectTrack) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ObjectTrack) GetObjectTrackID() int32 {
	if x != nil {
		return x.ObjectTrackID
	}
	return 0
}

func (x *ObjectTrack) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *ObjectTrack) GetPolarVelocity() *PolarVelocity {
	if x != nil {
		return x.PolarVelocity
	}
	return nil
}

func (x *ObjectTrack) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *ObjectTrack) GetBattery() float64 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *ObjectTrack) GetDatasourcesLatestUpdate() map[string]uint64 {
	if x != nil {
		return x.DatasourcesLatestUpdate
	}
	return nil
}

func (x *ObjectTrack) GetPosition() *GeodeticPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ObjectTrack) GetDroneStatus() AT_DRONE_STATUS {
	if x != nil {
		return x.DroneStatus
	}
	return AT_DRONE_STATUS_ADS_UNKNOWN
}

func (x *ObjectTrack) GetSourceTracks() []*TrackMessage {
	if x != nil {
		return x.SourceTracks
	}
	return nil
}

func (x *ObjectTrack) GetAircraftType() AircraftType {
	if x != nil {
		return x.AircraftType
	}
	return AircraftType_AIRCRAFT_TYPE_UNKNOWN
}

func (x *ObjectTrack) GetRemainTime() uint64 {
	if x != nil {
		return x.RemainTime
	}
	return 0
}

func (x *ObjectTrack) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ObjectTrack) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ObjectTrack) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ObjectTrack) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchObjectTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectTracks  []*ObjectTrack         `protobuf:"bytes,1,rep,name=ObjectTracks,proto3" json:"ObjectTracks,omitempty"` //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`    //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchObjectTrackResponse) Reset() {
	*x = SearchObjectTrackResponse{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchObjectTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchObjectTrackResponse) ProtoMessage() {}

func (x *SearchObjectTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchObjectTrackResponse.ProtoReflect.Descriptor instead.
func (*SearchObjectTrackResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{6}
}

func (x *SearchObjectTrackResponse) GetObjectTracks() []*ObjectTrack {
	if x != nil {
		return x.ObjectTracks
	}
	return nil
}

func (x *SearchObjectTrackResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ObjectTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectTrackRequest) Reset() {
	*x = ObjectTrackRequest{}
	mi := &file_pkg_proto_Drone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTrackRequest) ProtoMessage() {}

func (x *ObjectTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Drone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTrackRequest.ProtoReflect.Descriptor instead.
func (*ObjectTrackRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Drone_proto_rawDescGZIP(), []int{7}
}

var File_pkg_proto_Drone_proto protoreflect.FileDescriptor

const file_pkg_proto_Drone_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/Drone.proto\x12\x05drone\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\x1a pkg/proto/SpatialAttribute.proto\x1a\x1apkg/ipc/TrackMessage.proto\x1a\x1bpkg/ipc/TrackInfoEnum.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x04\n" +
	"\x05Drone\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bRTSPLink\x18\x02 \x01(\tR\bRTSPLink\x12\x14\n" +
	"\x05GcsID\x18\x03 \x01(\tR\x05GcsID\x128\n" +
	"\vDroneStatus\x18\x04 \x01(\x0e2\x16.drone.AT_DRONE_STATUSR\vDroneStatus\x12\x1a\n" +
	"\bDeportID\x18\x05 \x01(\tR\bDeportID\x12\x12\n" +
	"\x04Mass\x18\x06 \x01(\x01R\x04Mass\x12\x1e\n" +
	"\n" +
	"MaxPayload\x18\a \x01(\x01R\n" +
	"MaxPayload\x12\x1e\n" +
	"\n" +
	"MaxBattery\x18\b \x01(\x01R\n" +
	"MaxBattery\x12\x1a\n" +
	"\bMaxPower\x18\t \x01(\x01R\bMaxPower\x12\x1a\n" +
	"\bMaxSpeed\x18\n" +
	" \x01(\x01R\bMaxSpeed\x12\x12\n" +
	"\x04Size\x18\v \x03(\x01R\x04Size\x12&\n" +
	"\x0eFixedLockerIDs\x18\f \x03(\tR\x0eFixedLockerIDs\x12A\n" +
	"\x0eValidateStatus\x18\r \x01(\x0e2\x19.drone.AT_VALIDATE_STATUSR\x0eValidateStatus\x12\x14\n" +
	"\x05Image\x18\x0e \x01(\tR\x05Image\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"[\n" +
	"\x13SearchDroneResponse\x12$\n" +
	"\x06Drones\x18\x01 \x03(\v2\f.drone.DroneR\x06Drones\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount\"\xd2\x01\n" +
	"\fTrackHistory\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aDroneID\x18\x02 \x01(\tR\aDroneID\x12\x18\n" +
	"\aOrderID\x18\x03 \x01(\tR\aOrderID\x12\"\n" +
	"\fDatasourceID\x18\x04 \x01(\tR\fDatasourceID\x12\x18\n" +
	"\aTrackID\x18\x05 \x01(\x05R\aTrackID\x12\"\n" +
	"\fLocationByte\x18\x06 \x01(\fR\fLocationByte\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\x04R\tCreatedAt\"[\n" +
	"\bLocation\x12O\n" +
	"\x10GeodeticPosition\x18\x01 \x01(\v2#.spatial_attribute.GeodeticPositionR\x10GeodeticPosition\"w\n" +
	"\x1aSearchTrackHistoryResponse\x129\n" +
	"\rTrackHistorys\x18\x01 \x03(\v2\x13.drone.TrackHistoryR\rTrackHistorys\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount\"\xb5\x06\n" +
	"\vObjectTrack\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12$\n" +
	"\rObjectTrackID\x18\x02 \x01(\x05R\rObjectTrackID\x12\x1a\n" +
	"\bObjectID\x18\x03 \x01(\tR\bObjectID\x12F\n" +
	"\rPolarVelocity\x18\x04 \x01(\v2 .spatial_attribute.PolarVelocityR\rPolarVelocity\x12\x18\n" +
	"\aHeading\x18\x05 \x01(\x01R\aHeading\x12\x18\n" +
	"\aBattery\x18\x06 \x01(\x01R\aBattery\x12i\n" +
	"\x17DatasourcesLatestUpdate\x18\a \x03(\v2/.drone.ObjectTrack.DatasourcesLatestUpdateEntryR\x17DatasourcesLatestUpdate\x12?\n" +
	"\bPosition\x18\b \x01(\v2#.spatial_attribute.GeodeticPositionR\bPosition\x128\n" +
	"\vDroneStatus\x18\t \x01(\x0e2\x16.drone.AT_DRONE_STATUSR\vDroneStatus\x12F\n" +
	"\fSourceTracks\x18\n" +
	" \x03(\v2\".com.vht.bms.messages.TrackMessageR\fSourceTracks\x12F\n" +
	"\fAircraftType\x18\v \x01(\x0e2\".com.vht.bms.messages.AircraftTypeR\fAircraftType\x12\x1e\n" +
	"\n" +
	"RemainTime\x183 \x01(\x04R\n" +
	"RemainTime\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\x1aJ\n" +
	"\x1cDatasourcesLatestUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"s\n" +
	"\x19SearchObjectTrackResponse\x126\n" +
	"\fObjectTracks\x18\x01 \x03(\v2\x12.drone.ObjectTrackR\fObjectTracks\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount\"\x14\n" +
	"\x12ObjectTrackRequest*:\n" +
	"\x0eAT_UAV_OP_MODE\x12\x15\n" +
	"\x11AUOM_MODE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rAUOM_MODE_ONE\x10\x01*B\n" +
	"\x0fAT_DRONE_STATUS\x12\x0f\n" +
	"\vADS_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"ADS_FLYING\x10\x01\x12\x0e\n" +
	"\n" +
	"ADS_LANDED\x10\x02*E\n" +
	"\x12AT_VALIDATE_STATUS\x12\x0f\n" +
	"\vADS_CREATED\x10\x00\x12\f\n" +
	"\bADS_SENT\x10\x01\x12\x10\n" +
	"\fADS_APPROVED\x10\x022\xbd\x01\n" +
	"\fDroneService\x12$\n" +
	"\x06create\x12\f.drone.Drone\x1a\f.drone.Drone\x12C\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x1a.drone.SearchDroneResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse2\xd9\x01\n" +
	"\x13TrackHistoryService\x122\n" +
	"\x06create\x12\x13.drone.TrackHistory\x1a\x13.drone.TrackHistory\x12J\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a!.drone.SearchTrackHistoryResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse2\xd7\x02\n" +
	"\x12ObjectTrackService\x120\n" +
	"\x06create\x12\x12.drone.ObjectTrack\x1a\x12.drone.ObjectTrack\x12I\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a .drone.SearchObjectTrackResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x12;\n" +
	"\bfindByID\x12\x1b.google.protobuf.Int32Value\x1a\x12.drone.ObjectTrack\x12C\n" +
	"\afindAll\x12\x16.google.protobuf.Empty\x1a .drone.SearchObjectTrackResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Drone_proto_rawDescOnce sync.Once
	file_pkg_proto_Drone_proto_rawDescData []byte
)

func file_pkg_proto_Drone_proto_rawDescGZIP() []byte {
	file_pkg_proto_Drone_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Drone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Drone_proto_rawDesc), len(file_pkg_proto_Drone_proto_rawDesc)))
	})
	return file_pkg_proto_Drone_proto_rawDescData
}

var file_pkg_proto_Drone_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_Drone_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_Drone_proto_goTypes = []any{
	(AT_UAV_OP_MODE)(0),                // 0: drone.AT_UAV_OP_MODE
	(AT_DRONE_STATUS)(0),               // 1: drone.AT_DRONE_STATUS
	(AT_VALIDATE_STATUS)(0),            // 2: drone.AT_VALIDATE_STATUS
	(*Drone)(nil),                      // 3: drone.Drone
	(*SearchDroneResponse)(nil),        // 4: drone.SearchDroneResponse
	(*TrackHistory)(nil),               // 5: drone.TrackHistory
	(*Location)(nil),                   // 6: drone.Location
	(*SearchTrackHistoryResponse)(nil), // 7: drone.SearchTrackHistoryResponse
	(*ObjectTrack)(nil),                // 8: drone.ObjectTrack
	(*SearchObjectTrackResponse)(nil),  // 9: drone.SearchObjectTrackResponse
	(*ObjectTrackRequest)(nil),         // 10: drone.ObjectTrackRequest
	nil,                                // 11: drone.ObjectTrack.DatasourcesLatestUpdateEntry
	(*GeodeticPosition)(nil),           // 12: spatial_attribute.GeodeticPosition
	(*PolarVelocity)(nil),              // 13: spatial_attribute.PolarVelocity
	(*TrackMessage)(nil),               // 14: com.vht.bms.messages.TrackMessage
	(AircraftType)(0),                  // 15: com.vht.bms.messages.AircraftType
	(*SearchOptions)(nil),              // 16: search_options.SearchOptions
	(*PatchOptions)(nil),               // 17: patch_options.PatchOptions
	(*wrappers.Int32Value)(nil),        // 18: google.protobuf.Int32Value
	(*empty.Empty)(nil),                // 19: google.protobuf.Empty
	(*PatchResponse)(nil),              // 20: patch_options.PatchResponse
}
var file_pkg_proto_Drone_proto_depIdxs = []int32{
	1,  // 0: drone.Drone.DroneStatus:type_name -> drone.AT_DRONE_STATUS
	2,  // 1: drone.Drone.ValidateStatus:type_name -> drone.AT_VALIDATE_STATUS
	3,  // 2: drone.SearchDroneResponse.Drones:type_name -> drone.Drone
	12, // 3: drone.Location.GeodeticPosition:type_name -> spatial_attribute.GeodeticPosition
	5,  // 4: drone.SearchTrackHistoryResponse.TrackHistorys:type_name -> drone.TrackHistory
	13, // 5: drone.ObjectTrack.PolarVelocity:type_name -> spatial_attribute.PolarVelocity
	11, // 6: drone.ObjectTrack.DatasourcesLatestUpdate:type_name -> drone.ObjectTrack.DatasourcesLatestUpdateEntry
	12, // 7: drone.ObjectTrack.Position:type_name -> spatial_attribute.GeodeticPosition
	1,  // 8: drone.ObjectTrack.DroneStatus:type_name -> drone.AT_DRONE_STATUS
	14, // 9: drone.ObjectTrack.SourceTracks:type_name -> com.vht.bms.messages.TrackMessage
	15, // 10: drone.ObjectTrack.AircraftType:type_name -> com.vht.bms.messages.AircraftType
	8,  // 11: drone.SearchObjectTrackResponse.ObjectTracks:type_name -> drone.ObjectTrack
	3,  // 12: drone.DroneService.create:input_type -> drone.Drone
	16, // 13: drone.DroneService.search:input_type -> search_options.SearchOptions
	17, // 14: drone.DroneService.patch:input_type -> patch_options.PatchOptions
	5,  // 15: drone.TrackHistoryService.create:input_type -> drone.TrackHistory
	16, // 16: drone.TrackHistoryService.search:input_type -> search_options.SearchOptions
	17, // 17: drone.TrackHistoryService.patch:input_type -> patch_options.PatchOptions
	8,  // 18: drone.ObjectTrackService.create:input_type -> drone.ObjectTrack
	16, // 19: drone.ObjectTrackService.search:input_type -> search_options.SearchOptions
	17, // 20: drone.ObjectTrackService.patch:input_type -> patch_options.PatchOptions
	18, // 21: drone.ObjectTrackService.findByID:input_type -> google.protobuf.Int32Value
	19, // 22: drone.ObjectTrackService.findAll:input_type -> google.protobuf.Empty
	3,  // 23: drone.DroneService.create:output_type -> drone.Drone
	4,  // 24: drone.DroneService.search:output_type -> drone.SearchDroneResponse
	20, // 25: drone.DroneService.patch:output_type -> patch_options.PatchResponse
	5,  // 26: drone.TrackHistoryService.create:output_type -> drone.TrackHistory
	7,  // 27: drone.TrackHistoryService.search:output_type -> drone.SearchTrackHistoryResponse
	20, // 28: drone.TrackHistoryService.patch:output_type -> patch_options.PatchResponse
	8,  // 29: drone.ObjectTrackService.create:output_type -> drone.ObjectTrack
	9,  // 30: drone.ObjectTrackService.search:output_type -> drone.SearchObjectTrackResponse
	20, // 31: drone.ObjectTrackService.patch:output_type -> patch_options.PatchResponse
	8,  // 32: drone.ObjectTrackService.findByID:output_type -> drone.ObjectTrack
	9,  // 33: drone.ObjectTrackService.findAll:output_type -> drone.SearchObjectTrackResponse
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_Drone_proto_init() }
func file_pkg_proto_Drone_proto_init() {
	if File_pkg_proto_Drone_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	file_pkg_proto_SpatialAttribute_proto_init()
	file_pkg_ipc_TrackMessage_proto_init()
	file_pkg_ipc_TrackInfoEnum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Drone_proto_rawDesc), len(file_pkg_proto_Drone_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_proto_Drone_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Drone_proto_depIdxs,
		EnumInfos:         file_pkg_proto_Drone_proto_enumTypes,
		MessageInfos:      file_pkg_proto_Drone_proto_msgTypes,
	}.Build()
	File_pkg_proto_Drone_proto = out.File
	file_pkg_proto_Drone_proto_goTypes = nil
	file_pkg_proto_Drone_proto_depIdxs = nil
}
