// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/EventListener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRoutingKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RKService     string                 `protobuf:"bytes,1,opt,name=RKService,proto3" json:"RKService,omitempty"`   //`json:"rk_service" bson:"rk_service"`
	RKResource    string                 `protobuf:"bytes,2,opt,name=RKResource,proto3" json:"RKResource,omitempty"` //`json:"rk_resource" bson:"rk_resource"`
	RKAction      string                 `protobuf:"bytes,3,opt,name=RKAction,proto3" json:"RKAction,omitempty"`     //`json:"rk_action" bson:"rk_action"`
	RKEventAPI    string                 `protobuf:"bytes,4,opt,name=RKEventAPI,proto3" json:"RKEventAPI,omitempty"` //`json:"rk_event_api" bson:"rk_event_api"`
	RKID          string                 `protobuf:"bytes,5,opt,name=RKID,proto3" json:"RKID,omitempty"`             //`json:"rk_id" bson:"rk_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRoutingKey) Reset() {
	*x = EventRoutingKey{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRoutingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRoutingKey) ProtoMessage() {}

func (x *EventRoutingKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRoutingKey.ProtoReflect.Descriptor instead.
func (*EventRoutingKey) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{0}
}

func (x *EventRoutingKey) GetRKService() string {
	if x != nil {
		return x.RKService
	}
	return ""
}

func (x *EventRoutingKey) GetRKResource() string {
	if x != nil {
		return x.RKResource
	}
	return ""
}

func (x *EventRoutingKey) GetRKAction() string {
	if x != nil {
		return x.RKAction
	}
	return ""
}

func (x *EventRoutingKey) GetRKEventAPI() string {
	if x != nil {
		return x.RKEventAPI
	}
	return ""
}

func (x *EventRoutingKey) GetRKID() string {
	if x != nil {
		return x.RKID
	}
	return ""
}

type SocketEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`               //`json:"rk_service" bson:"rk_service"`
	Action        string                 `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`       //`json:"rk_resource" bson:"rk_resource"`
	Meta          string                 `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`           //`json:"rk_action" bson:"rk_action"`
	Data          string                 `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`           //`json:"rk_event_api" bson:"rk_event_api"`
	IssuerID      string                 `protobuf:"bytes,5,opt,name=IssuerID,proto3" json:"IssuerID,omitempty"`   //`json:"rk_event_api" bson:"rk_event_api"`
	EventName     string                 `protobuf:"bytes,6,opt,name=EventName,proto3" json:"EventName,omitempty"` //`json:"resource_name" bson:"resource_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketEvent) Reset() {
	*x = SocketEvent{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketEvent) ProtoMessage() {}

func (x *SocketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketEvent.ProtoReflect.Descriptor instead.
func (*SocketEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{1}
}

func (x *SocketEvent) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SocketEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SocketEvent) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *SocketEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SocketEvent) GetIssuerID() string {
	if x != nil {
		return x.IssuerID
	}
	return ""
}

func (x *SocketEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type AlgoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"orders_list" bson:"orders_list"`
	Drones        []*Drone               `protobuf:"bytes,2,rep,name=Drones,proto3" json:"drones_list" bson:"drones_list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgoRequest) Reset() {
	*x = AlgoRequest{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoRequest) ProtoMessage() {}

func (x *AlgoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoRequest.ProtoReflect.Descriptor instead.
func (*AlgoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{2}
}

func (x *AlgoRequest) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *AlgoRequest) GetDrones() []*Drone {
	if x != nil {
		return x.Drones
	}
	return nil
}

type AlgoOptimizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"` //`json:"orders_list" bson:"orders_list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgoOptimizeResponse) Reset() {
	*x = AlgoOptimizeResponse{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgoOptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoOptimizeResponse) ProtoMessage() {}

func (x *AlgoOptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoOptimizeResponse.ProtoReflect.Descriptor instead.
func (*AlgoOptimizeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{3}
}

func (x *AlgoOptimizeResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type DroneWithCurrentFlightLane struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Drone             *ObjectTrack           `protobuf:"bytes,1,opt,name=Drone,proto3" json:"Drone,omitempty"`                         //`json:"drone,omitempty" bson:"drone,omitempty"`
	CurrentFlightLane *FlightLane            `protobuf:"bytes,2,opt,name=CurrentFlightLane,proto3" json:"CurrentFlightLane,omitempty"` //`json:"current_flight_lane,omitempty" bson:"current_flight_lane,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DroneWithCurrentFlightLane) Reset() {
	*x = DroneWithCurrentFlightLane{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneWithCurrentFlightLane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneWithCurrentFlightLane) ProtoMessage() {}

func (x *DroneWithCurrentFlightLane) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneWithCurrentFlightLane.ProtoReflect.Descriptor instead.
func (*DroneWithCurrentFlightLane) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{4}
}

func (x *DroneWithCurrentFlightLane) GetDrone() *ObjectTrack {
	if x != nil {
		return x.Drone
	}
	return nil
}

func (x *DroneWithCurrentFlightLane) GetCurrentFlightLane() *FlightLane {
	if x != nil {
		return x.CurrentFlightLane
	}
	return nil
}

type UFOMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackID       int32                  `protobuf:"varint,1,opt,name=TrackID,proto3" json:"track_id" bson:"track_id"`
	UFOPosition   *GeodeticPosition      `protobuf:"bytes,2,opt,name=UFOPosition,proto3" json:"ufo_position" bson:"ufo_position"`
	Velocity      *PolarVelocity         `protobuf:"bytes,3,opt,name=Velocity,proto3" json:"Velocity,omitempty"`       //`json:"ufo_velocity" bson:"ufo_velocity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UFOMessage) Reset() {
	*x = UFOMessage{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UFOMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UFOMessage) ProtoMessage() {}

func (x *UFOMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UFOMessage.ProtoReflect.Descriptor instead.
func (*UFOMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{5}
}

func (x *UFOMessage) GetTrackID() int32 {
	if x != nil {
		return x.TrackID
	}
	return 0
}

func (x *UFOMessage) GetUFOPosition() *GeodeticPosition {
	if x != nil {
		return x.UFOPosition
	}
	return nil
}

func (x *UFOMessage) GetVelocity() *PolarVelocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type ActiveDrone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneID       string                 `protobuf:"bytes,1,opt,name=DroneID,proto3" json:"drone_id" bson:"drone_id"`
	SegmentID     string                 `protobuf:"bytes,2,opt,name=SegmentID,proto3" json:"segment_id" bson:"segment_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveDrone) Reset() {
	*x = ActiveDrone{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveDrone) ProtoMessage() {}

func (x *ActiveDrone) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveDrone.ProtoReflect.Descriptor instead.
func (*ActiveDrone) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{6}
}

func (x *ActiveDrone) GetDroneID() string {
	if x != nil {
		return x.DroneID
	}
	return ""
}

func (x *ActiveDrone) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

type ToDeliverDrone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneID       string                 `protobuf:"bytes,1,opt,name=DroneID,proto3" json:"drone_id" bson:"drone_id"`
	FlightLaneID  string                 `protobuf:"bytes,2,opt,name=FlightLaneID,proto3" json:"flight_lane_id" bson:"flight_lane_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToDeliverDrone) Reset() {
	*x = ToDeliverDrone{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToDeliverDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDeliverDrone) ProtoMessage() {}

func (x *ToDeliverDrone) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDeliverDrone.ProtoReflect.Descriptor instead.
func (*ToDeliverDrone) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{7}
}

func (x *ToDeliverDrone) GetDroneID() string {
	if x != nil {
		return x.DroneID
	}
	return ""
}

func (x *ToDeliverDrone) GetFlightLaneID() string {
	if x != nil {
		return x.FlightLaneID
	}
	return ""
}

type AlertRequest struct {
	state                      protoimpl.MessageState        `protogen:"open.v1"`
	DroneWithCurrentFlightLane []*DroneWithCurrentFlightLane `protobuf:"bytes,1,rep,name=DroneWithCurrentFlightLane,proto3" json:"drone_with_current_flight_lane,omitempty" bson:"drone_with_current_flight_lane,omitempty"`
	UFOList                    []*UFOMessage                 `protobuf:"bytes,2,rep,name=UFOList,proto3" json:"ufo_list,omitempty" bson:"ufo_list,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{8}
}

func (x *AlertRequest) GetDroneWithCurrentFlightLane() []*DroneWithCurrentFlightLane {
	if x != nil {
		return x.DroneWithCurrentFlightLane
	}
	return nil
}

func (x *AlertRequest) GetUFOList() []*UFOMessage {
	if x != nil {
		return x.UFOList
	}
	return nil
}

type AlertResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveDrone    []*ActiveDrone         `protobuf:"bytes,1,rep,name=ActiveDrone,proto3" json:"active_drone,omitempty" bson:"active_drone,omitempty"`
	ToDeliverDrone []*ToDeliverDrone      `protobuf:"bytes,2,rep,name=ToDeliverDrone,proto3" json:"to_deliver_drone,omitempty" bson:"to_deliver_drone,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_pkg_proto_EventListener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_EventListener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_EventListener_proto_rawDescGZIP(), []int{9}
}

func (x *AlertResponse) GetActiveDrone() []*ActiveDrone {
	if x != nil {
		return x.ActiveDrone
	}
	return nil
}

func (x *AlertResponse) GetToDeliverDrone() []*ToDeliverDrone {
	if x != nil {
		return x.ToDeliverDrone
	}
	return nil
}

var File_pkg_proto_EventListener_proto protoreflect.FileDescriptor

const file_pkg_proto_EventListener_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/EventListener.proto\x12\x0eevent_listener\x1a\x15pkg/proto/Order.proto\x1a\x15pkg/proto/Drone.proto\x1a pkg/proto/SpatialAttribute.proto\x1a\x1epkg/proto/FlightCorridor.proto\"\x9f\x01\n" +
	"\x0fEventRoutingKey\x12\x1c\n" +
	"\tRKService\x18\x01 \x01(\tR\tRKService\x12\x1e\n" +
	"\n" +
	"RKResource\x18\x02 \x01(\tR\n" +
	"RKResource\x12\x1a\n" +
	"\bRKAction\x18\x03 \x01(\tR\bRKAction\x12\x1e\n" +
	"\n" +
	"RKEventAPI\x18\x04 \x01(\tR\n" +
	"RKEventAPI\x12\x12\n" +
	"\x04RKID\x18\x05 \x01(\tR\x04RKID\"\x97\x01\n" +
	"\vSocketEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Action\x18\x02 \x01(\tR\x06Action\x12\x12\n" +
	"\x04Meta\x18\x03 \x01(\tR\x04Meta\x12\x12\n" +
	"\x04Data\x18\x04 \x01(\tR\x04Data\x12\x1a\n" +
	"\bIssuerID\x18\x05 \x01(\tR\bIssuerID\x12\x1c\n" +
	"\tEventName\x18\x06 \x01(\tR\tEventName\"Y\n" +
	"\vAlgoRequest\x12$\n" +
	"\x06Orders\x18\x01 \x03(\v2\f.order.OrderR\x06Orders\x12$\n" +
	"\x06Drones\x18\x02 \x03(\v2\f.drone.DroneR\x06Drones\"<\n" +
	"\x14AlgoOptimizeResponse\x12$\n" +
	"\x06Orders\x18\x01 \x03(\v2\f.order.OrderR\x06Orders\"\x87\x01\n" +
	"\x1aDroneWithCurrentFlightLane\x12(\n" +
	"\x05Drone\x18\x01 \x01(\v2\x12.drone.ObjectTrackR\x05Drone\x12?\n" +
	"\x11CurrentFlightLane\x18\x02 \x01(\v2\x11.drone.FlightLaneR\x11CurrentFlightLane\"\xab\x01\n" +
	"\n" +
	"UFOMessage\x12\x18\n" +
	"\aTrackID\x18\x01 \x01(\x05R\aTrackID\x12E\n" +
	"\vUFOPosition\x18\x02 \x01(\v2#.spatial_attribute.GeodeticPositionR\vUFOPosition\x12<\n" +
	"\bVelocity\x18\x03 \x01(\v2 .spatial_attribute.PolarVelocityR\bVelocity\"E\n" +
	"\vActiveDrone\x12\x18\n" +
	"\aDroneID\x18\x01 \x01(\tR\aDroneID\x12\x1c\n" +
	"\tSegmentID\x18\x02 \x01(\tR\tSegmentID\"N\n" +
	"\x0eToDeliverDrone\x12\x18\n" +
	"\aDroneID\x18\x01 \x01(\tR\aDroneID\x12\"\n" +
	"\fFlightLaneID\x18\x02 \x01(\tR\fFlightLaneID\"\xb0\x01\n" +
	"\fAlertRequest\x12j\n" +
	"\x1aDroneWithCurrentFlightLane\x18\x01 \x03(\v2*.event_listener.DroneWithCurrentFlightLaneR\x1aDroneWithCurrentFlightLane\x124\n" +
	"\aUFOList\x18\x02 \x03(\v2\x1a.event_listener.UFOMessageR\aUFOList\"\x96\x01\n" +
	"\rAlertResponse\x12=\n" +
	"\vActiveDrone\x18\x01 \x03(\v2\x1b.event_listener.ActiveDroneR\vActiveDrone\x12F\n" +
	"\x0eToDeliverDrone\x18\x02 \x03(\v2\x1e.event_listener.ToDeliverDroneR\x0eToDeliverDrone2a\n" +
	"\x12AlgoMappingService\x12K\n" +
	"\x06create\x12\x1b.event_listener.AlgoRequest\x1a$.event_listener.AlgoOptimizeResponse2U\n" +
	"\fAlertService\x12E\n" +
	"\x06create\x12\x1c.event_listener.AlertRequest\x1a\x1d.event_listener.AlertResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_EventListener_proto_rawDescOnce sync.Once
	file_pkg_proto_EventListener_proto_rawDescData []byte
)

func file_pkg_proto_EventListener_proto_rawDescGZIP() []byte {
	file_pkg_proto_EventListener_proto_rawDescOnce.Do(func() {
		file_pkg_proto_EventListener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_EventListener_proto_rawDesc), len(file_pkg_proto_EventListener_proto_rawDesc)))
	})
	return file_pkg_proto_EventListener_proto_rawDescData
}

var file_pkg_proto_EventListener_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_EventListener_proto_goTypes = []any{
	(*EventRoutingKey)(nil),            // 0: event_listener.EventRoutingKey
	(*SocketEvent)(nil),                // 1: event_listener.SocketEvent
	(*AlgoRequest)(nil),                // 2: event_listener.AlgoRequest
	(*AlgoOptimizeResponse)(nil),       // 3: event_listener.AlgoOptimizeResponse
	(*DroneWithCurrentFlightLane)(nil), // 4: event_listener.DroneWithCurrentFlightLane
	(*UFOMessage)(nil),                 // 5: event_listener.UFOMessage
	(*ActiveDrone)(nil),                // 6: event_listener.ActiveDrone
	(*ToDeliverDrone)(nil),             // 7: event_listener.ToDeliverDrone
	(*AlertRequest)(nil),               // 8: event_listener.AlertRequest
	(*AlertResponse)(nil),              // 9: event_listener.AlertResponse
	(*Order)(nil),                      // 10: order.Order
	(*Drone)(nil),                      // 11: drone.Drone
	(*ObjectTrack)(nil),                // 12: drone.ObjectTrack
	(*FlightLane)(nil),                 // 13: drone.FlightLane
	(*GeodeticPosition)(nil),           // 14: spatial_attribute.GeodeticPosition
	(*PolarVelocity)(nil),              // 15: spatial_attribute.PolarVelocity
}
var file_pkg_proto_EventListener_proto_depIdxs = []int32{
	10, // 0: event_listener.AlgoRequest.Orders:type_name -> order.Order
	11, // 1: event_listener.AlgoRequest.Drones:type_name -> drone.Drone
	10, // 2: event_listener.AlgoOptimizeResponse.Orders:type_name -> order.Order
	12, // 3: event_listener.DroneWithCurrentFlightLane.Drone:type_name -> drone.ObjectTrack
	13, // 4: event_listener.DroneWithCurrentFlightLane.CurrentFlightLane:type_name -> drone.FlightLane
	14, // 5: event_listener.UFOMessage.UFOPosition:type_name -> spatial_attribute.GeodeticPosition
	15, // 6: event_listener.UFOMessage.Velocity:type_name -> spatial_attribute.PolarVelocity
	4,  // 7: event_listener.AlertRequest.DroneWithCurrentFlightLane:type_name -> event_listener.DroneWithCurrentFlightLane
	5,  // 8: event_listener.AlertRequest.UFOList:type_name -> event_listener.UFOMessage
	6,  // 9: event_listener.AlertResponse.ActiveDrone:type_name -> event_listener.ActiveDrone
	7,  // 10: event_listener.AlertResponse.ToDeliverDrone:type_name -> event_listener.ToDeliverDrone
	2,  // 11: event_listener.AlgoMappingService.create:input_type -> event_listener.AlgoRequest
	8,  // 12: event_listener.AlertService.create:input_type -> event_listener.AlertRequest
	3,  // 13: event_listener.AlgoMappingService.create:output_type -> event_listener.AlgoOptimizeResponse
	9,  // 14: event_listener.AlertService.create:output_type -> event_listener.AlertResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_EventListener_proto_init() }
func file_pkg_proto_EventListener_proto_init() {
	if File_pkg_proto_EventListener_proto != nil {
		return
	}
	file_pkg_proto_Order_proto_init()
	file_pkg_proto_Drone_proto_init()
	file_pkg_proto_SpatialAttribute_proto_init()
	file_pkg_proto_FlightCorridor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_EventListener_proto_rawDesc), len(file_pkg_proto_EventListener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_EventListener_proto_goTypes,
		DependencyIndexes: file_pkg_proto_EventListener_proto_depIdxs,
		MessageInfos:      file_pkg_proto_EventListener_proto_msgTypes,
	}.Build()
	File_pkg_proto_EventListener_proto = out.File
	file_pkg_proto_EventListener_proto_goTypes = nil
	file_pkg_proto_EventListener_proto_depIdxs = nil
}
