// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/FlightCorridor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlightCorridorService_Create_FullMethodName = "/drone.FlightCorridorService/create"
	FlightCorridorService_Search_FullMethodName = "/drone.FlightCorridorService/search"
	FlightCorridorService_Patch_FullMethodName  = "/drone.FlightCorridorService/patch"
	FlightCorridorService_Update_FullMethodName = "/drone.FlightCorridorService/update"
)

// FlightCorridorServiceClient is the client API for FlightCorridorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightCorridorServiceClient interface {
	Create(ctx context.Context, in *FlightCorridor, opts ...grpc.CallOption) (*FlightCorridor, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightCorridorResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
	Update(ctx context.Context, in *FlightCorridor, opts ...grpc.CallOption) (*FlightCorridor, error)
}

type flightCorridorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightCorridorServiceClient(cc grpc.ClientConnInterface) FlightCorridorServiceClient {
	return &flightCorridorServiceClient{cc}
}

func (c *flightCorridorServiceClient) Create(ctx context.Context, in *FlightCorridor, opts ...grpc.CallOption) (*FlightCorridor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightCorridor)
	err := c.cc.Invoke(ctx, FlightCorridorService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightCorridorServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightCorridorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFlightCorridorResponse)
	err := c.cc.Invoke(ctx, FlightCorridorService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightCorridorServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, FlightCorridorService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightCorridorServiceClient) Update(ctx context.Context, in *FlightCorridor, opts ...grpc.CallOption) (*FlightCorridor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightCorridor)
	err := c.cc.Invoke(ctx, FlightCorridorService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightCorridorServiceServer is the server API for FlightCorridorService service.
// All implementations must embed UnimplementedFlightCorridorServiceServer
// for forward compatibility.
type FlightCorridorServiceServer interface {
	Create(context.Context, *FlightCorridor) (*FlightCorridor, error)
	Search(context.Context, *SearchOptions) (*SearchFlightCorridorResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	Update(context.Context, *FlightCorridor) (*FlightCorridor, error)
	mustEmbedUnimplementedFlightCorridorServiceServer()
}

// UnimplementedFlightCorridorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightCorridorServiceServer struct{}

func (UnimplementedFlightCorridorServiceServer) Create(context.Context, *FlightCorridor) (*FlightCorridor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedFlightCorridorServiceServer) Search(context.Context, *SearchOptions) (*SearchFlightCorridorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedFlightCorridorServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedFlightCorridorServiceServer) Update(context.Context, *FlightCorridor) (*FlightCorridor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedFlightCorridorServiceServer) mustEmbedUnimplementedFlightCorridorServiceServer() {}
func (UnimplementedFlightCorridorServiceServer) testEmbeddedByValue()                               {}

// UnsafeFlightCorridorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightCorridorServiceServer will
// result in compilation errors.
type UnsafeFlightCorridorServiceServer interface {
	mustEmbedUnimplementedFlightCorridorServiceServer()
}

func RegisterFlightCorridorServiceServer(s grpc.ServiceRegistrar, srv FlightCorridorServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightCorridorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightCorridorService_ServiceDesc, srv)
}

func _FlightCorridorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightCorridor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightCorridorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightCorridorService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightCorridorServiceServer).Create(ctx, req.(*FlightCorridor))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightCorridorService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightCorridorServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightCorridorService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightCorridorServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightCorridorService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightCorridorServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightCorridorService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightCorridorServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightCorridorService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightCorridor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightCorridorServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightCorridorService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightCorridorServiceServer).Update(ctx, req.(*FlightCorridor))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightCorridorService_ServiceDesc is the grpc.ServiceDesc for FlightCorridorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightCorridorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.FlightCorridorService",
	HandlerType: (*FlightCorridorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _FlightCorridorService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _FlightCorridorService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _FlightCorridorService_Patch_Handler,
		},
		{
			MethodName: "update",
			Handler:    _FlightCorridorService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/FlightCorridor.proto",
}

const (
	FlightLaneService_Create_FullMethodName = "/drone.FlightLaneService/create"
	FlightLaneService_Search_FullMethodName = "/drone.FlightLaneService/search"
	FlightLaneService_Patch_FullMethodName  = "/drone.FlightLaneService/patch"
	FlightLaneService_Update_FullMethodName = "/drone.FlightLaneService/update"
)

// FlightLaneServiceClient is the client API for FlightLaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightLaneServiceClient interface {
	Create(ctx context.Context, in *FlightLane, opts ...grpc.CallOption) (*FlightLane, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightLaneResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
	Update(ctx context.Context, in *FlightLane, opts ...grpc.CallOption) (*FlightLane, error)
}

type flightLaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightLaneServiceClient(cc grpc.ClientConnInterface) FlightLaneServiceClient {
	return &flightLaneServiceClient{cc}
}

func (c *flightLaneServiceClient) Create(ctx context.Context, in *FlightLane, opts ...grpc.CallOption) (*FlightLane, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightLane)
	err := c.cc.Invoke(ctx, FlightLaneService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightLaneServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFlightLaneResponse)
	err := c.cc.Invoke(ctx, FlightLaneService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightLaneServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, FlightLaneService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightLaneServiceClient) Update(ctx context.Context, in *FlightLane, opts ...grpc.CallOption) (*FlightLane, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightLane)
	err := c.cc.Invoke(ctx, FlightLaneService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightLaneServiceServer is the server API for FlightLaneService service.
// All implementations must embed UnimplementedFlightLaneServiceServer
// for forward compatibility.
type FlightLaneServiceServer interface {
	Create(context.Context, *FlightLane) (*FlightLane, error)
	Search(context.Context, *SearchOptions) (*SearchFlightLaneResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	Update(context.Context, *FlightLane) (*FlightLane, error)
	mustEmbedUnimplementedFlightLaneServiceServer()
}

// UnimplementedFlightLaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightLaneServiceServer struct{}

func (UnimplementedFlightLaneServiceServer) Create(context.Context, *FlightLane) (*FlightLane, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedFlightLaneServiceServer) Search(context.Context, *SearchOptions) (*SearchFlightLaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedFlightLaneServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedFlightLaneServiceServer) Update(context.Context, *FlightLane) (*FlightLane, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedFlightLaneServiceServer) mustEmbedUnimplementedFlightLaneServiceServer() {}
func (UnimplementedFlightLaneServiceServer) testEmbeddedByValue()                           {}

// UnsafeFlightLaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightLaneServiceServer will
// result in compilation errors.
type UnsafeFlightLaneServiceServer interface {
	mustEmbedUnimplementedFlightLaneServiceServer()
}

func RegisterFlightLaneServiceServer(s grpc.ServiceRegistrar, srv FlightLaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightLaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightLaneService_ServiceDesc, srv)
}

func _FlightLaneService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightLane)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightLaneServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightLaneService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightLaneServiceServer).Create(ctx, req.(*FlightLane))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightLaneService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightLaneServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightLaneService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightLaneServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightLaneService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightLaneServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightLaneService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightLaneServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightLaneService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightLane)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightLaneServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightLaneService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightLaneServiceServer).Update(ctx, req.(*FlightLane))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightLaneService_ServiceDesc is the grpc.ServiceDesc for FlightLaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightLaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.FlightLaneService",
	HandlerType: (*FlightLaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _FlightLaneService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _FlightLaneService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _FlightLaneService_Patch_Handler,
		},
		{
			MethodName: "update",
			Handler:    _FlightLaneService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/FlightCorridor.proto",
}
