// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/FlightArea.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlightAreaService_Create_FullMethodName = "/drone.FlightAreaService/create"
	FlightAreaService_Search_FullMethodName = "/drone.FlightAreaService/search"
	FlightAreaService_Patch_FullMethodName  = "/drone.FlightAreaService/patch"
	FlightAreaService_Update_FullMethodName = "/drone.FlightAreaService/update"
)

// FlightAreaServiceClient is the client API for FlightAreaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightAreaServiceClient interface {
	Create(ctx context.Context, in *FlightArea, opts ...grpc.CallOption) (*FlightArea, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightAreaResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
	Update(ctx context.Context, in *FlightArea, opts ...grpc.CallOption) (*FlightArea, error)
}

type flightAreaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightAreaServiceClient(cc grpc.ClientConnInterface) FlightAreaServiceClient {
	return &flightAreaServiceClient{cc}
}

func (c *flightAreaServiceClient) Create(ctx context.Context, in *FlightArea, opts ...grpc.CallOption) (*FlightArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightArea)
	err := c.cc.Invoke(ctx, FlightAreaService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightAreaServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchFlightAreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFlightAreaResponse)
	err := c.cc.Invoke(ctx, FlightAreaService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightAreaServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, FlightAreaService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightAreaServiceClient) Update(ctx context.Context, in *FlightArea, opts ...grpc.CallOption) (*FlightArea, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightArea)
	err := c.cc.Invoke(ctx, FlightAreaService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightAreaServiceServer is the server API for FlightAreaService service.
// All implementations must embed UnimplementedFlightAreaServiceServer
// for forward compatibility.
type FlightAreaServiceServer interface {
	Create(context.Context, *FlightArea) (*FlightArea, error)
	Search(context.Context, *SearchOptions) (*SearchFlightAreaResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	Update(context.Context, *FlightArea) (*FlightArea, error)
	mustEmbedUnimplementedFlightAreaServiceServer()
}

// UnimplementedFlightAreaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightAreaServiceServer struct{}

func (UnimplementedFlightAreaServiceServer) Create(context.Context, *FlightArea) (*FlightArea, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedFlightAreaServiceServer) Search(context.Context, *SearchOptions) (*SearchFlightAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedFlightAreaServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedFlightAreaServiceServer) Update(context.Context, *FlightArea) (*FlightArea, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedFlightAreaServiceServer) mustEmbedUnimplementedFlightAreaServiceServer() {}
func (UnimplementedFlightAreaServiceServer) testEmbeddedByValue()                           {}

// UnsafeFlightAreaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightAreaServiceServer will
// result in compilation errors.
type UnsafeFlightAreaServiceServer interface {
	mustEmbedUnimplementedFlightAreaServiceServer()
}

func RegisterFlightAreaServiceServer(s grpc.ServiceRegistrar, srv FlightAreaServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightAreaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightAreaService_ServiceDesc, srv)
}

func _FlightAreaService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightArea)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightAreaServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightAreaService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightAreaServiceServer).Create(ctx, req.(*FlightArea))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightAreaService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightAreaServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightAreaService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightAreaServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightAreaService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightAreaServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightAreaService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightAreaServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightAreaService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightArea)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightAreaServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightAreaService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightAreaServiceServer).Update(ctx, req.(*FlightArea))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightAreaService_ServiceDesc is the grpc.ServiceDesc for FlightAreaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightAreaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.FlightAreaService",
	HandlerType: (*FlightAreaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _FlightAreaService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _FlightAreaService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _FlightAreaService_Patch_Handler,
		},
		{
			MethodName: "update",
			Handler:    _FlightAreaService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/FlightArea.proto",
}
