// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/FlightCorridor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightCorridor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	Offset        float64                `protobuf:"fixed64,2,opt,name=Offset,proto3" json:"offset,omitempty" bson:"offset"`
	Corridor      []*GeodeticPosition    `protobuf:"bytes,3,rep,name=Corridor,proto3" json:"corridor,omitempty" bson:"corridor"`
	UserID        string                 `protobuf:"bytes,4,opt,name=UserID,proto3" json:"user_id,omitempty" bson:"user_id"`
	LockerIDs     []string               `protobuf:"bytes,5,rep,name=LockerIDs,proto3" json:"locker_id_list,omitempty" bson:"locker_id_list"`
	ValidateStatus AT_VALIDATE_STATUS     `protobuf:"varint,6,opt,name=ValidateStatus,proto3,enum=drone.AT_VALIDATE_STATUS" json:"validate_status,omitempty" bson:"validate_status"`
	CreatedAt     uint64                 `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64                 `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string                 `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string                 `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightCorridor) Reset() {
	*x = FlightCorridor{}
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightCorridor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightCorridor) ProtoMessage() {}

func (x *FlightCorridor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightCorridor.ProtoReflect.Descriptor instead.
func (*FlightCorridor) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightCorridor_proto_rawDescGZIP(), []int{0}
}

func (x *FlightCorridor) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *FlightCorridor) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FlightCorridor) GetCorridor() []*GeodeticPosition {
	if x != nil {
		return x.Corridor
	}
	return nil
}

func (x *FlightCorridor) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FlightCorridor) GetLockerIDs() []string {
	if x != nil {
		return x.LockerIDs
	}
	return nil
}

func (x *FlightCorridor) GetValidateStatus() AT_VALIDATE_STATUS {
	if x != nil {
		return x.ValidateStatus
	}
	return AT_VALIDATE_STATUS_ADS_CREATED
}

func (x *FlightCorridor) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FlightCorridor) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FlightCorridor) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FlightCorridor) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchFlightCorridorResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FlightCorridors []*FlightCorridor      `protobuf:"bytes,1,rep,name=FlightCorridors,proto3" json:"FlightCorridors,omitempty"` //
	TotalCount      int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`          //
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchFlightCorridorResponse) Reset() {
	*x = SearchFlightCorridorResponse{}
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightCorridorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightCorridorResponse) ProtoMessage() {}

func (x *SearchFlightCorridorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightCorridorResponse.ProtoReflect.Descriptor instead.
func (*SearchFlightCorridorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightCorridor_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFlightCorridorResponse) GetFlightCorridors() []*FlightCorridor {
	if x != nil {
		return x.FlightCorridors
	}
	return nil
}

func (x *SearchFlightCorridorResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type FlightLane struct {
	state          protoimpl.MessageState                 `protogen:"open.v1"`
	ID             string                                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	Offset         float64                                `protobuf:"fixed64,2,opt,name=Offset,proto3" json:"offset,omitempty" bson:"offset"`
	Corridor       []*GeodeticPositionWithTimeAndVelocity `protobuf:"bytes,3,rep,name=Corridor,proto3" json:"position,omitempty" bson:"position"`
	UserID         string                                 `protobuf:"bytes,4,opt,name=UserID,proto3" json:"user_id,omitempty" bson:"user_id"`
	CorridorID     string                                 `protobuf:"bytes,5,opt,name=CorridorID,proto3" json:"corridor_id,omitempty" bson:"corridor_id"`
	StartLockerID  string                                 `protobuf:"bytes,6,opt,name=StartLockerID,proto3" json:"start_locker_id,omitempty" bson:"start_locker_id"`
	EndLockerID    string                                 `protobuf:"bytes,7,opt,name=EndLockerID,proto3" json:"end_locker_id,omitempty" bson:"end_locker_id"`
	ValidateStatus AT_VALIDATE_STATUS                     `protobuf:"varint,8,opt,name=ValidateStatus,proto3,enum=drone.AT_VALIDATE_STATUS" json:"validate_status,omitempty" bson:"validate_status"`
	DelayTime      float64                                `protobuf:"fixed64,9,opt,name=DelayTime,proto3" json:"delay_time,omitempty" bson:"delay_time"`
	ActualTime     float64                                `protobuf:"fixed64,10,opt,name=ActualTime,proto3" json:"actual_time,omitempty" bson:"actual_time"`
	CreatedAt      uint64                                 `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt      uint64                                 `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy      string                                 `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy      string                                 `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlightLane) Reset() {
	*x = FlightLane{}
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightLane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightLane) ProtoMessage() {}

func (x *FlightLane) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightLane.ProtoReflect.Descriptor instead.
func (*FlightLane) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightCorridor_proto_rawDescGZIP(), []int{2}
}

func (x *FlightLane) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *FlightLane) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FlightLane) GetCorridor() []*GeodeticPositionWithTimeAndVelocity {
	if x != nil {
		return x.Corridor
	}
	return nil
}

func (x *FlightLane) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FlightLane) GetCorridorID() string {
	if x != nil {
		return x.CorridorID
	}
	return ""
}

func (x *FlightLane) GetStartLockerID() string {
	if x != nil {
		return x.StartLockerID
	}
	return ""
}

func (x *FlightLane) GetEndLockerID() string {
	if x != nil {
		return x.EndLockerID
	}
	return ""
}

func (x *FlightLane) GetValidateStatus() AT_VALIDATE_STATUS {
	if x != nil {
		return x.ValidateStatus
	}
	return AT_VALIDATE_STATUS_ADS_CREATED
}

func (x *FlightLane) GetDelayTime() float64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *FlightLane) GetActualTime() float64 {
	if x != nil {
		return x.ActualTime
	}
	return 0
}

func (x *FlightLane) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FlightLane) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FlightLane) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FlightLane) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchFlightLaneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightLanes   []*FlightLane          `protobuf:"bytes,1,rep,name=FlightLanes,proto3" json:"FlightLanes,omitempty"` //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`  //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlightLaneResponse) Reset() {
	*x = SearchFlightLaneResponse{}
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightLaneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightLaneResponse) ProtoMessage() {}

func (x *SearchFlightLaneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightCorridor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightLaneResponse.ProtoReflect.Descriptor instead.
func (*SearchFlightLaneResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightCorridor_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFlightLaneResponse) GetFlightLanes() []*FlightLane {
	if x != nil {
		return x.FlightLanes
	}
	return nil
}

func (x *SearchFlightLaneResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_FlightCorridor_proto protoreflect.FileDescriptor

const file_pkg_proto_FlightCorridor_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/proto/FlightCorridor.proto\x12\x05drone\x1a pkg/proto/SpatialAttribute.proto\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\x1a\x15pkg/proto/Drone.proto\"\xea\x02\n" +
	"\x0eFlightCorridor\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x01R\x06Offset\x12?\n" +
	"\bCorridor\x18\x03 \x03(\v2#.spatial_attribute.GeodeticPositionR\bCorridor\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\tR\x06UserID\x12\x1c\n" +
	"\tLockerIDs\x18\x05 \x03(\tR\tLockerIDs\x12A\n" +
	"\x0eValidateStatus\x18\x06 \x01(\x0e2\x19.drone.AT_VALIDATE_STATUSR\x0eValidateStatus\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"\x7f\n" +
	"\x1cSearchFlightCorridorResponse\x12?\n" +
	"\x0fFlightCorridors\x18\x01 \x03(\v2\x15.drone.FlightCorridorR\x0fFlightCorridors\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount\"\x81\x04\n" +
	"\n" +
	"FlightLane\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x01R\x06Offset\x12R\n" +
	"\bCorridor\x18\x03 \x03(\v26.spatial_attribute.GeodeticPositionWithTimeAndVelocityR\bCorridor\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\tR\x06UserID\x12\x1e\n" +
	"\n" +
	"CorridorID\x18\x05 \x01(\tR\n" +
	"CorridorID\x12$\n" +
	"\rStartLockerID\x18\x06 \x01(\tR\rStartLockerID\x12 \n" +
	"\vEndLockerID\x18\a \x01(\tR\vEndLockerID\x12A\n" +
	"\x0eValidateStatus\x18\b \x01(\x0e2\x19.drone.AT_VALIDATE_STATUSR\x0eValidateStatus\x12\x1c\n" +
	"\tDelayTime\x18\t \x01(\x01R\tDelayTime\x12\x1e\n" +
	"\n" +
	"ActualTime\x18\n" +
	" \x01(\x01R\n" +
	"ActualTime\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"o\n" +
	"\x18SearchFlightLaneResponse\x123\n" +
	"\vFlightLanes\x18\x01 \x03(\v2\x11.drone.FlightLaneR\vFlightLanes\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount2\x99\x02\n" +
	"\x15FlightCorridorService\x126\n" +
	"\x06create\x12\x15.drone.FlightCorridor\x1a\x15.drone.FlightCorridor\x12L\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a#.drone.SearchFlightCorridorResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x126\n" +
	"\x06update\x12\x15.drone.FlightCorridor\x1a\x15.drone.FlightCorridor2\x81\x02\n" +
	"\x11FlightLaneService\x12.\n" +
	"\x06create\x12\x11.drone.FlightLane\x1a\x11.drone.FlightLane\x12H\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x1f.drone.SearchFlightLaneResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x12.\n" +
	"\x06update\x12\x11.drone.FlightLane\x1a\x11.drone.FlightLaneB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_FlightCorridor_proto_rawDescOnce sync.Once
	file_pkg_proto_FlightCorridor_proto_rawDescData []byte
)

func file_pkg_proto_FlightCorridor_proto_rawDescGZIP() []byte {
	file_pkg_proto_FlightCorridor_proto_rawDescOnce.Do(func() {
		file_pkg_proto_FlightCorridor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightCorridor_proto_rawDesc), len(file_pkg_proto_FlightCorridor_proto_rawDesc)))
	})
	return file_pkg_proto_FlightCorridor_proto_rawDescData
}

var file_pkg_proto_FlightCorridor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_FlightCorridor_proto_goTypes = []any{
	(*FlightCorridor)(nil),                      // 0: drone.FlightCorridor
	(*SearchFlightCorridorResponse)(nil),        // 1: drone.SearchFlightCorridorResponse
	(*FlightLane)(nil),                          // 2: drone.FlightLane
	(*SearchFlightLaneResponse)(nil),            // 3: drone.SearchFlightLaneResponse
	(*GeodeticPosition)(nil),                    // 4: spatial_attribute.GeodeticPosition
	(AT_VALIDATE_STATUS)(0),                     // 5: drone.AT_VALIDATE_STATUS
	(*GeodeticPositionWithTimeAndVelocity)(nil), // 6: spatial_attribute.GeodeticPositionWithTimeAndVelocity
	(*SearchOptions)(nil),                       // 7: search_options.SearchOptions
	(*PatchOptions)(nil),                        // 8: patch_options.PatchOptions
	(*PatchResponse)(nil),                       // 9: patch_options.PatchResponse
}
var file_pkg_proto_FlightCorridor_proto_depIdxs = []int32{
	4,  // 0: drone.FlightCorridor.Corridor:type_name -> spatial_attribute.GeodeticPosition
	5,  // 1: drone.FlightCorridor.ValidateStatus:type_name -> drone.AT_VALIDATE_STATUS
	0,  // 2: drone.SearchFlightCorridorResponse.FlightCorridors:type_name -> drone.FlightCorridor
	6,  // 3: drone.FlightLane.Corridor:type_name -> spatial_attribute.GeodeticPositionWithTimeAndVelocity
	5,  // 4: drone.FlightLane.ValidateStatus:type_name -> drone.AT_VALIDATE_STATUS
	2,  // 5: drone.SearchFlightLaneResponse.FlightLanes:type_name -> drone.FlightLane
	0,  // 6: drone.FlightCorridorService.create:input_type -> drone.FlightCorridor
	7,  // 7: drone.FlightCorridorService.search:input_type -> search_options.SearchOptions
	8,  // 8: drone.FlightCorridorService.patch:input_type -> patch_options.PatchOptions
	0,  // 9: drone.FlightCorridorService.update:input_type -> drone.FlightCorridor
	2,  // 10: drone.FlightLaneService.create:input_type -> drone.FlightLane
	7,  // 11: drone.FlightLaneService.search:input_type -> search_options.SearchOptions
	8,  // 12: drone.FlightLaneService.patch:input_type -> patch_options.PatchOptions
	2,  // 13: drone.FlightLaneService.update:input_type -> drone.FlightLane
	0,  // 14: drone.FlightCorridorService.create:output_type -> drone.FlightCorridor
	1,  // 15: drone.FlightCorridorService.search:output_type -> drone.SearchFlightCorridorResponse
	9,  // 16: drone.FlightCorridorService.patch:output_type -> patch_options.PatchResponse
	0,  // 17: drone.FlightCorridorService.update:output_type -> drone.FlightCorridor
	2,  // 18: drone.FlightLaneService.create:output_type -> drone.FlightLane
	3,  // 19: drone.FlightLaneService.search:output_type -> drone.SearchFlightLaneResponse
	9,  // 20: drone.FlightLaneService.patch:output_type -> patch_options.PatchResponse
	2,  // 21: drone.FlightLaneService.update:output_type -> drone.FlightLane
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_FlightCorridor_proto_init() }
func file_pkg_proto_FlightCorridor_proto_init() {
	if File_pkg_proto_FlightCorridor_proto != nil {
		return
	}
	file_pkg_proto_SpatialAttribute_proto_init()
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	file_pkg_proto_Drone_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightCorridor_proto_rawDesc), len(file_pkg_proto_FlightCorridor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_FlightCorridor_proto_goTypes,
		DependencyIndexes: file_pkg_proto_FlightCorridor_proto_depIdxs,
		MessageInfos:      file_pkg_proto_FlightCorridor_proto_msgTypes,
	}.Build()
	File_pkg_proto_FlightCorridor_proto = out.File
	file_pkg_proto_FlightCorridor_proto_goTypes = nil
	file_pkg_proto_FlightCorridor_proto_depIdxs = nil
}
