// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/FlightRoute.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=Latitude,proto3" json:"latitude" bson:"latitude" validate:"gte=-90,lte=90.0"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"longitude" bson:"longitude" validate:"gte=-180,lte=180"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=Altitude,proto3" json:"altitude" bson:"altitude" validate:"gte=0,lte=99999"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightRoute) Reset() {
	*x = FlightRoute{}
	mi := &file_pkg_proto_FlightRoute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightRoute) ProtoMessage() {}

func (x *FlightRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightRoute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightRoute.ProtoReflect.Descriptor instead.
func (*FlightRoute) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightRoute_proto_rawDescGZIP(), []int{0}
}

func (x *FlightRoute) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FlightRoute) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FlightRoute) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

var File_pkg_proto_FlightRoute_proto protoreflect.FileDescriptor

const file_pkg_proto_FlightRoute_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/FlightRoute.proto\x12\fflight_route\"c\n" +
	"\vFlightRoute\x12\x1a\n" +
	"\bLatitude\x18\x01 \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\x02 \x01(\x01R\tLongitude\x12\x1a\n" +
	"\bAltitude\x18\x03 \x01(\x01R\bAltitudeB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_FlightRoute_proto_rawDescOnce sync.Once
	file_pkg_proto_FlightRoute_proto_rawDescData []byte
)

func file_pkg_proto_FlightRoute_proto_rawDescGZIP() []byte {
	file_pkg_proto_FlightRoute_proto_rawDescOnce.Do(func() {
		file_pkg_proto_FlightRoute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightRoute_proto_rawDesc), len(file_pkg_proto_FlightRoute_proto_rawDesc)))
	})
	return file_pkg_proto_FlightRoute_proto_rawDescData
}

var file_pkg_proto_FlightRoute_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_FlightRoute_proto_goTypes = []any{
	(*FlightRoute)(nil), // 0: flight_route.FlightRoute
}
var file_pkg_proto_FlightRoute_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_FlightRoute_proto_init() }
func file_pkg_proto_FlightRoute_proto_init() {
	if File_pkg_proto_FlightRoute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightRoute_proto_rawDesc), len(file_pkg_proto_FlightRoute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_FlightRoute_proto_goTypes,
		DependencyIndexes: file_pkg_proto_FlightRoute_proto_depIdxs,
		MessageInfos:      file_pkg_proto_FlightRoute_proto_msgTypes,
	}.Build()
	File_pkg_proto_FlightRoute_proto = out.File
	file_pkg_proto_FlightRoute_proto_goTypes = nil
	file_pkg_proto_FlightRoute_proto_depIdxs = nil
}
