// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/FlightArea.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	Boundary      []*GeographicPosition  `protobuf:"bytes,2,rep,name=Boundary,proto3" json:"boundary,omitempty" bson:"boundary"`
	UserID        string                 `protobuf:"bytes,3,opt,name=UserID,proto3" json:"user_id,omitempty" bson:"user_id"`
	CreatedAt     uint64                 `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64                 `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string                 `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string                 `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightArea) Reset() {
	*x = FlightArea{}
	mi := &file_pkg_proto_FlightArea_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightArea) ProtoMessage() {}

func (x *FlightArea) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightArea_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightArea.ProtoReflect.Descriptor instead.
func (*FlightArea) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightArea_proto_rawDescGZIP(), []int{0}
}

func (x *FlightArea) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *FlightArea) GetBoundary() []*GeographicPosition {
	if x != nil {
		return x.Boundary
	}
	return nil
}

func (x *FlightArea) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FlightArea) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FlightArea) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FlightArea) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FlightArea) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchFlightAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightAreas   []*FlightArea          `protobuf:"bytes,1,rep,name=FlightAreas,proto3" json:"FlightAreas,omitempty"` //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`  //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlightAreaResponse) Reset() {
	*x = SearchFlightAreaResponse{}
	mi := &file_pkg_proto_FlightArea_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightAreaResponse) ProtoMessage() {}

func (x *SearchFlightAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_FlightArea_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightAreaResponse.ProtoReflect.Descriptor instead.
func (*SearchFlightAreaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_FlightArea_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFlightAreaResponse) GetFlightAreas() []*FlightArea {
	if x != nil {
		return x.FlightAreas
	}
	return nil
}

func (x *SearchFlightAreaResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_FlightArea_proto protoreflect.FileDescriptor

const file_pkg_proto_FlightArea_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/FlightArea.proto\x12\x05drone\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\x1a pkg/proto/SpatialAttribute.proto\"\xef\x01\n" +
	"\n" +
	"FlightArea\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12A\n" +
	"\bBoundary\x18\x02 \x03(\v2%.spatial_attribute.GeographicPositionR\bBoundary\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\tR\x06UserID\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"o\n" +
	"\x18SearchFlightAreaResponse\x123\n" +
	"\vFlightAreas\x18\x01 \x03(\v2\x11.drone.FlightAreaR\vFlightAreas\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount2\x81\x02\n" +
	"\x11FlightAreaService\x12.\n" +
	"\x06create\x12\x11.drone.FlightArea\x1a\x11.drone.FlightArea\x12H\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x1f.drone.SearchFlightAreaResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x12.\n" +
	"\x06update\x12\x11.drone.FlightArea\x1a\x11.drone.FlightAreaB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_FlightArea_proto_rawDescOnce sync.Once
	file_pkg_proto_FlightArea_proto_rawDescData []byte
)

func file_pkg_proto_FlightArea_proto_rawDescGZIP() []byte {
	file_pkg_proto_FlightArea_proto_rawDescOnce.Do(func() {
		file_pkg_proto_FlightArea_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightArea_proto_rawDesc), len(file_pkg_proto_FlightArea_proto_rawDesc)))
	})
	return file_pkg_proto_FlightArea_proto_rawDescData
}

var file_pkg_proto_FlightArea_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_FlightArea_proto_goTypes = []any{
	(*FlightArea)(nil),               // 0: drone.FlightArea
	(*SearchFlightAreaResponse)(nil), // 1: drone.SearchFlightAreaResponse
	(*GeographicPosition)(nil),       // 2: spatial_attribute.GeographicPosition
	(*SearchOptions)(nil),            // 3: search_options.SearchOptions
	(*PatchOptions)(nil),             // 4: patch_options.PatchOptions
	(*PatchResponse)(nil),            // 5: patch_options.PatchResponse
}
var file_pkg_proto_FlightArea_proto_depIdxs = []int32{
	2, // 0: drone.FlightArea.Boundary:type_name -> spatial_attribute.GeographicPosition
	0, // 1: drone.SearchFlightAreaResponse.FlightAreas:type_name -> drone.FlightArea
	0, // 2: drone.FlightAreaService.create:input_type -> drone.FlightArea
	3, // 3: drone.FlightAreaService.search:input_type -> search_options.SearchOptions
	4, // 4: drone.FlightAreaService.patch:input_type -> patch_options.PatchOptions
	0, // 5: drone.FlightAreaService.update:input_type -> drone.FlightArea
	0, // 6: drone.FlightAreaService.create:output_type -> drone.FlightArea
	1, // 7: drone.FlightAreaService.search:output_type -> drone.SearchFlightAreaResponse
	5, // 8: drone.FlightAreaService.patch:output_type -> patch_options.PatchResponse
	0, // 9: drone.FlightAreaService.update:output_type -> drone.FlightArea
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_FlightArea_proto_init() }
func file_pkg_proto_FlightArea_proto_init() {
	if File_pkg_proto_FlightArea_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	file_pkg_proto_SpatialAttribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_FlightArea_proto_rawDesc), len(file_pkg_proto_FlightArea_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_FlightArea_proto_goTypes,
		DependencyIndexes: file_pkg_proto_FlightArea_proto_depIdxs,
		MessageInfos:      file_pkg_proto_FlightArea_proto_msgTypes,
	}.Build()
	File_pkg_proto_FlightArea_proto = out.File
	file_pkg_proto_FlightArea_proto_goTypes = nil
	file_pkg_proto_FlightArea_proto_depIdxs = nil
}
