// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Gcs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GCS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	GcsAddress    string                 `protobuf:"bytes,2,opt,name=GcsAddress,proto3" json:"gcs_address,omitempty" bson:"gcs_address"`
	ProviderID    string                 `protobuf:"bytes,3,opt,name=ProviderID,proto3" json:"provider_id,omitempty" bson:"provider_id"`
	Status        string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"status,omitempty" bson:"status"`
	Position      []float64              `protobuf:"fixed64,5,rep,packed,name=Position,proto3" json:"position,omitempty" bson:"position"`
	CreatedAt     uint64                 `protobuf:"varint,55,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64                 `protobuf:"varint,56,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string                 `protobuf:"bytes,57,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string                 `protobuf:"bytes,58,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCS) Reset() {
	*x = GCS{}
	mi := &file_pkg_proto_Gcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCS) ProtoMessage() {}

func (x *GCS) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Gcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCS.ProtoReflect.Descriptor instead.
func (*GCS) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Gcs_proto_rawDescGZIP(), []int{0}
}

func (x *GCS) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GCS) GetGcsAddress() string {
	if x != nil {
		return x.GcsAddress
	}
	return ""
}

func (x *GCS) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *GCS) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GCS) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GCS) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GCS) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GCS) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GCS) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchGCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GCSs          []*GCS                 `protobuf:"bytes,1,rep,name=GCSs,proto3" json:"GCSs,omitempty"`              //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGCSResponse) Reset() {
	*x = SearchGCSResponse{}
	mi := &file_pkg_proto_Gcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGCSResponse) ProtoMessage() {}

func (x *SearchGCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Gcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGCSResponse.ProtoReflect.Descriptor instead.
func (*SearchGCSResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Gcs_proto_rawDescGZIP(), []int{1}
}

func (x *SearchGCSResponse) GetGCSs() []*GCS {
	if x != nil {
		return x.GCSs
	}
	return nil
}

func (x *SearchGCSResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_Gcs_proto protoreflect.FileDescriptor

const file_pkg_proto_Gcs_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/Gcs.proto\x12\x04user\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\"\x81\x02\n" +
	"\x03GCS\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1e\n" +
	"\n" +
	"GcsAddress\x18\x02 \x01(\tR\n" +
	"GcsAddress\x12\x1e\n" +
	"\n" +
	"ProviderID\x18\x03 \x01(\tR\n" +
	"ProviderID\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x1a\n" +
	"\bPosition\x18\x05 \x03(\x01R\bPosition\x12\x1c\n" +
	"\tCreatedAt\x187 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x188 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x189 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18: \x01(\tR\tUpdatedBy\"R\n" +
	"\x11SearchGCSResponse\x12\x1d\n" +
	"\x04GCSs\x18\x01 \x03(\v2\t.user.GCSR\x04GCSs\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount2\xb2\x01\n" +
	"\n" +
	"GCSService\x12\x1e\n" +
	"\x06create\x12\t.user.GCS\x1a\t.user.GCS\x12@\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x17.user.SearchGCSResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Gcs_proto_rawDescOnce sync.Once
	file_pkg_proto_Gcs_proto_rawDescData []byte
)

func file_pkg_proto_Gcs_proto_rawDescGZIP() []byte {
	file_pkg_proto_Gcs_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Gcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Gcs_proto_rawDesc), len(file_pkg_proto_Gcs_proto_rawDesc)))
	})
	return file_pkg_proto_Gcs_proto_rawDescData
}

var file_pkg_proto_Gcs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_Gcs_proto_goTypes = []any{
	(*GCS)(nil),               // 0: user.GCS
	(*SearchGCSResponse)(nil), // 1: user.SearchGCSResponse
	(*SearchOptions)(nil),     // 2: search_options.SearchOptions
	(*PatchOptions)(nil),      // 3: patch_options.PatchOptions
	(*PatchResponse)(nil),     // 4: patch_options.PatchResponse
}
var file_pkg_proto_Gcs_proto_depIdxs = []int32{
	0, // 0: user.SearchGCSResponse.GCSs:type_name -> user.GCS
	0, // 1: user.GCSService.create:input_type -> user.GCS
	2, // 2: user.GCSService.search:input_type -> search_options.SearchOptions
	3, // 3: user.GCSService.patch:input_type -> patch_options.PatchOptions
	0, // 4: user.GCSService.create:output_type -> user.GCS
	1, // 5: user.GCSService.search:output_type -> user.SearchGCSResponse
	4, // 6: user.GCSService.patch:output_type -> patch_options.PatchResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_Gcs_proto_init() }
func file_pkg_proto_Gcs_proto_init() {
	if File_pkg_proto_Gcs_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Gcs_proto_rawDesc), len(file_pkg_proto_Gcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_Gcs_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Gcs_proto_depIdxs,
		MessageInfos:      file_pkg_proto_Gcs_proto_msgTypes,
	}.Build()
	File_pkg_proto_Gcs_proto = out.File
	file_pkg_proto_Gcs_proto_goTypes = nil
	file_pkg_proto_Gcs_proto_depIdxs = nil
}
