// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/Gcs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GCSService_Create_FullMethodName = "/user.GCSService/create"
	GCSService_Search_FullMethodName = "/user.GCSService/search"
	GCSService_Patch_FullMethodName  = "/user.GCSService/patch"
)

// GCSServiceClient is the client API for GCSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GCSServiceClient interface {
	Create(ctx context.Context, in *GCS, opts ...grpc.CallOption) (*GCS, error)
	Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchGCSResponse, error)
	Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error)
}

type gCSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGCSServiceClient(cc grpc.ClientConnInterface) GCSServiceClient {
	return &gCSServiceClient{cc}
}

func (c *gCSServiceClient) Create(ctx context.Context, in *GCS, opts ...grpc.CallOption) (*GCS, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GCS)
	err := c.cc.Invoke(ctx, GCSService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gCSServiceClient) Search(ctx context.Context, in *SearchOptions, opts ...grpc.CallOption) (*SearchGCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGCSResponse)
	err := c.cc.Invoke(ctx, GCSService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gCSServiceClient) Patch(ctx context.Context, in *PatchOptions, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, GCSService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GCSServiceServer is the server API for GCSService service.
// All implementations must embed UnimplementedGCSServiceServer
// for forward compatibility.
type GCSServiceServer interface {
	Create(context.Context, *GCS) (*GCS, error)
	Search(context.Context, *SearchOptions) (*SearchGCSResponse, error)
	Patch(context.Context, *PatchOptions) (*PatchResponse, error)
	mustEmbedUnimplementedGCSServiceServer()
}

// UnimplementedGCSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGCSServiceServer struct{}

func (UnimplementedGCSServiceServer) Create(context.Context, *GCS) (*GCS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGCSServiceServer) Search(context.Context, *SearchOptions) (*SearchGCSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGCSServiceServer) Patch(context.Context, *PatchOptions) (*PatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedGCSServiceServer) mustEmbedUnimplementedGCSServiceServer() {}
func (UnimplementedGCSServiceServer) testEmbeddedByValue()                    {}

// UnsafeGCSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GCSServiceServer will
// result in compilation errors.
type UnsafeGCSServiceServer interface {
	mustEmbedUnimplementedGCSServiceServer()
}

func RegisterGCSServiceServer(s grpc.ServiceRegistrar, srv GCSServiceServer) {
	// If the following call pancis, it indicates UnimplementedGCSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GCSService_ServiceDesc, srv)
}

func _GCSService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GCSServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GCSService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GCSServiceServer).Create(ctx, req.(*GCS))
	}
	return interceptor(ctx, in, info, handler)
}

func _GCSService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GCSServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GCSService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GCSServiceServer).Search(ctx, req.(*SearchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _GCSService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GCSServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GCSService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GCSServiceServer).Patch(ctx, req.(*PatchOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// GCSService_ServiceDesc is the grpc.ServiceDesc for GCSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GCSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.GCSService",
	HandlerType: (*GCSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _GCSService_Create_Handler,
		},
		{
			MethodName: "search",
			Handler:    _GCSService_Search_Handler,
		},
		{
			MethodName: "patch",
			Handler:    _GCSService_Patch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/Gcs.proto",
}
