// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Hub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id"`
	Position      []float64              `protobuf:"fixed64,2,rep,packed,name=Position,proto3" json:"position,omitempty" bson:"position"`
	Users         []*User                `protobuf:"bytes,3,rep,name=Users,proto3" json:"users,omitempty" bson:"users"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"name,omitempty" bson:"name"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"description,omitempty" bson:"description"`
	Lockers       []*Hub                 `protobuf:"bytes,6,rep,name=Lockers,proto3" json:"lockers,omitempty" bson:"lockers"`
	CreatedAt     uint64                 `protobuf:"varint,56,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64                 `protobuf:"varint,57,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string                 `protobuf:"bytes,58,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string                 `protobuf:"bytes,59,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hub) Reset() {
	*x = Hub{}
	mi := &file_pkg_proto_Hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hub) ProtoMessage() {}

func (x *Hub) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hub.ProtoReflect.Descriptor instead.
func (*Hub) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Hub_proto_rawDescGZIP(), []int{0}
}

func (x *Hub) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Hub) GetPosition() []float64 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Hub) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Hub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hub) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hub) GetLockers() []*Hub {
	if x != nil {
		return x.Lockers
	}
	return nil
}

func (x *Hub) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Hub) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Hub) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Hub) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hubs          []*Hub                 `protobuf:"bytes,1,rep,name=Hubs,proto3" json:"Hubs,omitempty"`              //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHubResponse) Reset() {
	*x = SearchHubResponse{}
	mi := &file_pkg_proto_Hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHubResponse) ProtoMessage() {}

func (x *SearchHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHubResponse.ProtoReflect.Descriptor instead.
func (*SearchHubResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Hub_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHubResponse) GetHubs() []*Hub {
	if x != nil {
		return x.Hubs
	}
	return nil
}

func (x *SearchHubResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pkg_proto_Hub_proto protoreflect.FileDescriptor

const file_pkg_proto_Hub_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/Hub.proto\x12\x03hub\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\x1a\x14pkg/proto/User.proto\"\xa5\x02\n" +
	"\x03Hub\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bPosition\x18\x02 \x03(\x01R\bPosition\x12 \n" +
	"\x05Users\x18\x03 \x03(\v2\n" +
	".user.UserR\x05Users\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\"\n" +
	"\aLockers\x18\x06 \x03(\v2\b.hub.HubR\aLockers\x12\x1c\n" +
	"\tCreatedAt\x188 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x189 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x18: \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x18; \x01(\tR\tUpdatedBy\"Q\n" +
	"\x11SearchHubResponse\x12\x1c\n" +
	"\x04Hubs\x18\x01 \x03(\v2\b.hub.HubR\x04Hubs\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount2\xaf\x01\n" +
	"\n" +
	"HubService\x12\x1c\n" +
	"\x06create\x12\b.hub.Hub\x1a\b.hub.Hub\x12?\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x16.hub.SearchHubResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponseB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Hub_proto_rawDescOnce sync.Once
	file_pkg_proto_Hub_proto_rawDescData []byte
)

func file_pkg_proto_Hub_proto_rawDescGZIP() []byte {
	file_pkg_proto_Hub_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Hub_proto_rawDesc), len(file_pkg_proto_Hub_proto_rawDesc)))
	})
	return file_pkg_proto_Hub_proto_rawDescData
}

var file_pkg_proto_Hub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_Hub_proto_goTypes = []any{
	(*Hub)(nil),               // 0: hub.Hub
	(*SearchHubResponse)(nil), // 1: hub.SearchHubResponse
	(*User)(nil),              // 2: user.User
	(*SearchOptions)(nil),     // 3: search_options.SearchOptions
	(*PatchOptions)(nil),      // 4: patch_options.PatchOptions
	(*PatchResponse)(nil),     // 5: patch_options.PatchResponse
}
var file_pkg_proto_Hub_proto_depIdxs = []int32{
	2, // 0: hub.Hub.Users:type_name -> user.User
	0, // 1: hub.Hub.Lockers:type_name -> hub.Hub
	0, // 2: hub.SearchHubResponse.Hubs:type_name -> hub.Hub
	0, // 3: hub.HubService.create:input_type -> hub.Hub
	3, // 4: hub.HubService.search:input_type -> search_options.SearchOptions
	4, // 5: hub.HubService.patch:input_type -> patch_options.PatchOptions
	0, // 6: hub.HubService.create:output_type -> hub.Hub
	1, // 7: hub.HubService.search:output_type -> hub.SearchHubResponse
	5, // 8: hub.HubService.patch:output_type -> patch_options.PatchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_Hub_proto_init() }
func file_pkg_proto_Hub_proto_init() {
	if File_pkg_proto_Hub_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	file_pkg_proto_User_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Hub_proto_rawDesc), len(file_pkg_proto_Hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_Hub_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Hub_proto_depIdxs,
		MessageInfos:      file_pkg_proto_Hub_proto_msgTypes,
	}.Build()
	File_pkg_proto_Hub_proto = out.File
	file_pkg_proto_Hub_proto_goTypes = nil
	file_pkg_proto_Hub_proto_depIdxs = nil
}
