// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/Order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AT_ORDER_STATUS int32

const (
	AT_ORDER_STATUS_AOS_UNKNOWN     AT_ORDER_STATUS = 0
	AT_ORDER_STATUS_AOS_PENDING     AT_ORDER_STATUS = 1
	AT_ORDER_STATUS_AOS_IN_DELIVERY AT_ORDER_STATUS = 2
	AT_ORDER_STATUS_AOS_DELIVERED   AT_ORDER_STATUS = 3
	AT_ORDER_STATUS_AOS_CANCELED    AT_ORDER_STATUS = 4
)

// Enum value maps for AT_ORDER_STATUS.
var (
	AT_ORDER_STATUS_name = map[int32]string{
		0: "AOS_UNKNOWN",
		1: "AOS_PENDING",
		2: "AOS_IN_DELIVERY",
		3: "AOS_DELIVERED",
		4: "AOS_CANCELED",
	}
	AT_ORDER_STATUS_value = map[string]int32{
		"AOS_UNKNOWN":     0,
		"AOS_PENDING":     1,
		"AOS_IN_DELIVERY": 2,
		"AOS_DELIVERED":   3,
		"AOS_CANCELED":    4,
	}
)

func (x AT_ORDER_STATUS) Enum() *AT_ORDER_STATUS {
	p := new(AT_ORDER_STATUS)
	*p = x
	return p
}

func (x AT_ORDER_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_ORDER_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Order_proto_enumTypes[0].Descriptor()
}

func (AT_ORDER_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_Order_proto_enumTypes[0]
}

func (x AT_ORDER_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_ORDER_STATUS.Descriptor instead.
func (AT_ORDER_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{0}
}

type AT_ORDER_SIZE int32

const (
	AT_ORDER_SIZE_AOSZ_UNKNOWN  AT_ORDER_SIZE = 0
	AT_ORDER_SIZE_AOSZ_SMALL    AT_ORDER_SIZE = 1
	AT_ORDER_SIZE_AOSZ_MEDIUM   AT_ORDER_SIZE = 2
	AT_ORDER_SIZE_AOSZ_LARGE    AT_ORDER_SIZE = 3
	AT_ORDER_SIZE_AOSZ_OVERSIZE AT_ORDER_SIZE = 4
)

// Enum value maps for AT_ORDER_SIZE.
var (
	AT_ORDER_SIZE_name = map[int32]string{
		0: "AOSZ_UNKNOWN",
		1: "AOSZ_SMALL",
		2: "AOSZ_MEDIUM",
		3: "AOSZ_LARGE",
		4: "AOSZ_OVERSIZE",
	}
	AT_ORDER_SIZE_value = map[string]int32{
		"AOSZ_UNKNOWN":  0,
		"AOSZ_SMALL":    1,
		"AOSZ_MEDIUM":   2,
		"AOSZ_LARGE":    3,
		"AOSZ_OVERSIZE": 4,
	}
)

func (x AT_ORDER_SIZE) Enum() *AT_ORDER_SIZE {
	p := new(AT_ORDER_SIZE)
	*p = x
	return p
}

func (x AT_ORDER_SIZE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_ORDER_SIZE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Order_proto_enumTypes[1].Descriptor()
}

func (AT_ORDER_SIZE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Order_proto_enumTypes[1]
}

func (x AT_ORDER_SIZE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_ORDER_SIZE.Descriptor instead.
func (AT_ORDER_SIZE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{1}
}

type AT_ORDER_PRORITY int32

const (
	AT_ORDER_PRORITY_AOP_UKNOWN AT_ORDER_PRORITY = 0
	AT_ORDER_PRORITY_AOP_NORMAL AT_ORDER_PRORITY = 1
	AT_ORDER_PRORITY_AOP_HIGH   AT_ORDER_PRORITY = 2
)

// Enum value maps for AT_ORDER_PRORITY.
var (
	AT_ORDER_PRORITY_name = map[int32]string{
		0: "AOP_UKNOWN",
		1: "AOP_NORMAL",
		2: "AOP_HIGH",
	}
	AT_ORDER_PRORITY_value = map[string]int32{
		"AOP_UKNOWN": 0,
		"AOP_NORMAL": 1,
		"AOP_HIGH":   2,
	}
)

func (x AT_ORDER_PRORITY) Enum() *AT_ORDER_PRORITY {
	p := new(AT_ORDER_PRORITY)
	*p = x
	return p
}

func (x AT_ORDER_PRORITY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_ORDER_PRORITY) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Order_proto_enumTypes[2].Descriptor()
}

func (AT_ORDER_PRORITY) Type() protoreflect.EnumType {
	return &file_pkg_proto_Order_proto_enumTypes[2]
}

func (x AT_ORDER_PRORITY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_ORDER_PRORITY.Descriptor instead.
func (AT_ORDER_PRORITY) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{2}
}

type AT_SEGMENT_TYPE int32

const (
	AT_SEGMENT_TYPE_AST_UKNOWN              AT_SEGMENT_TYPE = 0
	AT_SEGMENT_TYPE_AST_PRE_DELIVERY_ROUTE  AT_SEGMENT_TYPE = 1
	AT_SEGMENT_TYPE_AST_IN_DELIVERY_ROUTE   AT_SEGMENT_TYPE = 2
	AT_SEGMENT_TYPE_AST_RETURN_FLIGHT_ROUTE AT_SEGMENT_TYPE = 3
)

// Enum value maps for AT_SEGMENT_TYPE.
var (
	AT_SEGMENT_TYPE_name = map[int32]string{
		0: "AST_UKNOWN",
		1: "AST_PRE_DELIVERY_ROUTE",
		2: "AST_IN_DELIVERY_ROUTE",
		3: "AST_RETURN_FLIGHT_ROUTE",
	}
	AT_SEGMENT_TYPE_value = map[string]int32{
		"AST_UKNOWN":              0,
		"AST_PRE_DELIVERY_ROUTE":  1,
		"AST_IN_DELIVERY_ROUTE":   2,
		"AST_RETURN_FLIGHT_ROUTE": 3,
	}
)

func (x AT_SEGMENT_TYPE) Enum() *AT_SEGMENT_TYPE {
	p := new(AT_SEGMENT_TYPE)
	*p = x
	return p
}

func (x AT_SEGMENT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_SEGMENT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Order_proto_enumTypes[3].Descriptor()
}

func (AT_SEGMENT_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Order_proto_enumTypes[3]
}

func (x AT_SEGMENT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_SEGMENT_TYPE.Descriptor instead.
func (AT_SEGMENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{3}
}

type AT_SEGMENT_STATUS int32

const (
	AT_SEGMENT_STATUS_ASS_UKNOWN     AT_SEGMENT_STATUS = 0
	AT_SEGMENT_STATUS_ASS_UNFINISHED AT_SEGMENT_STATUS = 1
	AT_SEGMENT_STATUS_ASS_FINISHED   AT_SEGMENT_STATUS = 2
)

// Enum value maps for AT_SEGMENT_STATUS.
var (
	AT_SEGMENT_STATUS_name = map[int32]string{
		0: "ASS_UKNOWN",
		1: "ASS_UNFINISHED",
		2: "ASS_FINISHED",
	}
	AT_SEGMENT_STATUS_value = map[string]int32{
		"ASS_UKNOWN":     0,
		"ASS_UNFINISHED": 1,
		"ASS_FINISHED":   2,
	}
)

func (x AT_SEGMENT_STATUS) Enum() *AT_SEGMENT_STATUS {
	p := new(AT_SEGMENT_STATUS)
	*p = x
	return p
}

func (x AT_SEGMENT_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AT_SEGMENT_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Order_proto_enumTypes[4].Descriptor()
}

func (AT_SEGMENT_STATUS) Type() protoreflect.EnumType {
	return &file_pkg_proto_Order_proto_enumTypes[4]
}

func (x AT_SEGMENT_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AT_SEGMENT_STATUS.Descriptor instead.
func (AT_SEGMENT_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{4}
}

type Order struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ID      string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Source  string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"source,omitempty" bson:"source"`
	Dest    string                 `protobuf:"bytes,3,opt,name=Dest,proto3" json:"dest,omitempty" bson:"dest"`
	Status  AT_ORDER_STATUS        `protobuf:"varint,4,opt,name=Status,proto3,enum=order.AT_ORDER_STATUS" json:"order_status,omitempty" bson:"order_status"`
	DroneID string                 `protobuf:"bytes,5,opt,name=DroneID,proto3" json:"drone_id,omitempty" bson:"drone_id"`
	GcsID   string                 `protobuf:"bytes,6,opt,name=GcsID,proto3" json:"gcs_id,omitempty" bson:"gcs_id"`
	// repeated spatial_attribute.GeodeticPositionWithTime FlightRoute  = 7;//`json:"flight_route,omitempty" bson:"flight_route"`
	Segments      []*Segments      `protobuf:"bytes,7,rep,name=Segments,proto3" json:"segments,omitempty" bson:"segments"`
	UserCreateID  string           `protobuf:"bytes,8,opt,name=UserCreateID,proto3" json:"user_create_id,omitempty" bson:"user_create_id"`
	Weight        uint64           `protobuf:"varint,9,opt,name=Weight,proto3" json:"weight,omitempty" bson:"weight"`
	Size          AT_ORDER_SIZE    `protobuf:"varint,10,opt,name=Size,proto3,enum=order.AT_ORDER_SIZE" json:"size,omitempty" bson:"size"`
	Priority      AT_ORDER_PRORITY `protobuf:"varint,11,opt,name=Priority,proto3,enum=order.AT_ORDER_PRORITY" json:"priority,omitempty" bson:"priority"`
	TimeWindow    *TimeWindow      `protobuf:"bytes,12,opt,name=TimeWindow,proto3" json:"time_window,omitempty" bson:"time_window"`
	CorridorID    string           `protobuf:"bytes,13,opt,name=CorridorID,proto3" json:"corridor_id,omitempty" bson:"corridor_id"`
	ETA           uint64           `protobuf:"varint,14,opt,name=ETA,proto3" json:"eta,omitempty" bson:"eta"`
	CreatedAt     uint64           `protobuf:"varint,52,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"  audit:"createdAt"`
	UpdatedAt     uint64           `protobuf:"varint,53,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at"  audit:"updatedAt"`
	CreatedBy     string           `protobuf:"bytes,54,opt,name=CreatedBy,proto3" json:"created_by,omitempty" bson:"created_by"`
	UpdatedBy     string           `protobuf:"bytes,55,opt,name=UpdatedBy,proto3" json:"updated_by,omitempty" bson:"updated_by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pkg_proto_Order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Order) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Order) GetStatus() AT_ORDER_STATUS {
	if x != nil {
		return x.Status
	}
	return AT_ORDER_STATUS_AOS_UNKNOWN
}

func (x *Order) GetDroneID() string {
	if x != nil {
		return x.DroneID
	}
	return ""
}

func (x *Order) GetGcsID() string {
	if x != nil {
		return x.GcsID
	}
	return ""
}

func (x *Order) GetSegments() []*Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Order) GetUserCreateID() string {
	if x != nil {
		return x.UserCreateID
	}
	return ""
}

func (x *Order) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetSize() AT_ORDER_SIZE {
	if x != nil {
		return x.Size
	}
	return AT_ORDER_SIZE_AOSZ_UNKNOWN
}

func (x *Order) GetPriority() AT_ORDER_PRORITY {
	if x != nil {
		return x.Priority
	}
	return AT_ORDER_PRORITY_AOP_UKNOWN
}

func (x *Order) GetTimeWindow() *TimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

func (x *Order) GetCorridorID() string {
	if x != nil {
		return x.CorridorID
	}
	return ""
}

func (x *Order) GetETA() uint64 {
	if x != nil {
		return x.ETA
	}
	return 0
}

func (x *Order) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Order) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Order) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SearchOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         []*Order               `protobuf:"bytes,1,rep,name=Order,proto3" json:"Order,omitempty"`            //
	TotalCount    int32                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrderResponse) Reset() {
	*x = SearchOrderResponse{}
	mi := &file_pkg_proto_Order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrderResponse) ProtoMessage() {}

func (x *SearchOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrderResponse.ProtoReflect.Descriptor instead.
func (*SearchOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{1}
}

func (x *SearchOrderResponse) GetOrder() []*Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SearchOrderResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=StartTime,proto3" json:"start_time,omitempty" bson:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=EndTime,proto3" json:"end_time,omitempty" bson:"end_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_pkg_proto_Order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{2}
}

func (x *TimeWindow) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeWindow) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type Segments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentIndex  int32                  `protobuf:"varint,1,opt,name=SegmentIndex,proto3" json:"segment_index,omitempty" bson:"segment_index,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"source,omitempty" bson:"source"`
	Dest          string                 `protobuf:"bytes,3,opt,name=Dest,proto3" json:"dest,omitempty" bson:"dest"`
	FlightLaneID  string                 `protobuf:"bytes,4,opt,name=FlightLaneID,proto3" json:"flight_lane_id,omitempty" bson:"flight_lane_id"`
	SegmentStatus AT_SEGMENT_STATUS      `protobuf:"varint,5,opt,name=SegmentStatus,proto3,enum=order.AT_SEGMENT_STATUS" json:"segment_status,omitempty" bson:"segment_status"`
	SegmentType   AT_SEGMENT_TYPE        `protobuf:"varint,6,opt,name=SegmentType,proto3,enum=order.AT_SEGMENT_TYPE" json:"segment_type,omitempty" bson:"segment_type"`
	DroneID       string                 `protobuf:"bytes,7,opt,name=DroneID,proto3" json:"drone_id,omitempty" bson:"drone_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segments) Reset() {
	*x = Segments{}
	mi := &file_pkg_proto_Order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segments) ProtoMessage() {}

func (x *Segments) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segments.ProtoReflect.Descriptor instead.
func (*Segments) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Order_proto_rawDescGZIP(), []int{3}
}

func (x *Segments) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *Segments) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Segments) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Segments) GetFlightLaneID() string {
	if x != nil {
		return x.FlightLaneID
	}
	return ""
}

func (x *Segments) GetSegmentStatus() AT_SEGMENT_STATUS {
	if x != nil {
		return x.SegmentStatus
	}
	return AT_SEGMENT_STATUS_ASS_UKNOWN
}

func (x *Segments) GetSegmentType() AT_SEGMENT_TYPE {
	if x != nil {
		return x.SegmentType
	}
	return AT_SEGMENT_TYPE_AST_UKNOWN
}

func (x *Segments) GetDroneID() string {
	if x != nil {
		return x.DroneID
	}
	return ""
}

var File_pkg_proto_Order_proto protoreflect.FileDescriptor

const file_pkg_proto_Order_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/Order.proto\x12\x05order\x1a\x1dpkg/proto/SearchOptions.proto\x1a\x1cpkg/proto/PatchOptions.proto\"\xc8\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\x12\x12\n" +
	"\x04Dest\x18\x03 \x01(\tR\x04Dest\x12.\n" +
	"\x06Status\x18\x04 \x01(\x0e2\x16.order.AT_ORDER_STATUSR\x06Status\x12\x18\n" +
	"\aDroneID\x18\x05 \x01(\tR\aDroneID\x12\x14\n" +
	"\x05GcsID\x18\x06 \x01(\tR\x05GcsID\x12+\n" +
	"\bSegments\x18\a \x03(\v2\x0f.order.SegmentsR\bSegments\x12\"\n" +
	"\fUserCreateID\x18\b \x01(\tR\fUserCreateID\x12\x16\n" +
	"\x06Weight\x18\t \x01(\x04R\x06Weight\x12(\n" +
	"\x04Size\x18\n" +
	" \x01(\x0e2\x14.order.AT_ORDER_SIZER\x04Size\x123\n" +
	"\bPriority\x18\v \x01(\x0e2\x17.order.AT_ORDER_PRORITYR\bPriority\x121\n" +
	"\n" +
	"TimeWindow\x18\f \x01(\v2\x11.order.TimeWindowR\n" +
	"TimeWindow\x12\x1e\n" +
	"\n" +
	"CorridorID\x18\r \x01(\tR\n" +
	"CorridorID\x12\x10\n" +
	"\x03ETA\x18\x0e \x01(\x04R\x03ETA\x12\x1c\n" +
	"\tCreatedAt\x184 \x01(\x04R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x185 \x01(\x04R\tUpdatedAt\x12\x1c\n" +
	"\tCreatedBy\x186 \x01(\tR\tCreatedBy\x12\x1c\n" +
	"\tUpdatedBy\x187 \x01(\tR\tUpdatedBy\"Y\n" +
	"\x13SearchOrderResponse\x12\"\n" +
	"\x05Order\x18\x01 \x03(\v2\f.order.OrderR\x05Order\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x05R\n" +
	"TotalCount\"D\n" +
	"\n" +
	"TimeWindow\x12\x1c\n" +
	"\tStartTime\x18\x01 \x01(\x03R\tStartTime\x12\x18\n" +
	"\aEndTime\x18\x02 \x01(\x03R\aEndTime\"\x92\x02\n" +
	"\bSegments\x12\"\n" +
	"\fSegmentIndex\x18\x01 \x01(\x05R\fSegmentIndex\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\x12\x12\n" +
	"\x04Dest\x18\x03 \x01(\tR\x04Dest\x12\"\n" +
	"\fFlightLaneID\x18\x04 \x01(\tR\fFlightLaneID\x12>\n" +
	"\rSegmentStatus\x18\x05 \x01(\x0e2\x18.order.AT_SEGMENT_STATUSR\rSegmentStatus\x128\n" +
	"\vSegmentType\x18\x06 \x01(\x0e2\x16.order.AT_SEGMENT_TYPER\vSegmentType\x12\x18\n" +
	"\aDroneID\x18\a \x01(\tR\aDroneID*m\n" +
	"\x0fAT_ORDER_STATUS\x12\x0f\n" +
	"\vAOS_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vAOS_PENDING\x10\x01\x12\x13\n" +
	"\x0fAOS_IN_DELIVERY\x10\x02\x12\x11\n" +
	"\rAOS_DELIVERED\x10\x03\x12\x10\n" +
	"\fAOS_CANCELED\x10\x04*e\n" +
	"\rAT_ORDER_SIZE\x12\x10\n" +
	"\fAOSZ_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"AOSZ_SMALL\x10\x01\x12\x0f\n" +
	"\vAOSZ_MEDIUM\x10\x02\x12\x0e\n" +
	"\n" +
	"AOSZ_LARGE\x10\x03\x12\x11\n" +
	"\rAOSZ_OVERSIZE\x10\x04*@\n" +
	"\x10AT_ORDER_PRORITY\x12\x0e\n" +
	"\n" +
	"AOP_UKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"AOP_NORMAL\x10\x01\x12\f\n" +
	"\bAOP_HIGH\x10\x02*u\n" +
	"\x0fAT_SEGMENT_TYPE\x12\x0e\n" +
	"\n" +
	"AST_UKNOWN\x10\x00\x12\x1a\n" +
	"\x16AST_PRE_DELIVERY_ROUTE\x10\x01\x12\x19\n" +
	"\x15AST_IN_DELIVERY_ROUTE\x10\x02\x12\x1b\n" +
	"\x17AST_RETURN_FLIGHT_ROUTE\x10\x03*I\n" +
	"\x11AT_SEGMENT_STATUS\x12\x0e\n" +
	"\n" +
	"ASS_UKNOWN\x10\x00\x12\x12\n" +
	"\x0eASS_UNFINISHED\x10\x01\x12\x10\n" +
	"\fASS_FINISHED\x10\x022\xe3\x01\n" +
	"\fOrderService\x12$\n" +
	"\x06create\x12\f.order.Order\x1a\f.order.Order\x12C\n" +
	"\x06search\x12\x1d.search_options.SearchOptions\x1a\x1a.order.SearchOrderResponse\x12B\n" +
	"\x05patch\x12\x1b.patch_options.PatchOptions\x1a\x1c.patch_options.PatchResponse\x12$\n" +
	"\x06update\x12\f.order.Order\x1a\f.order.OrderB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_Order_proto_rawDescOnce sync.Once
	file_pkg_proto_Order_proto_rawDescData []byte
)

func file_pkg_proto_Order_proto_rawDescGZIP() []byte {
	file_pkg_proto_Order_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_Order_proto_rawDesc), len(file_pkg_proto_Order_proto_rawDesc)))
	})
	return file_pkg_proto_Order_proto_rawDescData
}

var file_pkg_proto_Order_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pkg_proto_Order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_Order_proto_goTypes = []any{
	(AT_ORDER_STATUS)(0),        // 0: order.AT_ORDER_STATUS
	(AT_ORDER_SIZE)(0),          // 1: order.AT_ORDER_SIZE
	(AT_ORDER_PRORITY)(0),       // 2: order.AT_ORDER_PRORITY
	(AT_SEGMENT_TYPE)(0),        // 3: order.AT_SEGMENT_TYPE
	(AT_SEGMENT_STATUS)(0),      // 4: order.AT_SEGMENT_STATUS
	(*Order)(nil),               // 5: order.Order
	(*SearchOrderResponse)(nil), // 6: order.SearchOrderResponse
	(*TimeWindow)(nil),          // 7: order.TimeWindow
	(*Segments)(nil),            // 8: order.Segments
	(*SearchOptions)(nil),       // 9: search_options.SearchOptions
	(*PatchOptions)(nil),        // 10: patch_options.PatchOptions
	(*PatchResponse)(nil),       // 11: patch_options.PatchResponse
}
var file_pkg_proto_Order_proto_depIdxs = []int32{
	0,  // 0: order.Order.Status:type_name -> order.AT_ORDER_STATUS
	8,  // 1: order.Order.Segments:type_name -> order.Segments
	1,  // 2: order.Order.Size:type_name -> order.AT_ORDER_SIZE
	2,  // 3: order.Order.Priority:type_name -> order.AT_ORDER_PRORITY
	7,  // 4: order.Order.TimeWindow:type_name -> order.TimeWindow
	5,  // 5: order.SearchOrderResponse.Order:type_name -> order.Order
	4,  // 6: order.Segments.SegmentStatus:type_name -> order.AT_SEGMENT_STATUS
	3,  // 7: order.Segments.SegmentType:type_name -> order.AT_SEGMENT_TYPE
	5,  // 8: order.OrderService.create:input_type -> order.Order
	9,  // 9: order.OrderService.search:input_type -> search_options.SearchOptions
	10, // 10: order.OrderService.patch:input_type -> patch_options.PatchOptions
	5,  // 11: order.OrderService.update:input_type -> order.Order
	5,  // 12: order.OrderService.create:output_type -> order.Order
	6,  // 13: order.OrderService.search:output_type -> order.SearchOrderResponse
	11, // 14: order.OrderService.patch:output_type -> patch_options.PatchResponse
	5,  // 15: order.OrderService.update:output_type -> order.Order
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_proto_Order_proto_init() }
func file_pkg_proto_Order_proto_init() {
	if File_pkg_proto_Order_proto != nil {
		return
	}
	file_pkg_proto_SearchOptions_proto_init()
	file_pkg_proto_PatchOptions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_Order_proto_rawDesc), len(file_pkg_proto_Order_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_Order_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Order_proto_depIdxs,
		EnumInfos:         file_pkg_proto_Order_proto_enumTypes,
		MessageInfos:      file_pkg_proto_Order_proto_msgTypes,
	}.Build()
	File_pkg_proto_Order_proto = out.File
	file_pkg_proto_Order_proto_goTypes = nil
	file_pkg_proto_Order_proto_depIdxs = nil
}
