// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/PatchOptions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatchOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operations is the field for json bytes of the Patch according to the standard of JSON Patch https://jsonpatch.com/
	// Use the libraries for param data then encode it as byte array
	Operations    []byte `protobuf:"bytes,1,opt,name=Operations,proto3" json:"Operations,omitempty"` //`json:"operations"`
	ID            string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`                 //`json:"id,omitempty" bson:"_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOptions) Reset() {
	*x = PatchOptions{}
	mi := &file_pkg_proto_PatchOptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOptions) ProtoMessage() {}

func (x *PatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_PatchOptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOptions.ProtoReflect.Descriptor instead.
func (*PatchOptions) Descriptor() ([]byte, []int) {
	return file_pkg_proto_PatchOptions_proto_rawDescGZIP(), []int{0}
}

func (x *PatchOptions) GetOperations() []byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *PatchOptions) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type PatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`      //
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchResponse) Reset() {
	*x = PatchResponse{}
	mi := &file_pkg_proto_PatchOptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchResponse) ProtoMessage() {}

func (x *PatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_PatchOptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchResponse.ProtoReflect.Descriptor instead.
func (*PatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_PatchOptions_proto_rawDescGZIP(), []int{1}
}

func (x *PatchResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *PatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_PatchOptions_proto protoreflect.FileDescriptor

const file_pkg_proto_PatchOptions_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/PatchOptions.proto\x12\rpatch_options\">\n" +
	"\fPatchOptions\x12\x1e\n" +
	"\n" +
	"Operations\x18\x01 \x01(\fR\n" +
	"Operations\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\"=\n" +
	"\rPatchResponse\x12\x12\n" +
	"\x04IsOk\x18\x01 \x01(\bR\x04IsOk\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessageB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_PatchOptions_proto_rawDescOnce sync.Once
	file_pkg_proto_PatchOptions_proto_rawDescData []byte
)

func file_pkg_proto_PatchOptions_proto_rawDescGZIP() []byte {
	file_pkg_proto_PatchOptions_proto_rawDescOnce.Do(func() {
		file_pkg_proto_PatchOptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_PatchOptions_proto_rawDesc), len(file_pkg_proto_PatchOptions_proto_rawDesc)))
	})
	return file_pkg_proto_PatchOptions_proto_rawDescData
}

var file_pkg_proto_PatchOptions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_PatchOptions_proto_goTypes = []any{
	(*PatchOptions)(nil),  // 0: patch_options.PatchOptions
	(*PatchResponse)(nil), // 1: patch_options.PatchResponse
}
var file_pkg_proto_PatchOptions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_PatchOptions_proto_init() }
func file_pkg_proto_PatchOptions_proto_init() {
	if File_pkg_proto_PatchOptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_PatchOptions_proto_rawDesc), len(file_pkg_proto_PatchOptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_PatchOptions_proto_goTypes,
		DependencyIndexes: file_pkg_proto_PatchOptions_proto_depIdxs,
		MessageInfos:      file_pkg_proto_PatchOptions_proto_msgTypes,
	}.Build()
	File_pkg_proto_PatchOptions_proto = out.File
	file_pkg_proto_PatchOptions_proto_goTypes = nil
	file_pkg_proto_PatchOptions_proto_depIdxs = nil
}
