// Code generated by custom.generate.sh.
// source: pkg/pb/*.proto
// template: pkg/custom.template
// DO NOT EDIT!
package pb

import (
	"reflect"

	"github.com/nguyenngodinh/qmgo/field"
)
const AUDIT_USER = "X-Username"

func (c *LoginInfo) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(LoginInfo{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *AuthUser) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(AuthUser{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchAuthUserResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchAuthUserResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Command) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Command{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchCommandResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchCommandResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *DirectCommand) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(DirectCommand{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchDirectCommandResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchDirectCommandResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Drone) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Drone{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchDroneResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchDroneResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *TrackHistory) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(TrackHistory{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Location) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Location{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchTrackHistoryResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchTrackHistoryResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *ObjectTrack) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(ObjectTrack{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchObjectTrackResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchObjectTrackResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *EventRoutingKey) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(EventRoutingKey{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SocketEvent) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SocketEvent{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *AlgoRequest) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(AlgoRequest{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *AlgoOptimizeResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(AlgoOptimizeResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *DroneWithCurrentFlightLane) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(DroneWithCurrentFlightLane{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *UFOMessage) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(UFOMessage{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *ActiveDrone) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(ActiveDrone{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *ToDeliverDrone) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(ToDeliverDrone{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *AlertRequest) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(AlertRequest{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *AlertResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(AlertResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *FlightArea) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(FlightArea{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchFlightAreaResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchFlightAreaResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *FlightCorridor) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(FlightCorridor{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchFlightCorridorResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchFlightCorridorResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *FlightLane) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(FlightLane{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchFlightLaneResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchFlightLaneResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *GCS) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(GCS{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchGCSResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchGCSResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Hub) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Hub{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchHubResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchHubResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Order) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Order{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchOrderResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchOrderResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *TimeWindow) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(TimeWindow{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *Segments) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(Segments{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *PatchOptions) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(PatchOptions{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *PatchResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(PatchResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *GeodeticPosition) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(GeodeticPosition{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *GeographicPosition) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(GeographicPosition{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *GeodeticPositionWithTimeAndVelocity) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(GeodeticPositionWithTimeAndVelocity{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *CartesianVelocity) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(CartesianVelocity{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *CartesianPosition) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(CartesianPosition{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *PolarPosition) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(PolarPosition{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *PolarVelocity) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(PolarVelocity{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *User) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(User{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}

func (c *SearchUserResponse) CustomFields() field.CustomFieldsBuilder {
	rType := reflect.TypeOf(SearchUserResponse{})
	custom := field.NewCustom()
	for i := 0; i < rType.NumField(); i++ {
		field := rType.Field(i)
		tag := field.Tag
		auditTag := tag.Get("audit")
		if auditTag == "createdAt" {
			custom.SetCreateAt(field.Name)
		}
		if auditTag == "updatedAt" {
			custom.SetUpdateAt(field.Name)
		}
		if auditTag == "ID" {
			custom.SetId(field.Name)
		}
		if auditTag == "updatedBy" {
			custom.SetUpdateBy(field.Name, AUDIT_USER)
		}
		if auditTag == "createdBy" {
			custom.SetCreateBy(field.Name, AUDIT_USER)
		}
	}
	return custom
}
