// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/SearchOptions.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`                                                                           //`json:"fields,omitempty"`
	Filter        map[string]*StringList `protobuf:"bytes,2,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //`json:"filter,omitempty"`
	Page          map[string]int32       `protobuf:"bytes,3,rep,name=Page,proto3" json:"Page,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    //`json:"page" validate:"required"`
	Sorts         []string               `protobuf:"bytes,4,rep,name=Sorts,proto3" json:"Sorts,omitempty"`                                                                             //`json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOptions) Reset() {
	*x = SearchOptions{}
	mi := &file_pkg_proto_SearchOptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOptions) ProtoMessage() {}

func (x *SearchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SearchOptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOptions.ProtoReflect.Descriptor instead.
func (*SearchOptions) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SearchOptions_proto_rawDescGZIP(), []int{0}
}

func (x *SearchOptions) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchOptions) GetFilter() map[string]*StringList {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SearchOptions) GetPage() map[string]int32 {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *SearchOptions) GetSorts() []string {
	if x != nil {
		return x.Sorts
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           []string               `protobuf:"bytes,1,rep,name=Str,proto3" json:"Str,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_pkg_proto_SearchOptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SearchOptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SearchOptions_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetStr() []string {
	if x != nil {
		return x.Str
	}
	return nil
}

var File_pkg_proto_SearchOptions_proto protoreflect.FileDescriptor

const file_pkg_proto_SearchOptions_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/SearchOptions.proto\x12\x0esearch_options\"\xcd\x02\n" +
	"\rSearchOptions\x12\x16\n" +
	"\x06Fields\x18\x01 \x03(\tR\x06Fields\x12A\n" +
	"\x06Filter\x18\x02 \x03(\v2).search_options.SearchOptions.FilterEntryR\x06Filter\x12;\n" +
	"\x04Page\x18\x03 \x03(\v2'.search_options.SearchOptions.PageEntryR\x04Page\x12\x14\n" +
	"\x05Sorts\x18\x04 \x03(\tR\x05Sorts\x1aU\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.search_options.StringListR\x05value:\x028\x01\x1a7\n" +
	"\tPageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x1e\n" +
	"\n" +
	"StringList\x12\x10\n" +
	"\x03Str\x18\x01 \x03(\tR\x03StrB\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_SearchOptions_proto_rawDescOnce sync.Once
	file_pkg_proto_SearchOptions_proto_rawDescData []byte
)

func file_pkg_proto_SearchOptions_proto_rawDescGZIP() []byte {
	file_pkg_proto_SearchOptions_proto_rawDescOnce.Do(func() {
		file_pkg_proto_SearchOptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_SearchOptions_proto_rawDesc), len(file_pkg_proto_SearchOptions_proto_rawDesc)))
	})
	return file_pkg_proto_SearchOptions_proto_rawDescData
}

var file_pkg_proto_SearchOptions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_SearchOptions_proto_goTypes = []any{
	(*SearchOptions)(nil), // 0: search_options.SearchOptions
	(*StringList)(nil),    // 1: search_options.StringList
	nil,                   // 2: search_options.SearchOptions.FilterEntry
	nil,                   // 3: search_options.SearchOptions.PageEntry
}
var file_pkg_proto_SearchOptions_proto_depIdxs = []int32{
	2, // 0: search_options.SearchOptions.Filter:type_name -> search_options.SearchOptions.FilterEntry
	3, // 1: search_options.SearchOptions.Page:type_name -> search_options.SearchOptions.PageEntry
	1, // 2: search_options.SearchOptions.FilterEntry.value:type_name -> search_options.StringList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_SearchOptions_proto_init() }
func file_pkg_proto_SearchOptions_proto_init() {
	if File_pkg_proto_SearchOptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_SearchOptions_proto_rawDesc), len(file_pkg_proto_SearchOptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_SearchOptions_proto_goTypes,
		DependencyIndexes: file_pkg_proto_SearchOptions_proto_depIdxs,
		MessageInfos:      file_pkg_proto_SearchOptions_proto_msgTypes,
	}.Build()
	File_pkg_proto_SearchOptions_proto = out.File
	file_pkg_proto_SearchOptions_proto_goTypes = nil
	file_pkg_proto_SearchOptions_proto_depIdxs = nil
}
