// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/SpatialAttribute.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dimension int32

const (
	Dimension_DIMENSION_2D Dimension = 0
	Dimension_DIMENSION_3D Dimension = 1
)

// Enum value maps for Dimension.
var (
	Dimension_name = map[int32]string{
		0: "DIMENSION_2D",
		1: "DIMENSION_3D",
	}
	Dimension_value = map[string]int32{
		"DIMENSION_2D": 0,
		"DIMENSION_3D": 1,
	}
)

func (x Dimension) Enum() *Dimension {
	p := new(Dimension)
	*p = x
	return p
}

func (x Dimension) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dimension) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_SpatialAttribute_proto_enumTypes[0].Descriptor()
}

func (Dimension) Type() protoreflect.EnumType {
	return &file_pkg_proto_SpatialAttribute_proto_enumTypes[0]
}

func (x Dimension) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dimension.Descriptor instead.
func (Dimension) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{0}
}

type GeodeticPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float32                `protobuf:"fixed32,1,opt,name=Longitude,proto3" json:"longitude" bson:"longitude" validate:"gte=-180,lte=180"`
	Latitude      float32                `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"latitude" bson:"latitude" validate:"gte=-90,lte=90.0"`
	Altitude      float32                `protobuf:"fixed32,3,opt,name=Altitude,proto3" json:"altitude" bson:"altitude" validate:"gte=0,lte=99999"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeodeticPosition) Reset() {
	*x = GeodeticPosition{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeodeticPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeodeticPosition) ProtoMessage() {}

func (x *GeodeticPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeodeticPosition.ProtoReflect.Descriptor instead.
func (*GeodeticPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{0}
}

func (x *GeodeticPosition) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeodeticPosition) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeodeticPosition) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type GeographicPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float32                `protobuf:"fixed32,1,opt,name=Longitude,proto3" json:"longitude" bson:"longitude" validate:"gte=-180,lte=180"`
	Latitude      float32                `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"latitude" bson:"latitude" validate:"gte=-90,lte=90.0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeographicPosition) Reset() {
	*x = GeographicPosition{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeographicPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeographicPosition) ProtoMessage() {}

func (x *GeographicPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeographicPosition.ProtoReflect.Descriptor instead.
func (*GeographicPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{1}
}

func (x *GeographicPosition) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeographicPosition) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type GeodeticPositionWithTimeAndVelocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float32                `protobuf:"fixed32,1,opt,name=Longitude,proto3" json:"longitude" bson:"longitude" validate:"gte=-180,lte=180"`
	Latitude      float32                `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"latitude" bson:"latitude" validate:"gte=-90,lte=90.0"`
	Altitude      float32                `protobuf:"fixed32,3,opt,name=Altitude,proto3" json:"altitude" bson:"altitude" validate:"gte=0,lte=99999"`
	PolarVelocity *PolarVelocity         `protobuf:"bytes,4,opt,name=PolarVelocity,proto3" json:"polar_velocity" bson:"polar_velocity" validate:"gte=0,lte=99999"`
	EstimateTime  float32                `protobuf:"fixed32,5,opt,name=EstimateTime,proto3" json:"eta" bson:"eta" validate:"gte=0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeodeticPositionWithTimeAndVelocity) Reset() {
	*x = GeodeticPositionWithTimeAndVelocity{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeodeticPositionWithTimeAndVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeodeticPositionWithTimeAndVelocity) ProtoMessage() {}

func (x *GeodeticPositionWithTimeAndVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeodeticPositionWithTimeAndVelocity.ProtoReflect.Descriptor instead.
func (*GeodeticPositionWithTimeAndVelocity) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{2}
}

func (x *GeodeticPositionWithTimeAndVelocity) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeodeticPositionWithTimeAndVelocity) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeodeticPositionWithTimeAndVelocity) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *GeodeticPositionWithTimeAndVelocity) GetPolarVelocity() *PolarVelocity {
	if x != nil {
		return x.PolarVelocity
	}
	return nil
}

func (x *GeodeticPositionWithTimeAndVelocity) GetEstimateTime() float32 {
	if x != nil {
		return x.EstimateTime
	}
	return 0
}

type CartesianVelocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vx            float32                `protobuf:"fixed32,1,opt,name=Vx,proto3" json:"vx" bson:"vx"`
	Vy            float32                `protobuf:"fixed32,2,opt,name=Vy,proto3" json:"vy" bson:"vy"`
	Vz            float32                `protobuf:"fixed32,3,opt,name=Vz,proto3" json:"vz" bson:"vz"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartesianVelocity) Reset() {
	*x = CartesianVelocity{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartesianVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartesianVelocity) ProtoMessage() {}

func (x *CartesianVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartesianVelocity.ProtoReflect.Descriptor instead.
func (*CartesianVelocity) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{3}
}

func (x *CartesianVelocity) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *CartesianVelocity) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *CartesianVelocity) GetVz() float32 {
	if x != nil {
		return x.Vz
	}
	return 0
}

type CartesianPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,opt,name=x,proto3,oneof" json:"x,omitempty"` //meter
	Y             *float32               `protobuf:"fixed32,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Z             *float32               `protobuf:"fixed32,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartesianPosition) Reset() {
	*x = CartesianPosition{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartesianPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartesianPosition) ProtoMessage() {}

func (x *CartesianPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartesianPosition.ProtoReflect.Descriptor instead.
func (*CartesianPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{4}
}

func (x *CartesianPosition) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *CartesianPosition) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *CartesianPosition) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type PolarPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *float32               `protobuf:"fixed32,1,opt,name=range,proto3,oneof" json:"range,omitempty"`         //meter
	Azimuth       *float32               `protobuf:"fixed32,2,opt,name=azimuth,proto3,oneof" json:"azimuth,omitempty"`     //radian
	Elevation     *float32               `protobuf:"fixed32,3,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"` //meter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolarPosition) Reset() {
	*x = PolarPosition{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolarPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarPosition) ProtoMessage() {}

func (x *PolarPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarPosition.ProtoReflect.Descriptor instead.
func (*PolarPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{5}
}

func (x *PolarPosition) GetRange() float32 {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return 0
}

func (x *PolarPosition) GetAzimuth() float32 {
	if x != nil && x.Azimuth != nil {
		return *x.Azimuth
	}
	return 0
}

func (x *PolarPosition) GetElevation() float32 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

type PolarVelocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         *float32               `protobuf:"fixed32,1,opt,name=speed,proto3,oneof" json:"speed,omitempty"`     //m/s
	Heading       *float32               `protobuf:"fixed32,2,opt,name=heading,proto3,oneof" json:"heading,omitempty"` //radian
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolarVelocity) Reset() {
	*x = PolarVelocity{}
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolarVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarVelocity) ProtoMessage() {}

func (x *PolarVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_SpatialAttribute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarVelocity.ProtoReflect.Descriptor instead.
func (*PolarVelocity) Descriptor() ([]byte, []int) {
	return file_pkg_proto_SpatialAttribute_proto_rawDescGZIP(), []int{6}
}

func (x *PolarVelocity) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *PolarVelocity) GetHeading() float32 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

var File_pkg_proto_SpatialAttribute_proto protoreflect.FileDescriptor

const file_pkg_proto_SpatialAttribute_proto_rawDesc = "" +
	"\n" +
	" pkg/proto/SpatialAttribute.proto\x12\x11spatial_attribute\"h\n" +
	"\x10GeodeticPosition\x12\x1c\n" +
	"\tLongitude\x18\x01 \x01(\x02R\tLongitude\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x02R\bLatitude\x12\x1a\n" +
	"\bAltitude\x18\x03 \x01(\x02R\bAltitude\"N\n" +
	"\x12GeographicPosition\x12\x1c\n" +
	"\tLongitude\x18\x01 \x01(\x02R\tLongitude\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x02R\bLatitude\"\xe7\x01\n" +
	"#GeodeticPositionWithTimeAndVelocity\x12\x1c\n" +
	"\tLongitude\x18\x01 \x01(\x02R\tLongitude\x12\x1a\n" +
	"\bLatitude\x18\x02 \x01(\x02R\bLatitude\x12\x1a\n" +
	"\bAltitude\x18\x03 \x01(\x02R\bAltitude\x12F\n" +
	"\rPolarVelocity\x18\x04 \x01(\v2 .spatial_attribute.PolarVelocityR\rPolarVelocity\x12\"\n" +
	"\fEstimateTime\x18\x05 \x01(\x02R\fEstimateTime\"C\n" +
	"\x11CartesianVelocity\x12\x0e\n" +
	"\x02Vx\x18\x01 \x01(\x02R\x02Vx\x12\x0e\n" +
	"\x02Vy\x18\x02 \x01(\x02R\x02Vy\x12\x0e\n" +
	"\x02Vz\x18\x03 \x01(\x02R\x02Vz\"^\n" +
	"\x11CartesianPosition\x12\x11\n" +
	"\x01x\x18\x01 \x01(\x02H\x00R\x01x\x88\x01\x01\x12\x11\n" +
	"\x01y\x18\x02 \x01(\x02H\x01R\x01y\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x02H\x02R\x01z\x88\x01\x01B\x04\n" +
	"\x02_xB\x04\n" +
	"\x02_yB\x04\n" +
	"\x02_z\"\x90\x01\n" +
	"\rPolarPosition\x12\x19\n" +
	"\x05range\x18\x01 \x01(\x02H\x00R\x05range\x88\x01\x01\x12\x1d\n" +
	"\aazimuth\x18\x02 \x01(\x02H\x01R\aazimuth\x88\x01\x01\x12!\n" +
	"\televation\x18\x03 \x01(\x02H\x02R\televation\x88\x01\x01B\b\n" +
	"\x06_rangeB\n" +
	"\n" +
	"\b_azimuthB\f\n" +
	"\n" +
	"_elevation\"_\n" +
	"\rPolarVelocity\x12\x19\n" +
	"\x05speed\x18\x01 \x01(\x02H\x00R\x05speed\x88\x01\x01\x12\x1d\n" +
	"\aheading\x18\x02 \x01(\x02H\x01R\aheading\x88\x01\x01B\b\n" +
	"\x06_speedB\n" +
	"\n" +
	"\b_heading*/\n" +
	"\tDimension\x12\x10\n" +
	"\fDIMENSION_2D\x10\x00\x12\x10\n" +
	"\fDIMENSION_3D\x10\x01B\bZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_proto_SpatialAttribute_proto_rawDescOnce sync.Once
	file_pkg_proto_SpatialAttribute_proto_rawDescData []byte
)

func file_pkg_proto_SpatialAttribute_proto_rawDescGZIP() []byte {
	file_pkg_proto_SpatialAttribute_proto_rawDescOnce.Do(func() {
		file_pkg_proto_SpatialAttribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_SpatialAttribute_proto_rawDesc), len(file_pkg_proto_SpatialAttribute_proto_rawDesc)))
	})
	return file_pkg_proto_SpatialAttribute_proto_rawDescData
}

var file_pkg_proto_SpatialAttribute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_SpatialAttribute_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_SpatialAttribute_proto_goTypes = []any{
	(Dimension)(0),                              // 0: spatial_attribute.Dimension
	(*GeodeticPosition)(nil),                    // 1: spatial_attribute.GeodeticPosition
	(*GeographicPosition)(nil),                  // 2: spatial_attribute.GeographicPosition
	(*GeodeticPositionWithTimeAndVelocity)(nil), // 3: spatial_attribute.GeodeticPositionWithTimeAndVelocity
	(*CartesianVelocity)(nil),                   // 4: spatial_attribute.CartesianVelocity
	(*CartesianPosition)(nil),                   // 5: spatial_attribute.CartesianPosition
	(*PolarPosition)(nil),                       // 6: spatial_attribute.PolarPosition
	(*PolarVelocity)(nil),                       // 7: spatial_attribute.PolarVelocity
}
var file_pkg_proto_SpatialAttribute_proto_depIdxs = []int32{
	7, // 0: spatial_attribute.GeodeticPositionWithTimeAndVelocity.PolarVelocity:type_name -> spatial_attribute.PolarVelocity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_SpatialAttribute_proto_init() }
func file_pkg_proto_SpatialAttribute_proto_init() {
	if File_pkg_proto_SpatialAttribute_proto != nil {
		return
	}
	file_pkg_proto_SpatialAttribute_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_proto_SpatialAttribute_proto_msgTypes[5].OneofWrappers = []any{}
	file_pkg_proto_SpatialAttribute_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_SpatialAttribute_proto_rawDesc), len(file_pkg_proto_SpatialAttribute_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_SpatialAttribute_proto_goTypes,
		DependencyIndexes: file_pkg_proto_SpatialAttribute_proto_depIdxs,
		EnumInfos:         file_pkg_proto_SpatialAttribute_proto_enumTypes,
		MessageInfos:      file_pkg_proto_SpatialAttribute_proto_msgTypes,
	}.Build()
	File_pkg_proto_SpatialAttribute_proto = out.File
	file_pkg_proto_SpatialAttribute_proto_goTypes = nil
	file_pkg_proto_SpatialAttribute_proto_depIdxs = nil
}
