// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/ipc/TrackMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	SourceType    *SourceType            `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=com.vht.bms.messages.SourceType,oneof" json:"source_type,omitempty"` // Refer to SourceType in TrackInfoEnum.proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{0}
}

func (x *SourceInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SourceInfo) GetSourceType() SourceType {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNKNOWN
}

type TrackMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	SourceInfo           *SourceInfo            `protobuf:"bytes,2,opt,name=source_info,json=sourceInfo,proto3" json:"source_info,omitempty"`
	TrackInfo            *TrackInfo             `protobuf:"bytes,4,opt,name=track_info,json=trackInfo,proto3" json:"track_info,omitempty"`
	GeodeticPosition     *GeodeticPosition      `protobuf:"bytes,10,opt,name=geodetic_position,json=geodeticPosition,proto3" json:"geodetic_position,omitempty"`
	PolarVelocity        *PolarVelocity         `protobuf:"bytes,11,opt,name=polar_velocity,json=polarVelocity,proto3" json:"polar_velocity,omitempty"`
	PolarPosition        *PolarPosition         `protobuf:"bytes,12,opt,name=polar_position,json=polarPosition,proto3" json:"polar_position,omitempty"`
	TrackingMode         *TrackingMode          `protobuf:"varint,15,opt,name=tracking_mode,json=trackingMode,proto3,enum=com.vht.bms.messages.TrackingMode,oneof" json:"tracking_mode,omitempty"` // Refer to TrackingMode in TrackInfoEnum.proto
	ActiveMode           *ActiveMode            `protobuf:"varint,16,opt,name=active_mode,json=activeMode,proto3,enum=com.vht.bms.messages.ActiveMode,oneof" json:"active_mode,omitempty"`         // Refer to ActiveMode in TrackInfoEnum.proto
	CreatedTimestamp     *int64                 `protobuf:"varint,20,opt,name=created_timestamp,json=createdTimestamp,proto3,oneof" json:"created_timestamp,omitempty"`                            // Timestamp when track is created
	LastUpdatedTimestamp *int64                 `protobuf:"varint,21,opt,name=last_updated_timestamp,json=lastUpdatedTimestamp,proto3,oneof" json:"last_updated_timestamp,omitempty"`              // Timestamp when track is updated by a source track
	Timestamp            *int64                 `protobuf:"varint,22,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`                                                                  // Timestamp when track's kinematic state (position + velocity) is updated (by a source track or by prediction)
	SourceTracks         []*TrackMessage        `protobuf:"bytes,30,rep,name=source_tracks,json=sourceTracks,proto3" json:"source_tracks,omitempty"`
	// Additional fields
	NoDeleteFlag     *bool              `protobuf:"varint,50,opt,name=no_delete_flag,json=noDeleteFlag,proto3,oneof" json:"no_delete_flag,omitempty"`
	Jammed           *bool              `protobuf:"varint,51,opt,name=jammed,proto3,oneof" json:"jammed,omitempty"`
	Suppressed       *bool              `protobuf:"varint,52,opt,name=suppressed,proto3,oneof" json:"suppressed,omitempty"`
	Destroyed        *bool              `protobuf:"varint,53,opt,name=destroyed,proto3,oneof" json:"destroyed,omitempty"`
	ManeuverWarnings []*ManeuverWarning `protobuf:"bytes,54,rep,name=maneuver_warnings,json=maneuverWarnings,proto3" json:"maneuver_warnings,omitempty"`
	Confirmed        *bool              `protobuf:"varint,55,opt,name=confirmed,proto3,oneof" json:"confirmed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackMessage) Reset() {
	*x = TrackMessage{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMessage) ProtoMessage() {}

func (x *TrackMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMessage.ProtoReflect.Descriptor instead.
func (*TrackMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{1}
}

func (x *TrackMessage) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TrackMessage) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *TrackMessage) GetTrackInfo() *TrackInfo {
	if x != nil {
		return x.TrackInfo
	}
	return nil
}

func (x *TrackMessage) GetGeodeticPosition() *GeodeticPosition {
	if x != nil {
		return x.GeodeticPosition
	}
	return nil
}

func (x *TrackMessage) GetPolarVelocity() *PolarVelocity {
	if x != nil {
		return x.PolarVelocity
	}
	return nil
}

func (x *TrackMessage) GetPolarPosition() *PolarPosition {
	if x != nil {
		return x.PolarPosition
	}
	return nil
}

func (x *TrackMessage) GetTrackingMode() TrackingMode {
	if x != nil && x.TrackingMode != nil {
		return *x.TrackingMode
	}
	return TrackingMode_TRACKING_MODE_AUTOMATIC
}

func (x *TrackMessage) GetActiveMode() ActiveMode {
	if x != nil && x.ActiveMode != nil {
		return *x.ActiveMode
	}
	return ActiveMode_ACTIVE_MODE_TENTATIVE
}

func (x *TrackMessage) GetCreatedTimestamp() int64 {
	if x != nil && x.CreatedTimestamp != nil {
		return *x.CreatedTimestamp
	}
	return 0
}

func (x *TrackMessage) GetLastUpdatedTimestamp() int64 {
	if x != nil && x.LastUpdatedTimestamp != nil {
		return *x.LastUpdatedTimestamp
	}
	return 0
}

func (x *TrackMessage) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *TrackMessage) GetSourceTracks() []*TrackMessage {
	if x != nil {
		return x.SourceTracks
	}
	return nil
}

func (x *TrackMessage) GetNoDeleteFlag() bool {
	if x != nil && x.NoDeleteFlag != nil {
		return *x.NoDeleteFlag
	}
	return false
}

func (x *TrackMessage) GetJammed() bool {
	if x != nil && x.Jammed != nil {
		return *x.Jammed
	}
	return false
}

func (x *TrackMessage) GetSuppressed() bool {
	if x != nil && x.Suppressed != nil {
		return *x.Suppressed
	}
	return false
}

func (x *TrackMessage) GetDestroyed() bool {
	if x != nil && x.Destroyed != nil {
		return *x.Destroyed
	}
	return false
}

func (x *TrackMessage) GetManeuverWarnings() []*ManeuverWarning {
	if x != nil {
		return x.ManeuverWarnings
	}
	return nil
}

func (x *TrackMessage) GetConfirmed() bool {
	if x != nil && x.Confirmed != nil {
		return *x.Confirmed
	}
	return false
}

type TrackMessages struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrackMessageList []*TrackMessage        `protobuf:"bytes,1,rep,name=track_message_list,json=trackMessageList,proto3" json:"track_message_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackMessages) Reset() {
	*x = TrackMessages{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMessages) ProtoMessage() {}

func (x *TrackMessages) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMessages.ProtoReflect.Descriptor instead.
func (*TrackMessages) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{2}
}

func (x *TrackMessages) GetTrackMessageList() []*TrackMessage {
	if x != nil {
		return x.TrackMessageList
	}
	return nil
}

type ManeuverWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int32                 `protobuf:"varint,1,opt,name=type,proto3,oneof" json:"type,omitempty"` // 1 = SPEED; 2 = HEADING; 3 = ALTITUDE
	Delta         *float64               `protobuf:"fixed64,2,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	DeltaPercent  *float64               `protobuf:"fixed64,3,opt,name=delta_percent,json=deltaPercent,proto3,oneof" json:"delta_percent,omitempty"` // Value from 0 to 1, equal 0% to 100%
	Timestamp     *int64                 `protobuf:"varint,4,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`                            // Timestamp when the warning occur
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManeuverWarning) Reset() {
	*x = ManeuverWarning{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManeuverWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManeuverWarning) ProtoMessage() {}

func (x *ManeuverWarning) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManeuverWarning.ProtoReflect.Descriptor instead.
func (*ManeuverWarning) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{3}
}

func (x *ManeuverWarning) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *ManeuverWarning) GetDelta() float64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *ManeuverWarning) GetDeltaPercent() float64 {
	if x != nil && x.DeltaPercent != nil {
		return *x.DeltaPercent
	}
	return 0
}

func (x *ManeuverWarning) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type RemovedTrackEventMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemovedTrackId int32                  `protobuf:"varint,1,opt,name=removed_track_id,json=removedTrackId,proto3" json:"removed_track_id,omitempty"`
	SourceInfo     *SourceInfo            `protobuf:"bytes,3,opt,name=source_info,json=sourceInfo,proto3" json:"source_info,omitempty"`
	Uuid           *string                `protobuf:"bytes,4,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemovedTrackEventMessage) Reset() {
	*x = RemovedTrackEventMessage{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedTrackEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedTrackEventMessage) ProtoMessage() {}

func (x *RemovedTrackEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedTrackEventMessage.ProtoReflect.Descriptor instead.
func (*RemovedTrackEventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{4}
}

func (x *RemovedTrackEventMessage) GetRemovedTrackId() int32 {
	if x != nil {
		return x.RemovedTrackId
	}
	return 0
}

func (x *RemovedTrackEventMessage) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *RemovedTrackEventMessage) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type RemovedTracksEventMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RemovedTrackIdList []int32                `protobuf:"varint,1,rep,packed,name=removed_track_id_list,json=removedTrackIdList,proto3" json:"removed_track_id_list,omitempty"`
	SourceInfo         *SourceInfo            `protobuf:"bytes,3,opt,name=source_info,json=sourceInfo,proto3" json:"source_info,omitempty"`
	UuidList           []string               `protobuf:"bytes,4,rep,name=uuid_list,json=uuidList,proto3" json:"uuid_list,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RemovedTracksEventMessage) Reset() {
	*x = RemovedTracksEventMessage{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedTracksEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedTracksEventMessage) ProtoMessage() {}

func (x *RemovedTracksEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedTracksEventMessage.ProtoReflect.Descriptor instead.
func (*RemovedTracksEventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{5}
}

func (x *RemovedTracksEventMessage) GetRemovedTrackIdList() []int32 {
	if x != nil {
		return x.RemovedTrackIdList
	}
	return nil
}

func (x *RemovedTracksEventMessage) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *RemovedTracksEventMessage) GetUuidList() []string {
	if x != nil {
		return x.UuidList
	}
	return nil
}

type TrackStatisticsMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllIdList      []int32                `protobuf:"varint,1,rep,packed,name=all_id_list,json=allIdList,proto3" json:"all_id_list,omitempty"`
	StatisticIndex int32                  `protobuf:"varint,2,opt,name=statistic_index,json=statisticIndex,proto3" json:"statistic_index,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UuidList       []string               `protobuf:"bytes,5,rep,name=uuid_list,json=uuidList,proto3" json:"uuid_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackStatisticsMessage) Reset() {
	*x = TrackStatisticsMessage{}
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStatisticsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStatisticsMessage) ProtoMessage() {}

func (x *TrackStatisticsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStatisticsMessage.ProtoReflect.Descriptor instead.
func (*TrackStatisticsMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackMessage_proto_rawDescGZIP(), []int{6}
}

func (x *TrackStatisticsMessage) GetAllIdList() []int32 {
	if x != nil {
		return x.AllIdList
	}
	return nil
}

func (x *TrackStatisticsMessage) GetStatisticIndex() int32 {
	if x != nil {
		return x.StatisticIndex
	}
	return 0
}

func (x *TrackStatisticsMessage) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TrackStatisticsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrackStatisticsMessage) GetUuidList() []string {
	if x != nil {
		return x.UuidList
	}
	return nil
}

var File_pkg_ipc_TrackMessage_proto protoreflect.FileDescriptor

const file_pkg_ipc_TrackMessage_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/ipc/TrackMessage.proto\x12\x14com.vht.bms.messages\x1a pkg/proto/SpatialAttribute.proto\x1a\x17pkg/ipc/TrackInfo.proto\x1a\x1bpkg/ipc/TrackInfoEnum.proto\"\x80\x01\n" +
	"\n" +
	"SourceInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12F\n" +
	"\vsource_type\x18\x02 \x01(\x0e2 .com.vht.bms.messages.SourceTypeH\x01R\n" +
	"sourceType\x88\x01\x01B\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_source_type\"\xb1\t\n" +
	"\fTrackMessage\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12A\n" +
	"\vsource_info\x18\x02 \x01(\v2 .com.vht.bms.messages.SourceInfoR\n" +
	"sourceInfo\x12>\n" +
	"\n" +
	"track_info\x18\x04 \x01(\v2\x1f.com.vht.bms.messages.TrackInfoR\ttrackInfo\x12P\n" +
	"\x11geodetic_position\x18\n" +
	" \x01(\v2#.spatial_attribute.GeodeticPositionR\x10geodeticPosition\x12G\n" +
	"\x0epolar_velocity\x18\v \x01(\v2 .spatial_attribute.PolarVelocityR\rpolarVelocity\x12G\n" +
	"\x0epolar_position\x18\f \x01(\v2 .spatial_attribute.PolarPositionR\rpolarPosition\x12L\n" +
	"\rtracking_mode\x18\x0f \x01(\x0e2\".com.vht.bms.messages.TrackingModeH\x01R\ftrackingMode\x88\x01\x01\x12F\n" +
	"\vactive_mode\x18\x10 \x01(\x0e2 .com.vht.bms.messages.ActiveModeH\x02R\n" +
	"activeMode\x88\x01\x01\x120\n" +
	"\x11created_timestamp\x18\x14 \x01(\x03H\x03R\x10createdTimestamp\x88\x01\x01\x129\n" +
	"\x16last_updated_timestamp\x18\x15 \x01(\x03H\x04R\x14lastUpdatedTimestamp\x88\x01\x01\x12!\n" +
	"\ttimestamp\x18\x16 \x01(\x03H\x05R\ttimestamp\x88\x01\x01\x12G\n" +
	"\rsource_tracks\x18\x1e \x03(\v2\".com.vht.bms.messages.TrackMessageR\fsourceTracks\x12)\n" +
	"\x0eno_delete_flag\x182 \x01(\bH\x06R\fnoDeleteFlag\x88\x01\x01\x12\x1b\n" +
	"\x06jammed\x183 \x01(\bH\aR\x06jammed\x88\x01\x01\x12#\n" +
	"\n" +
	"suppressed\x184 \x01(\bH\bR\n" +
	"suppressed\x88\x01\x01\x12!\n" +
	"\tdestroyed\x185 \x01(\bH\tR\tdestroyed\x88\x01\x01\x12R\n" +
	"\x11maneuver_warnings\x186 \x03(\v2%.com.vht.bms.messages.ManeuverWarningR\x10maneuverWarnings\x12!\n" +
	"\tconfirmed\x187 \x01(\bH\n" +
	"R\tconfirmed\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_tracking_modeB\x0e\n" +
	"\f_active_modeB\x14\n" +
	"\x12_created_timestampB\x19\n" +
	"\x17_last_updated_timestampB\f\n" +
	"\n" +
	"_timestampB\x11\n" +
	"\x0f_no_delete_flagB\t\n" +
	"\a_jammedB\r\n" +
	"\v_suppressedB\f\n" +
	"\n" +
	"_destroyedB\f\n" +
	"\n" +
	"_confirmed\"a\n" +
	"\rTrackMessages\x12P\n" +
	"\x12track_message_list\x18\x01 \x03(\v2\".com.vht.bms.messages.TrackMessageR\x10trackMessageList\"\xc5\x01\n" +
	"\x0fManeuverWarning\x12\x17\n" +
	"\x04type\x18\x01 \x01(\x05H\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05delta\x18\x02 \x01(\x01H\x01R\x05delta\x88\x01\x01\x12(\n" +
	"\rdelta_percent\x18\x03 \x01(\x01H\x02R\fdeltaPercent\x88\x01\x01\x12!\n" +
	"\ttimestamp\x18\x04 \x01(\x03H\x03R\ttimestamp\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_deltaB\x10\n" +
	"\x0e_delta_percentB\f\n" +
	"\n" +
	"_timestamp\"\xa9\x01\n" +
	"\x18RemovedTrackEventMessage\x12(\n" +
	"\x10removed_track_id\x18\x01 \x01(\x05R\x0eremovedTrackId\x12A\n" +
	"\vsource_info\x18\x03 \x01(\v2 .com.vht.bms.messages.SourceInfoR\n" +
	"sourceInfo\x12\x17\n" +
	"\x04uuid\x18\x04 \x01(\tH\x00R\x04uuid\x88\x01\x01B\a\n" +
	"\x05_uuid\"\xae\x01\n" +
	"\x19RemovedTracksEventMessage\x121\n" +
	"\x15removed_track_id_list\x18\x01 \x03(\x05R\x12removedTrackIdList\x12A\n" +
	"\vsource_info\x18\x03 \x01(\v2 .com.vht.bms.messages.SourceInfoR\n" +
	"sourceInfo\x12\x1b\n" +
	"\tuuid_list\x18\x04 \x03(\tR\buuidList\"\xb9\x01\n" +
	"\x16TrackStatisticsMessage\x12\x1e\n" +
	"\vall_id_list\x18\x01 \x03(\x05R\tallIdList\x12'\n" +
	"\x0fstatistic_index\x18\x02 \x01(\x05R\x0estatisticIndex\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tuuid_list\x18\x05 \x03(\tR\buuidListB7\n" +
	"\x1acom.vht.bms.messages.trackB\x11TrackMessageProtoZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_ipc_TrackMessage_proto_rawDescOnce sync.Once
	file_pkg_ipc_TrackMessage_proto_rawDescData []byte
)

func file_pkg_ipc_TrackMessage_proto_rawDescGZIP() []byte {
	file_pkg_ipc_TrackMessage_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_TrackMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipc_TrackMessage_proto_rawDesc), len(file_pkg_ipc_TrackMessage_proto_rawDesc)))
	})
	return file_pkg_ipc_TrackMessage_proto_rawDescData
}

var file_pkg_ipc_TrackMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_ipc_TrackMessage_proto_goTypes = []any{
	(*SourceInfo)(nil),                // 0: com.vht.bms.messages.SourceInfo
	(*TrackMessage)(nil),              // 1: com.vht.bms.messages.TrackMessage
	(*TrackMessages)(nil),             // 2: com.vht.bms.messages.TrackMessages
	(*ManeuverWarning)(nil),           // 3: com.vht.bms.messages.ManeuverWarning
	(*RemovedTrackEventMessage)(nil),  // 4: com.vht.bms.messages.RemovedTrackEventMessage
	(*RemovedTracksEventMessage)(nil), // 5: com.vht.bms.messages.RemovedTracksEventMessage
	(*TrackStatisticsMessage)(nil),    // 6: com.vht.bms.messages.TrackStatisticsMessage
	(SourceType)(0),                   // 7: com.vht.bms.messages.SourceType
	(*TrackInfo)(nil),                 // 8: com.vht.bms.messages.TrackInfo
	(*GeodeticPosition)(nil),          // 9: spatial_attribute.GeodeticPosition
	(*PolarVelocity)(nil),             // 10: spatial_attribute.PolarVelocity
	(*PolarPosition)(nil),             // 11: spatial_attribute.PolarPosition
	(TrackingMode)(0),                 // 12: com.vht.bms.messages.TrackingMode
	(ActiveMode)(0),                   // 13: com.vht.bms.messages.ActiveMode
}
var file_pkg_ipc_TrackMessage_proto_depIdxs = []int32{
	7,  // 0: com.vht.bms.messages.SourceInfo.source_type:type_name -> com.vht.bms.messages.SourceType
	0,  // 1: com.vht.bms.messages.TrackMessage.source_info:type_name -> com.vht.bms.messages.SourceInfo
	8,  // 2: com.vht.bms.messages.TrackMessage.track_info:type_name -> com.vht.bms.messages.TrackInfo
	9,  // 3: com.vht.bms.messages.TrackMessage.geodetic_position:type_name -> spatial_attribute.GeodeticPosition
	10, // 4: com.vht.bms.messages.TrackMessage.polar_velocity:type_name -> spatial_attribute.PolarVelocity
	11, // 5: com.vht.bms.messages.TrackMessage.polar_position:type_name -> spatial_attribute.PolarPosition
	12, // 6: com.vht.bms.messages.TrackMessage.tracking_mode:type_name -> com.vht.bms.messages.TrackingMode
	13, // 7: com.vht.bms.messages.TrackMessage.active_mode:type_name -> com.vht.bms.messages.ActiveMode
	1,  // 8: com.vht.bms.messages.TrackMessage.source_tracks:type_name -> com.vht.bms.messages.TrackMessage
	3,  // 9: com.vht.bms.messages.TrackMessage.maneuver_warnings:type_name -> com.vht.bms.messages.ManeuverWarning
	1,  // 10: com.vht.bms.messages.TrackMessages.track_message_list:type_name -> com.vht.bms.messages.TrackMessage
	0,  // 11: com.vht.bms.messages.RemovedTrackEventMessage.source_info:type_name -> com.vht.bms.messages.SourceInfo
	0,  // 12: com.vht.bms.messages.RemovedTracksEventMessage.source_info:type_name -> com.vht.bms.messages.SourceInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_ipc_TrackMessage_proto_init() }
func file_pkg_ipc_TrackMessage_proto_init() {
	if File_pkg_ipc_TrackMessage_proto != nil {
		return
	}
	file_pkg_proto_SpatialAttribute_proto_init()
	file_pkg_ipc_TrackInfo_proto_init()
	file_pkg_ipc_TrackInfoEnum_proto_init()
	file_pkg_ipc_TrackMessage_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_ipc_TrackMessage_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_ipc_TrackMessage_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_ipc_TrackMessage_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipc_TrackMessage_proto_rawDesc), len(file_pkg_ipc_TrackMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ipc_TrackMessage_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_TrackMessage_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_TrackMessage_proto_msgTypes,
	}.Build()
	File_pkg_ipc_TrackMessage_proto = out.File
	file_pkg_ipc_TrackMessage_proto_goTypes = nil
	file_pkg_ipc_TrackMessage_proto_depIdxs = nil
}
