// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/ipc/TrackInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AircraftInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Mode_3A      *string                `protobuf:"bytes,1,opt,name=mode_3a,json=mode3a,proto3,oneof" json:"mode_3a,omitempty"`                                                           // Mode 3/A of aircraft: a string of 4-digit
	ModeS        *string                `protobuf:"bytes,2,opt,name=mode_s,json=modeS,proto3,oneof" json:"mode_s,omitempty"`                                                              // Mode S of aircraft: a string of 6 hex-code
	AircraftType *AircraftType          `protobuf:"varint,3,opt,name=aircraft_type,json=aircraftType,proto3,enum=com.vht.bms.messages.AircraftType,oneof" json:"aircraft_type,omitempty"` // Refer to AircraftType in TrackInfoEnum.proto
	// Number of aircraft in one formation:
	// If aircraft in formation fly closely together, sensor with low resolution will see them as one target.
	// That's why we need this field to identify the real number of aircraft in one target.
	AircraftCount *int32  `protobuf:"varint,4,opt,name=aircraft_count,json=aircraftCount,proto3,oneof" json:"aircraft_count,omitempty"`
	SpecialLabel  *string `protobuf:"bytes,5,opt,name=special_label,json=specialLabel,proto3,oneof" json:"special_label,omitempty"` // Aircraft of important flight (for example: flight of president), often be assigned a label so all operators can recognized it quickly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AircraftInfo) Reset() {
	*x = AircraftInfo{}
	mi := &file_pkg_ipc_TrackInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftInfo) ProtoMessage() {}

func (x *AircraftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftInfo.ProtoReflect.Descriptor instead.
func (*AircraftInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackInfo_proto_rawDescGZIP(), []int{0}
}

func (x *AircraftInfo) GetMode_3A() string {
	if x != nil && x.Mode_3A != nil {
		return *x.Mode_3A
	}
	return ""
}

func (x *AircraftInfo) GetModeS() string {
	if x != nil && x.ModeS != nil {
		return *x.ModeS
	}
	return ""
}

func (x *AircraftInfo) GetAircraftType() AircraftType {
	if x != nil && x.AircraftType != nil {
		return *x.AircraftType
	}
	return AircraftType_AIRCRAFT_TYPE_UNKNOWN
}

func (x *AircraftInfo) GetAircraftCount() int32 {
	if x != nil && x.AircraftCount != nil {
		return *x.AircraftCount
	}
	return 0
}

func (x *AircraftInfo) GetSpecialLabel() string {
	if x != nil && x.SpecialLabel != nil {
		return *x.SpecialLabel
	}
	return ""
}

type TrackInfo struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Name             *string                 `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	CallSign         *string                 `protobuf:"bytes,2,opt,name=call_sign,json=callSign,proto3,oneof" json:"call_sign,omitempty"`
	FriendFoeState   *AircraftFriendFoeState `protobuf:"varint,4,opt,name=friend_foe_state,json=friendFoeState,proto3,enum=com.vht.bms.messages.AircraftFriendFoeState,oneof" json:"friend_foe_state,omitempty"`
	HeightSourceType *HeightSourceType       `protobuf:"varint,9,opt,name=height_source_type,json=heightSourceType,proto3,enum=com.vht.bms.messages.HeightSourceType,oneof" json:"height_source_type,omitempty"` // Refer to HeightSourceType in TrackInfoEnum.proto
	AircraftInfo     *AircraftInfo           `protobuf:"bytes,15,opt,name=aircraft_info,json=aircraftInfo,proto3,oneof" json:"aircraft_info,omitempty"`
	// Additional info for TN24 military drill
	TrackQuality *int32 `protobuf:"varint,40,opt,name=track_quality,json=trackQuality,proto3,oneof" json:"track_quality,omitempty"`
	// todo dinh nghia
	// Enum value
	// 0 = UNKNOWN;
	// 1 = NORMAL
	// 2 = LOST_CONTROL; 3 = LOST_ALTITUDE; 4 = LOST_CONTROL_AND_ALTITUDE;
	ManeuverStatus *int32 `protobuf:"varint,43,opt,name=maneuver_status,json=maneuverStatus,proto3,oneof" json:"maneuver_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_pkg_ipc_TrackInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_TrackInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_TrackInfo_proto_rawDescGZIP(), []int{1}
}

func (x *TrackInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TrackInfo) GetCallSign() string {
	if x != nil && x.CallSign != nil {
		return *x.CallSign
	}
	return ""
}

func (x *TrackInfo) GetFriendFoeState() AircraftFriendFoeState {
	if x != nil && x.FriendFoeState != nil {
		return *x.FriendFoeState
	}
	return AircraftFriendFoeState_AIR_FRIEND_FOE_STATE_UNKNOWN
}

func (x *TrackInfo) GetHeightSourceType() HeightSourceType {
	if x != nil && x.HeightSourceType != nil {
		return *x.HeightSourceType
	}
	return HeightSourceType_HEIGHT_SOURCE_TYPE_UNKNOWN
}

func (x *TrackInfo) GetAircraftInfo() *AircraftInfo {
	if x != nil {
		return x.AircraftInfo
	}
	return nil
}

func (x *TrackInfo) GetTrackQuality() int32 {
	if x != nil && x.TrackQuality != nil {
		return *x.TrackQuality
	}
	return 0
}

func (x *TrackInfo) GetManeuverStatus() int32 {
	if x != nil && x.ManeuverStatus != nil {
		return *x.ManeuverStatus
	}
	return 0
}

var File_pkg_ipc_TrackInfo_proto protoreflect.FileDescriptor

const file_pkg_ipc_TrackInfo_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/ipc/TrackInfo.proto\x12\x14com.vht.bms.messages\x1a\x1bpkg/ipc/TrackInfoEnum.proto\"\xba\x02\n" +
	"\fAircraftInfo\x12\x1c\n" +
	"\amode_3a\x18\x01 \x01(\tH\x00R\x06mode3a\x88\x01\x01\x12\x1a\n" +
	"\x06mode_s\x18\x02 \x01(\tH\x01R\x05modeS\x88\x01\x01\x12L\n" +
	"\raircraft_type\x18\x03 \x01(\x0e2\".com.vht.bms.messages.AircraftTypeH\x02R\faircraftType\x88\x01\x01\x12*\n" +
	"\x0eaircraft_count\x18\x04 \x01(\x05H\x03R\raircraftCount\x88\x01\x01\x12(\n" +
	"\rspecial_label\x18\x05 \x01(\tH\x04R\fspecialLabel\x88\x01\x01B\n" +
	"\n" +
	"\b_mode_3aB\t\n" +
	"\a_mode_sB\x10\n" +
	"\x0e_aircraft_typeB\x11\n" +
	"\x0f_aircraft_countB\x10\n" +
	"\x0e_special_label\"\x9f\x04\n" +
	"\tTrackInfo\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tcall_sign\x18\x02 \x01(\tH\x01R\bcallSign\x88\x01\x01\x12[\n" +
	"\x10friend_foe_state\x18\x04 \x01(\x0e2,.com.vht.bms.messages.AircraftFriendFoeStateH\x02R\x0efriendFoeState\x88\x01\x01\x12Y\n" +
	"\x12height_source_type\x18\t \x01(\x0e2&.com.vht.bms.messages.HeightSourceTypeH\x03R\x10heightSourceType\x88\x01\x01\x12L\n" +
	"\raircraft_info\x18\x0f \x01(\v2\".com.vht.bms.messages.AircraftInfoH\x04R\faircraftInfo\x88\x01\x01\x12(\n" +
	"\rtrack_quality\x18( \x01(\x05H\x05R\ftrackQuality\x88\x01\x01\x12,\n" +
	"\x0fmaneuver_status\x18+ \x01(\x05H\x06R\x0emaneuverStatus\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_call_signB\x13\n" +
	"\x11_friend_foe_stateB\x15\n" +
	"\x13_height_source_typeB\x10\n" +
	"\x0e_aircraft_infoB\x10\n" +
	"\x0e_track_qualityB\x12\n" +
	"\x10_maneuver_statusB4\n" +
	"\x1acom.vht.bms.messages.trackB\x0eTrackInfoProtoZ\x06pkg/pbb\x06proto3"

var (
	file_pkg_ipc_TrackInfo_proto_rawDescOnce sync.Once
	file_pkg_ipc_TrackInfo_proto_rawDescData []byte
)

func file_pkg_ipc_TrackInfo_proto_rawDescGZIP() []byte {
	file_pkg_ipc_TrackInfo_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_TrackInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipc_TrackInfo_proto_rawDesc), len(file_pkg_ipc_TrackInfo_proto_rawDesc)))
	})
	return file_pkg_ipc_TrackInfo_proto_rawDescData
}

var file_pkg_ipc_TrackInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ipc_TrackInfo_proto_goTypes = []any{
	(*AircraftInfo)(nil),        // 0: com.vht.bms.messages.AircraftInfo
	(*TrackInfo)(nil),           // 1: com.vht.bms.messages.TrackInfo
	(AircraftType)(0),           // 2: com.vht.bms.messages.AircraftType
	(AircraftFriendFoeState)(0), // 3: com.vht.bms.messages.AircraftFriendFoeState
	(HeightSourceType)(0),       // 4: com.vht.bms.messages.HeightSourceType
}
var file_pkg_ipc_TrackInfo_proto_depIdxs = []int32{
	2, // 0: com.vht.bms.messages.AircraftInfo.aircraft_type:type_name -> com.vht.bms.messages.AircraftType
	3, // 1: com.vht.bms.messages.TrackInfo.friend_foe_state:type_name -> com.vht.bms.messages.AircraftFriendFoeState
	4, // 2: com.vht.bms.messages.TrackInfo.height_source_type:type_name -> com.vht.bms.messages.HeightSourceType
	0, // 3: com.vht.bms.messages.TrackInfo.aircraft_info:type_name -> com.vht.bms.messages.AircraftInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_ipc_TrackInfo_proto_init() }
func file_pkg_ipc_TrackInfo_proto_init() {
	if File_pkg_ipc_TrackInfo_proto != nil {
		return
	}
	file_pkg_ipc_TrackInfoEnum_proto_init()
	file_pkg_ipc_TrackInfo_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_ipc_TrackInfo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipc_TrackInfo_proto_rawDesc), len(file_pkg_ipc_TrackInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ipc_TrackInfo_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_TrackInfo_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_TrackInfo_proto_msgTypes,
	}.Build()
	File_pkg_ipc_TrackInfo_proto = out.File
	file_pkg_ipc_TrackInfo_proto_goTypes = nil
	file_pkg_ipc_TrackInfo_proto_depIdxs = nil
}
