#!/bin/bash

echo '// Code generated by custom.generate.sh.
// source: pkg/pb/*.proto
// template: pkg/custom.template
// DO NOT EDIT!
package pb

import (
	"reflect"

	"github.com/nguyenngodinh/qmgo/field"
)
const AUDIT_USER = "X-Username"' > pb/QmgoCustom.go

files=`ls ./proto/*.proto`
for proto in $files
do
    input=$proto
    while IFS= read -r line
    do
        # echo "line: --------- $line"
        if [[ $line == "message "*" {" ]]; then
            # echo "message: ====> $line"
            msg=$line
            arr=(${msg//"message "/ })
            Model=$arr
            echo $Model

            cp custom.template $Model.template
            sed -i "s/CustomTemplate/$Model/g" $Model.template
            cat $Model.template >> pb/QmgoCustom.go
            rm $Model.template
            
        fi
    done < "$input"
done